/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/ingredients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List or search ingredients
         * @description Without `q`, lists ingredients alphabetically with cursor pagination. With `q`, searches by name and returns the best matches, not paginated.
         */
        get: operations["listIngredients"];
        put?: never;
        /** Create a custom ingredient */
        post: operations["createIngredient"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ingredients/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a custom ingredient */
        delete: operations["deleteIngredient"];
        options?: never;
        head?: never;
        /**
         * Update a custom ingredient
         * @description Fields that are absent are left unchanged. Only a custom ingredient owned by the caller can be updated. Clearing `grams_per_piece` or `density_g_per_ml` while a meal still uses this ingredient with the `piece` or `ml` unit is rejected (`409 unit_not_convertible`).
         */
        patch: operations["updateIngredient"];
        trace?: never;
    };
    "/diet-templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the caller's diet templates
         * @description Cursor-paginated, alphabetical by name. Lists only the caller's own templates (the partner's shared ones are at `GET /partner/diet-templates`). Does not include slots; fetch a single template for those.
         */
        get: operations["listDietTemplates"];
        put?: never;
        /**
         * Create a diet template
         * @description Creates the template with no slots. Add slots with `PUT /diet-templates/{id}/slots`.
         */
        post: operations["createDietTemplate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/diet-templates/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /**
         * Get a diet template
         * @description Includes the slot list. Returns the caller's own template, or a template the partner has shared (`is_owner` false), whose slots show each meal's id and name even if that meal is not shared itself (its detail stays `404`). Any other template is `404`.
         */
        get: operations["getDietTemplate"];
        put?: never;
        post?: never;
        /**
         * Delete a diet template
         * @description Any plan entries created by applying this template keep their row, with from_template_id set to null.
         */
        delete: operations["deleteDietTemplate"];
        options?: never;
        head?: never;
        /**
         * Update a diet template
         * @description Fields that are absent are left unchanged. day_count cannot be changed after creation; recreate or copy the template instead.
         */
        patch: operations["updateDietTemplate"];
        trace?: never;
    };
    "/diet-templates/{id}/slots": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        /**
         * Replace a diet template's slot list
         * @description Atomically replaces the full slot list. Every row is validated (day_index must be within the template's day_count, and the meal must exist and be visible to the caller) before anything is written; an empty `items` array clears the list.
         */
        put: operations["replaceTemplateSlots"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/diet-templates/{id}/apply": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Apply a template to the plan
         * @description Copies the template's slots into plan entries starting at `start_date`. Without `overwrite`, fails if any non-snack target date+slot already has an entry; snack slots are always added. With `overwrite`, the same non-snack targets are replaced.
         */
        post: operations["applyDietTemplate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/diet-templates/{id}/copy": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Copy a diet template
         * @description Creates a new template, owned by the caller, with the same name, day_count and slots. The original may be the caller's own or one the partner has shared. Copying the partner's template also copies its meals (each once, with the same ingredient rules as `POST /meals/{id}/copy`), so the copy can be applied to the caller's own plan. The copy always starts with `shared_with_partner` false.
         */
        post: operations["copyDietTemplate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/meals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the caller's meals
         * @description Cursor-paginated, alphabetical by name. Lists only the caller's own meals (the partner's shared ones are at `GET /partner/meals`). Does not include ingredients or computed nutrition; fetch a single meal for those.
         */
        get: operations["listMeals"];
        put?: never;
        /**
         * Create a meal
         * @description Creates the meal with an empty ingredient list. Add ingredients with `PUT /meals/{id}/ingredients`.
         */
        post: operations["createMeal"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/meals/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /**
         * Get a meal
         * @description Includes the ingredient list and nutrition per serving, computed on read. Returns the caller's own meal, or a meal the partner has shared (`is_owner` false). Any other meal is `404`.
         */
        get: operations["getMeal"];
        put?: never;
        post?: never;
        /** Delete a meal */
        delete: operations["deleteMeal"];
        options?: never;
        head?: never;
        /**
         * Update a meal
         * @description Fields that are absent are left unchanged. Only the owner can update a meal; for anyone else, including the partner, it is `404`.
         */
        patch: operations["updateMeal"];
        trace?: never;
    };
    "/meals/{id}/ingredients": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        /**
         * Replace a meal's ingredient list
         * @description Atomically replaces the full ingredient list. Every row is validated (the ingredient must exist and be visible to the caller, and its unit must be convertible) before anything is written; an empty `items` array clears the list.
         */
        put: operations["replaceMealIngredients"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/meals/{id}/copy": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Copy a meal
         * @description Creates a new meal, owned by the caller, with the same name, notes, servings and ingredients. The original may be the caller's own or one the partner has shared. Copying the partner's meal also copies each custom ingredient it uses into the caller's library (once per copy; global ingredients are shared). The copy always starts with `shared_with_partner` false.
         */
        post: operations["copyMeal"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the plan for a date range
         * @description One DailyTotal per calendar date in [from, to] inclusive, with nutrition computed from each entry's meal and compared against the caller's targets. Capped at 92 days.
         */
        get: operations["getPlan"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/plan/{date}/{slot}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                date: string;
                slot: components["schemas"]["Slot"];
            };
            cookie?: never;
        };
        get?: never;
        /**
         * Set or swap the meal for a date and slot
         * @description For breakfast/lunch/dinner this upserts the one entry for that date+slot. For snack, since the URL can't select among several, this always adds a new entry. Either way, the written entry's from_template_id is null.
         */
        put: operations["setPlanEntry"];
        post?: never;
        /**
         * Remove the plan entry (or entries) for a date and slot
         * @description For breakfast/lunch/dinner this removes the one entry. For snack this removes every snack entry for that date.
         */
        delete: operations["deletePlanEntry"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/shopping-lists": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the caller's shopping lists
         * @description Cursor-paginated, newest first. Lists only the caller's own lists (the partner's shared ones are at `GET /partner/shopping-lists`). Does not include items; fetch a single list for those.
         */
        get: operations["listShoppingLists"];
        put?: never;
        /**
         * Create an empty shopping list
         * @description Creates a list with no items and no source date range. Add items with `POST /shopping-lists/{id}/items`, or use `POST /shopping-lists/generate` to build one from the plan.
         */
        post: operations["createShoppingList"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/shopping-lists/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate a shopping list from the plan
         * @description Sums the ingredients of every plan entry in [from, to] inclusive (capped at 92 days), merging lines of the same ingredient, and groups them by category. Without `list_id` this creates a new list (201). With `list_id` it regenerates that list (200), replacing every `generated` item, keeping every `manual` item untouched, and updating its source range.
         */
        post: operations["generateShoppingList"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/shopping-lists/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /**
         * Get a shopping list
         * @description Includes every item, ordered by position. Returns the caller's own list, or a list the partner has shared (`is_owner` false). Any other list is `404`. Renaming, deleting, sharing and regenerating are owner-only (`404` for the partner); the partner may add, edit, check and delete items, and open the event stream.
         */
        get: operations["getShoppingList"];
        put?: never;
        post?: never;
        /**
         * Delete a shopping list
         * @description Deletes the list and all of its items. Open event streams for the list receive a final `list_deleted` event and are closed.
         */
        delete: operations["deleteShoppingList"];
        options?: never;
        head?: never;
        /**
         * Update a shopping list
         * @description Fields that are absent are left unchanged.
         */
        patch: operations["updateShoppingList"];
        trace?: never;
    };
    "/shopping-lists/{id}/items": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add an item to a shopping list
         * @description Adds a `manual` item at the end of the list. With `ingredient_id`, the ingredient must be visible to the caller, and `category` defaults to the ingredient's category; without it, `category` defaults to `other`.
         */
        post: operations["createShoppingItem"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/shopping-lists/{id}/items/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                item_id: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Remove an item from a shopping list
         * @description Removes the item regardless of its version (removes merge, per the sync rules).
         */
        delete: operations["deleteShoppingItem"];
        options?: never;
        head?: never;
        /**
         * Edit or check off a shopping item
         * @description Fields that are absent are left unchanged. Changing `name`, `quantity`, `unit` or `category` requires `version`, which must equal the item's current version, or the request fails with `409 version_conflict` carrying the current item in `current`. A request that changes only `checked` is last-write-wins and does not need `version`; setting `checked` to the value it already has is a no-op that returns the item unchanged. Every change increments `version`.
         */
        patch: operations["updateShoppingItem"];
        trace?: never;
    };
    "/shopping-lists/{id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        /**
         * Stream live changes to a shopping list
         * @description A Server-Sent Events stream. Each event's `event:` field is its type and its `data:` field is one JSON object `{"type", "list_id", "item_id"?, "version"?}`. `item_changed` and `item_deleted` carry `item_id` and the item's `version` (for `item_deleted`, the version the item had when it was removed); `list_changed` (renamed or regenerated) and `list_deleted` carry only `type` and `list_id`. After `list_deleted` the server closes the stream. Comment lines (`: keep-alive`) are sent every 25 seconds. The server may also close the stream at any time (shutdown, or a client too slow to keep up); clients reconnect and refetch the list, and refetch whenever they see a version gap. Events for the same item can arrive out of order; a client should ignore an event whose `version` is less than or equal to the version it already has for that item. Authenticate with the `Authorization` header like every other route: access tokens are never accepted in the query string.
         */
        get: operations["streamShoppingListEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/partner": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the caller's partnership
         * @description Returns the active partnership (the partner's `display_name` and `linked_at`), or the caller's own pending invite (`expires_at`; the code is never returned again). `404 partner_not_linked` when there is neither, and also once a pending invite has expired.
         */
        get: operations["getPartner"];
        put?: never;
        post?: never;
        /**
         * End the partnership or cancel a pending invite
         * @description Either side may unlink. Access ends at once, so the former partner's next read of shared meals, diet templates and shopping lists is `404`, and their open shopping-list event streams are closed. Every list, meal and template stays with its owner; copies are independent. Re-linking needs a fresh invite.
         */
        delete: operations["unlinkPartner"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/partner/invite": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create an invite code
         * @description Creates an invite for the caller and returns its code, which is shown only here (only its hash is stored). The code has 8 characters from `23456789ABCDEFGHJKMNPQRSTUVWXYZ` and expires after 48 hours. A new invite replaces the caller's pending one. `409 partner_already_linked` if the caller already has a partner.
         */
        post: operations["createPartnerInvite"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/partner/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Accept an invite code
         * @description Links the caller with the user who issued the code. A wrong, expired, own or already used code all return the same `404 invite_invalid`. A caller who already has a partner gets `409 partner_already_linked` whatever the code. Case, spaces and dashes in the code do not matter. This route has its own, tighter rate limit (per user and per client IP).
         */
        post: operations["acceptPartnerInvite"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/partner/meals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the meals the partner has shared
         * @description Cursor-paginated, alphabetical by name, like `GET /meals`, but only the meals the partner has marked `shared_with_partner`, never the caller's own. Open one with `GET /meals/{id}` (`is_owner` is false) or copy it with `POST /meals/{id}/copy`. `404 partner_not_linked` without an active partner.
         */
        get: operations["listPartnerMeals"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/partner/diet-templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the diet templates the partner has shared
         * @description Cursor-paginated, alphabetical by name, like `GET /diet-templates`, but only the templates the partner has marked `shared_with_partner`, never the caller's own. Open one with `GET /diet-templates/{id}` (`is_owner` is false) or copy it with `POST /diet-templates/{id}/copy`, which copies its meals too. `404 partner_not_linked` without an active partner.
         */
        get: operations["listPartnerDietTemplates"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/partner/shopping-lists": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List the shopping lists the partner has shared
         * @description Cursor-paginated, newest first, like `GET /shopping-lists`, but only the lists the partner has marked `shared_with_partner`, never the caller's own. Open one with `GET /shopping-lists/{id}` (`is_owner` is false); both partners may edit its items. `404 partner_not_linked` without an active partner.
         */
        get: operations["listPartnerShoppingLists"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness probe
         * @description Returns 200 when the process is up. Does not touch the database.
         */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness probe
         * @description Returns 200 when the service can reach its database, 503 otherwise.
         */
        get: operations["getReady"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create an account
         * @description Creates an account with email and password and signs the user in.
         */
        post: operations["registerUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sign in with email and password */
        post: operations["loginUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Exchange a refresh token for a new token pair
         * @description Rotates the refresh token. Presenting an already-used refresh token revokes the whole session family.
         */
        post: operations["refreshSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Revoke a refresh-token session
         * @description Idempotent. An unknown or already-revoked token is not an error.
         */
        post: operations["logoutUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the signed-in user's profile */
        get: operations["getMe"];
        put?: never;
        post?: never;
        /**
         * Delete the signed-in user's account
         * @description Permanently deletes the account and everything it owns.
         */
        delete: operations["deleteMe"];
        options?: never;
        head?: never;
        /**
         * Update the signed-in user's profile
         * @description Fields that are absent are left unchanged. A daily target set to null is cleared.
         */
        patch: operations["updateMe"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Health: {
            /** @enum {string} */
            status: "ok";
        };
        /** @description RFC 9457 problem details with a stable machine-readable code. */
        Problem: {
            /** Format: uri-reference */
            type: string;
            title: string;
            status: number;
            detail?: string;
            /** @description Stable identifier clients map to localized text, e.g. partner_not_linked. */
            code: string;
            /** @description Per-field details, present on validation_failed problems. */
            errors?: components["schemas"]["FieldError"][];
        };
        FieldError: {
            /** @description Path of the offending JSON field, e.g. `email`. */
            field: string;
            /** @description Stable identifier, e.g. required, too_short, too_long, invalid_format, invalid_type, invalid_value. */
            code: string;
        };
        User: {
            /** Format: uuid */
            id: string;
            email: string;
            display_name: string;
            /** Format: double */
            target_kcal?: number | null;
            /** Format: double */
            target_protein_g?: number | null;
            /** Format: double */
            target_carbs_g?: number | null;
            /** Format: double */
            target_fat_g?: number | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        RegisterRequest: {
            /** Format: email */
            email: string;
            password: string;
            display_name: string;
        };
        LoginRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        RefreshRequest: {
            refresh_token: string;
        };
        AuthResponse: {
            access_token: string;
            refresh_token: string;
            /** @enum {string} */
            token_type: "Bearer";
            /** @description Access token lifetime in seconds. */
            expires_in: number;
            user: components["schemas"]["User"];
        };
        UpdateProfileRequest: {
            display_name?: string;
            /** Format: double */
            target_kcal?: number | null;
            /** Format: double */
            target_protein_g?: number | null;
            /** Format: double */
            target_carbs_g?: number | null;
            /** Format: double */
            target_fat_g?: number | null;
        };
        /** @enum {string} */
        IngredientCategory: "produce" | "dairy_eggs" | "meat_seafood" | "grains_bread" | "legumes_nuts_seeds" | "condiments_oils" | "spices_herbs" | "beverages" | "sweets_snacks" | "other";
        /** @description Amount per 100 g for each tracked nutrient. A null value means the amount is unknown. Units: kcal for calories; g for protein, carbohydrates, sugar, fibre, fat and saturated_fat; mg for sodium, potassium, calcium, iron, magnesium, zinc and vitamin_c; µg for vitamin_a, vitamin_d, vitamin_b12 and folate. */
        NutrientAmounts: {
            /** Format: double */
            calories: number | null;
            /** Format: double */
            protein: number | null;
            /** Format: double */
            carbohydrates: number | null;
            /** Format: double */
            sugar: number | null;
            /** Format: double */
            fibre: number | null;
            /** Format: double */
            fat: number | null;
            /** Format: double */
            saturated_fat: number | null;
            /** Format: double */
            sodium: number | null;
            /** Format: double */
            potassium: number | null;
            /** Format: double */
            calcium: number | null;
            /** Format: double */
            iron: number | null;
            /** Format: double */
            magnesium: number | null;
            /** Format: double */
            zinc: number | null;
            /** Format: double */
            vitamin_a: number | null;
            /** Format: double */
            vitamin_c: number | null;
            /** Format: double */
            vitamin_d: number | null;
            /** Format: double */
            vitamin_b12: number | null;
            /** Format: double */
            folate: number | null;
        };
        /** @description Amount per 100 g for each tracked nutrient the caller wants to set. Supplying the `nutrients` field replaces the ingredient's entire nutrient set — any of the 18 keys omitted, or explicitly set to null, is cleared. Omitting the `nutrients` field entirely from the request body leaves the ingredient's existing nutrients unchanged. */
        NutrientAmountsInput: {
            /** Format: double */
            calories?: number | null;
            /** Format: double */
            protein?: number | null;
            /** Format: double */
            carbohydrates?: number | null;
            /** Format: double */
            sugar?: number | null;
            /** Format: double */
            fibre?: number | null;
            /** Format: double */
            fat?: number | null;
            /** Format: double */
            saturated_fat?: number | null;
            /** Format: double */
            sodium?: number | null;
            /** Format: double */
            potassium?: number | null;
            /** Format: double */
            calcium?: number | null;
            /** Format: double */
            iron?: number | null;
            /** Format: double */
            magnesium?: number | null;
            /** Format: double */
            zinc?: number | null;
            /** Format: double */
            vitamin_a?: number | null;
            /** Format: double */
            vitamin_c?: number | null;
            /** Format: double */
            vitamin_d?: number | null;
            /** Format: double */
            vitamin_b12?: number | null;
            /** Format: double */
            folate?: number | null;
        };
        Ingredient: {
            /** Format: uuid */
            id: string;
            name: string;
            category: components["schemas"]["IngredientCategory"];
            /** @description True for a custom ingredient owned by the caller; false for the global USDA catalog. */
            is_custom: boolean;
            /** Format: double */
            grams_per_piece: number | null;
            /** Format: double */
            density_g_per_ml: number | null;
            nutrients: components["schemas"]["NutrientAmounts"];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        CreateIngredientRequest: {
            name: string;
            category: components["schemas"]["IngredientCategory"];
            /** Format: double */
            grams_per_piece?: number | null;
            /** Format: double */
            density_g_per_ml?: number | null;
            nutrients?: components["schemas"]["NutrientAmountsInput"];
        };
        UpdateIngredientRequest: {
            name?: string;
            category?: components["schemas"]["IngredientCategory"];
            /** Format: double */
            grams_per_piece?: number | null;
            /** Format: double */
            density_g_per_ml?: number | null;
            nutrients?: components["schemas"]["NutrientAmountsInput"];
        };
        IngredientList: {
            items: components["schemas"]["Ingredient"][];
            next_cursor: string | null;
        };
        /** @enum {string} */
        Unit: "g" | "ml" | "piece";
        /** @enum {string} */
        Slot: "breakfast" | "lunch" | "dinner" | "snack";
        MealIngredient: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            ingredient_id: string;
            ingredient_name: string;
            ingredient_category: components["schemas"]["IngredientCategory"];
            /** Format: double */
            quantity: number;
            unit: components["schemas"]["Unit"];
            position: number;
        };
        Meal: {
            /** Format: uuid */
            id: string;
            name: string;
            notes: string | null;
            /** Format: double */
            servings: number;
            shared_with_partner: boolean;
            /** @description False when the meal belongs to the caller's partner, who shared it. It is then read-only for the caller (writes are `404`); copy it to change it. */
            is_owner: boolean;
            ingredients: components["schemas"]["MealIngredient"][];
            nutrition_per_serving: components["schemas"]["NutrientAmounts"];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        MealSummary: {
            /** Format: uuid */
            id: string;
            name: string;
            notes: string | null;
            /** Format: double */
            servings: number;
            shared_with_partner: boolean;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        CreateMealRequest: {
            name: string;
            notes?: string | null;
            /** Format: double */
            servings: number;
            shared_with_partner?: boolean;
        };
        UpdateMealRequest: {
            name?: string;
            notes?: string | null;
            /** Format: double */
            servings?: number;
            shared_with_partner?: boolean;
        };
        MealIngredientInput: {
            /** Format: uuid */
            ingredient_id: string;
            /** Format: double */
            quantity: number;
            unit: components["schemas"]["Unit"];
        };
        ReplaceMealIngredientsRequest: {
            items: components["schemas"]["MealIngredientInput"][];
        };
        MealList: {
            items: components["schemas"]["MealSummary"][];
            next_cursor: string | null;
        };
        TemplateSlot: {
            /** Format: uuid */
            id: string;
            day_index: number;
            slot: components["schemas"]["Slot"];
            /** Format: uuid */
            meal_id: string;
            meal_name: string;
            /** Format: double */
            portion: number;
        };
        DietTemplate: {
            /** Format: uuid */
            id: string;
            name: string;
            day_count: number;
            shared_with_partner: boolean;
            /** @description False when the diet template belongs to the caller's partner, who shared it. It is then read-only for the caller (writes are `404`); copy it to change it, or to apply it. */
            is_owner: boolean;
            slots: components["schemas"]["TemplateSlot"][];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        DietTemplateSummary: {
            /** Format: uuid */
            id: string;
            name: string;
            day_count: number;
            shared_with_partner: boolean;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        CreateDietTemplateRequest: {
            name: string;
            day_count: number;
            shared_with_partner?: boolean;
        };
        UpdateDietTemplateRequest: {
            name?: string;
            shared_with_partner?: boolean;
        };
        TemplateSlotInput: {
            day_index: number;
            slot: components["schemas"]["Slot"];
            /** Format: uuid */
            meal_id: string;
            /**
             * Format: double
             * @default 1
             */
            portion: number;
        };
        ReplaceTemplateSlotsRequest: {
            items: components["schemas"]["TemplateSlotInput"][];
        };
        ApplyDietTemplateRequest: {
            /** Format: date */
            start_date: string;
            /** @default false */
            overwrite: boolean;
        };
        DietTemplateList: {
            items: components["schemas"]["DietTemplateSummary"][];
            next_cursor: string | null;
        };
        PlanEntry: {
            /** Format: uuid */
            id: string;
            /** Format: date */
            date: string;
            slot: components["schemas"]["Slot"];
            /** Format: uuid */
            meal_id: string;
            meal_name: string;
            /** Format: double */
            portion: number;
            /** Format: uuid */
            from_template_id: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        DailyTotal: {
            /** Format: date */
            date: string;
            entries: components["schemas"]["PlanEntry"][];
            nutrition_per_day: components["schemas"]["NutrientAmounts"];
        };
        Targets: {
            /** Format: double */
            target_kcal: number | null;
            /** Format: double */
            target_protein_g: number | null;
            /** Format: double */
            target_carbs_g: number | null;
            /** Format: double */
            target_fat_g: number | null;
        };
        PlanRange: {
            /** Format: date */
            from: string;
            /** Format: date */
            to: string;
            days: components["schemas"]["DailyTotal"][];
            targets: components["schemas"]["Targets"];
        };
        SetPlanEntryRequest: {
            /** Format: uuid */
            meal_id: string;
            /**
             * Format: double
             * @default 1
             */
            portion: number;
        };
        /** @enum {string} */
        ShoppingItemOrigin: "generated" | "manual";
        ShoppingItem: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            list_id: string;
            /**
             * Format: uuid
             * @description The ingredient this item came from. Null for a free-text item, and for any item whose ingredient has since been deleted; the item keeps its own name, quantity, unit and category either way.
             */
            ingredient_id: string | null;
            name: string;
            /** Format: double */
            quantity: number | null;
            /** @enum {string|null} */
            unit: "g" | "ml" | "piece" | null;
            category: components["schemas"]["IngredientCategory"];
            checked: boolean;
            /** Format: uuid */
            checked_by: string | null;
            position: number;
            version: number;
            origin: components["schemas"]["ShoppingItemOrigin"];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        ShoppingList: {
            /** Format: uuid */
            id: string;
            name: string;
            shared_with_partner: boolean;
            /** @description False when the list belongs to the caller's partner, who shared it. It is then read-only for the caller (writes are `404`); the caller may still add, edit, check and delete its items. */
            is_owner: boolean;
            /** Format: date */
            source_from: string | null;
            /** Format: date */
            source_to: string | null;
            items: components["schemas"]["ShoppingItem"][];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        ShoppingListSummary: {
            /** Format: uuid */
            id: string;
            name: string;
            shared_with_partner: boolean;
            /** Format: date */
            source_from: string | null;
            /** Format: date */
            source_to: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        ShoppingListPage: {
            items: components["schemas"]["ShoppingListSummary"][];
            next_cursor: string | null;
        };
        CreateShoppingListRequest: {
            name: string;
            shared_with_partner?: boolean;
        };
        UpdateShoppingListRequest: {
            name?: string;
            shared_with_partner?: boolean;
        };
        GenerateShoppingListRequest: {
            /** Format: date */
            from: string;
            /** Format: date */
            to: string;
            /** @description Name for a new list. Ignored when `list_id` is set. Defaults to "Shopping {from} to {to}". */
            name?: string;
            /**
             * Format: uuid
             * @description Regenerate this existing list instead of creating a new one.
             */
            list_id?: string;
        };
        CreateShoppingItemRequest: {
            /** Format: uuid */
            ingredient_id?: string;
            name: string;
            /** Format: double */
            quantity?: number;
            unit?: components["schemas"]["Unit"];
            category?: components["schemas"]["IngredientCategory"];
        };
        UpdateShoppingItemRequest: {
            version?: number;
            name?: string;
            /** Format: double */
            quantity?: number | null;
            /** @enum {string|null} */
            unit?: "g" | "ml" | "piece" | null;
            category?: components["schemas"]["IngredientCategory"];
            checked?: boolean;
        };
        /** @description A `version_conflict` problem (RFC 9457) with the item's current state as the `current` extension member. */
        ShoppingItemConflict: {
            /** Format: uri-reference */
            type: string;
            title: string;
            status: number;
            detail?: string;
            code: string;
            current: components["schemas"]["ShoppingItem"];
        };
        /** @description The caller's partnership. While `status` is `active`, `display_name` is the partner's name and `linked_at` says since when; while it is `pending`, `expires_at` is when the invite code stops working. */
        Partnership: {
            /** @enum {string} */
            status: "pending" | "active";
            display_name: string | null;
            /** Format: date-time */
            linked_at: string | null;
            /** Format: date-time */
            expires_at: string | null;
        };
        PartnerInvite: {
            /** @description Shown once; only its hash is stored. */
            code: string;
            /** Format: date-time */
            expires_at: string;
        };
        AcceptPartnerInviteRequest: {
            code: string;
        };
    };
    responses: {
        /** @description An error occurred. */
        Problem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description The request is malformed or fails validation. Field details are in `errors`. */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Missing, invalid or expired credentials. */
        Unauthorized: {
            headers: {
                "WWW-Authenticate"?: string;
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description The resource does not exist, or exists but is not visible to the caller. */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description The request conflicts with existing state. */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Rate limit exceeded. */
        TooManyRequests: {
            headers: {
                "Retry-After"?: number;
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listIngredients: {
        parameters: {
            query?: {
                q?: string;
                category?: components["schemas"]["IngredientCategory"];
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Matching ingredients. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngredientList"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["Problem"];
        };
    };
    createIngredient: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateIngredientRequest"];
            };
        };
        responses: {
            /** @description The ingredient was created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ingredient"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["Problem"];
        };
    };
    deleteIngredient: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The ingredient was deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["Problem"];
        };
    };
    updateIngredient: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateIngredientRequest"];
            };
        };
        responses: {
            /** @description The updated ingredient. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ingredient"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["Problem"];
        };
    };
    listDietTemplates: {
        parameters: {
            query?: {
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The caller's diet templates. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DietTemplateList"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["Problem"];
        };
    };
    createDietTemplate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateDietTemplateRequest"];
            };
        };
        responses: {
            /** @description The template was created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DietTemplate"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["Problem"];
        };
    };
    getDietTemplate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The template. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DietTemplate"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["Problem"];
        };
    };
    deleteDietTemplate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The template was deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["Problem"];
        };
    };
    updateDietTemplate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateDietTemplateRequest"];
            };
        };
        responses: {
            /** @description The updated template. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DietTemplate"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["Problem"];
        };
    };
    replaceTemplateSlots: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReplaceTemplateSlotsRequest"];
            };
        };
        responses: {
            /** @description The updated template. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DietTemplate"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["Problem"];
        };
    };
    applyDietTemplate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApplyDietTemplateRequest"];
            };
        };
        responses: {
            /** @description The template was applied. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["Problem"];
        };
    };
    copyDietTemplate: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The copy. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DietTemplate"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["Problem"];
        };
    };
    listMeals: {
        parameters: {
            query?: {
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The caller's meals. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MealList"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["Problem"];
        };
    };
    createMeal: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateMealRequest"];
            };
        };
        responses: {
            /** @description The meal was created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Meal"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["Problem"];
        };
    };
    getMeal: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The meal. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Meal"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["Problem"];
        };
    };
    deleteMeal: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The meal was deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["Problem"];
        };
    };
    updateMeal: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateMealRequest"];
            };
        };
        responses: {
            /** @description The updated meal. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Meal"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["Problem"];
        };
    };
    replaceMealIngredients: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReplaceMealIngredientsRequest"];
            };
        };
        responses: {
            /** @description The updated meal. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Meal"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["Problem"];
        };
    };
    copyMeal: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The copy. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Meal"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["Problem"];
        };
    };
    getPlan: {
        parameters: {
            query: {
                from: string;
                to: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The plan for the range. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanRange"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            409: components["responses"]["Conflict"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["Problem"];
        };
    };
    setPlanEntry: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                date: string;
                slot: components["schemas"]["Slot"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetPlanEntryRequest"];
            };
        };
        responses: {
            /** @description The entry. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlanEntry"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["Problem"];
        };
    };
    deletePlanEntry: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                date: string;
                slot: components["schemas"]["Slot"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The entry (or entries) was removed. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["Problem"];
        };
    };
    listShoppingLists: {
        parameters: {
            query?: {
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The caller's shopping lists. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShoppingListPage"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["Problem"];
        };
    };
    createShoppingList: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateShoppingListRequest"];
            };
        };
        responses: {
            /** @description The list was created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShoppingList"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["Problem"];
        };
    };
    generateShoppingList: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateShoppingListRequest"];
            };
        };
        responses: {
            /** @description The existing list was regenerated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShoppingList"];
                };
            };
            /** @description A new list was generated. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShoppingList"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["Problem"];
        };
    };
    getShoppingList: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The list. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShoppingList"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["Problem"];
        };
    };
    deleteShoppingList: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The list was deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["Problem"];
        };
    };
    updateShoppingList: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateShoppingListRequest"];
            };
        };
        responses: {
            /** @description The updated list. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShoppingList"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["Problem"];
        };
    };
    createShoppingItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateShoppingItemRequest"];
            };
        };
        responses: {
            /** @description The item was added. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShoppingItem"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["Problem"];
        };
    };
    deleteShoppingItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                item_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The item was removed. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["Problem"];
        };
    };
    updateShoppingItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
                item_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateShoppingItemRequest"];
            };
        };
        responses: {
            /** @description The item, with its new version. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShoppingItem"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            /** @description The request's `version` is stale. `current` is the item as it is now. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ShoppingItemConflict"];
                };
            };
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["Problem"];
        };
    };
    streamShoppingListEvents: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The event stream. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["Problem"];
            503: components["responses"]["Problem"];
        };
    };
    getPartner: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The partnership. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Partnership"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["Problem"];
        };
    };
    unlinkPartner: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The link was ended, or the pending invite cancelled. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["Problem"];
        };
    };
    createPartnerInvite: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The invite. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PartnerInvite"];
                };
            };
            401: components["responses"]["Unauthorized"];
            409: components["responses"]["Conflict"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["Problem"];
        };
    };
    acceptPartnerInvite: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AcceptPartnerInviteRequest"];
            };
        };
        responses: {
            /** @description The new partnership. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Partnership"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["Problem"];
        };
    };
    listPartnerMeals: {
        parameters: {
            query?: {
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The partner's shared meals. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MealList"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["Problem"];
        };
    };
    listPartnerDietTemplates: {
        parameters: {
            query?: {
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The partner's shared diet templates. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DietTemplateList"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["Problem"];
        };
    };
    listPartnerShoppingLists: {
        parameters: {
            query?: {
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The partner's shared shopping lists. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShoppingListPage"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["Problem"];
        };
    };
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The service is alive. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
            500: components["responses"]["Problem"];
        };
    };
    getReady: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The service is ready to take traffic. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
            503: components["responses"]["Problem"];
        };
    };
    registerUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterRequest"];
            };
        };
        responses: {
            /** @description The account was created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            409: components["responses"]["Conflict"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["Problem"];
        };
    };
    loginUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description The user is signed in. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["Problem"];
        };
    };
    refreshSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description A new token pair. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["Problem"];
        };
    };
    logoutUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description The session is revoked. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["Problem"];
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The profile. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["Problem"];
        };
    };
    deleteMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The account was deleted. */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["Problem"];
        };
    };
    updateMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProfileRequest"];
            };
        };
        responses: {
            /** @description The updated profile. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["TooManyRequests"];
            500: components["responses"]["Problem"];
        };
    };
}
