// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/nullable"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for AuthResponseTokenType.
const (
	AuthResponseTokenTypeBearer AuthResponseTokenType = "Bearer"
)

// Valid indicates whether the value is a known member of the AuthResponseTokenType enum.
func (e AuthResponseTokenType) Valid() bool {
	switch e {
	case AuthResponseTokenTypeBearer:
		return true
	default:
		return false
	}
}

// Defines values for HealthStatus.
const (
	HealthStatusOk HealthStatus = "ok"
)

// Valid indicates whether the value is a known member of the HealthStatus enum.
func (e HealthStatus) Valid() bool {
	switch e {
	case HealthStatusOk:
		return true
	default:
		return false
	}
}

// Defines values for IngredientCategory.
const (
	IngredientCategoryBeverages        IngredientCategory = "beverages"
	IngredientCategoryCondimentsOils   IngredientCategory = "condiments_oils"
	IngredientCategoryDairyEggs        IngredientCategory = "dairy_eggs"
	IngredientCategoryGrainsBread      IngredientCategory = "grains_bread"
	IngredientCategoryLegumesNutsSeeds IngredientCategory = "legumes_nuts_seeds"
	IngredientCategoryMeatSeafood      IngredientCategory = "meat_seafood"
	IngredientCategoryOther            IngredientCategory = "other"
	IngredientCategoryProduce          IngredientCategory = "produce"
	IngredientCategorySpicesHerbs      IngredientCategory = "spices_herbs"
	IngredientCategorySweetsSnacks     IngredientCategory = "sweets_snacks"
)

// Valid indicates whether the value is a known member of the IngredientCategory enum.
func (e IngredientCategory) Valid() bool {
	switch e {
	case IngredientCategoryBeverages:
		return true
	case IngredientCategoryCondimentsOils:
		return true
	case IngredientCategoryDairyEggs:
		return true
	case IngredientCategoryGrainsBread:
		return true
	case IngredientCategoryLegumesNutsSeeds:
		return true
	case IngredientCategoryMeatSeafood:
		return true
	case IngredientCategoryOther:
		return true
	case IngredientCategoryProduce:
		return true
	case IngredientCategorySpicesHerbs:
		return true
	case IngredientCategorySweetsSnacks:
		return true
	default:
		return false
	}
}

// AuthResponse defines model for AuthResponse.
type AuthResponse struct {
	AccessToken string `json:"access_token"`

	// ExpiresIn Access token lifetime in seconds.
	ExpiresIn    int                   `json:"expires_in"`
	RefreshToken string                `json:"refresh_token"`
	TokenType    AuthResponseTokenType `json:"token_type"`
	User         User                  `json:"user"`
}

// AuthResponseTokenType defines model for AuthResponse.TokenType.
type AuthResponseTokenType string

// CreateIngredientRequest defines model for CreateIngredientRequest.
type CreateIngredientRequest struct {
	Category      IngredientCategory         `json:"category"`
	DensityGPerMl nullable.Nullable[float64] `json:"density_g_per_ml,omitempty"`
	GramsPerPiece nullable.Nullable[float64] `json:"grams_per_piece,omitempty"`
	Name          string                     `json:"name"`

	// Nutrients Amount per 100 g for each tracked nutrient. A null value means the amount is unknown.
	Nutrients *NutrientAmounts `json:"nutrients,omitempty"`
}

// FieldError defines model for FieldError.
type FieldError struct {
	// Code Stable identifier, e.g. required, too_short, too_long, invalid_format, invalid_type, invalid_value.
	Code string `json:"code"`

	// Field Path of the offending JSON field, e.g. `email`.
	Field string `json:"field"`
}

// Health defines model for Health.
type Health struct {
	Status HealthStatus `json:"status"`
}

// HealthStatus defines model for Health.Status.
type HealthStatus string

// Ingredient defines model for Ingredient.
type Ingredient struct {
	Category      IngredientCategory         `json:"category"`
	CreatedAt     time.Time                  `json:"created_at"`
	DensityGPerMl nullable.Nullable[float64] `json:"density_g_per_ml"`
	GramsPerPiece nullable.Nullable[float64] `json:"grams_per_piece"`
	Id            openapi_types.UUID         `json:"id"`

	// IsCustom True for a custom ingredient owned by the caller; false for the global USDA catalog.
	IsCustom bool   `json:"is_custom"`
	Name     string `json:"name"`

	// Nutrients Amount per 100 g for each tracked nutrient. A null value means the amount is unknown.
	Nutrients NutrientAmounts `json:"nutrients"`
	UpdatedAt time.Time       `json:"updated_at"`
}

// IngredientCategory defines model for IngredientCategory.
type IngredientCategory string

// IngredientList defines model for IngredientList.
type IngredientList struct {
	Items      []Ingredient              `json:"items"`
	NextCursor nullable.Nullable[string] `json:"next_cursor"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
}

// NutrientAmounts Amount per 100 g for each tracked nutrient. A null value means the amount is unknown.
type NutrientAmounts struct {
	Calcium       nullable.Nullable[float64] `json:"calcium"`
	Calories      nullable.Nullable[float64] `json:"calories"`
	Carbohydrates nullable.Nullable[float64] `json:"carbohydrates"`
	Fat           nullable.Nullable[float64] `json:"fat"`
	Fibre         nullable.Nullable[float64] `json:"fibre"`
	Folate        nullable.Nullable[float64] `json:"folate"`
	Iron          nullable.Nullable[float64] `json:"iron"`
	Magnesium     nullable.Nullable[float64] `json:"magnesium"`
	Potassium     nullable.Nullable[float64] `json:"potassium"`
	Protein       nullable.Nullable[float64] `json:"protein"`
	SaturatedFat  nullable.Nullable[float64] `json:"saturated_fat"`
	Sodium        nullable.Nullable[float64] `json:"sodium"`
	Sugar         nullable.Nullable[float64] `json:"sugar"`
	VitaminA      nullable.Nullable[float64] `json:"vitamin_a"`
	VitaminB12    nullable.Nullable[float64] `json:"vitamin_b12"`
	VitaminC      nullable.Nullable[float64] `json:"vitamin_c"`
	VitaminD      nullable.Nullable[float64] `json:"vitamin_d"`
	Zinc          nullable.Nullable[float64] `json:"zinc"`
}

// Problem RFC 9457 problem details with a stable machine-readable code.
type Problem struct {
	// Code Stable identifier clients map to localized text, e.g. partner_not_linked.
	Code   string  `json:"code"`
	Detail *string `json:"detail,omitempty"`

	// Errors Per-field details, present on validation_failed problems.
	Errors *[]FieldError `json:"errors,omitempty"`
	Status int           `json:"status"`
	Title  string        `json:"title"`
	Type   string        `json:"type"`
}

// RefreshRequest defines model for RefreshRequest.
type RefreshRequest struct {
	RefreshToken string `json:"refresh_token"`
}

// RegisterRequest defines model for RegisterRequest.
type RegisterRequest struct {
	DisplayName string              `json:"display_name"`
	Email       openapi_types.Email `json:"email"`
	Password    string              `json:"password"`
}

// UpdateIngredientRequest defines model for UpdateIngredientRequest.
type UpdateIngredientRequest struct {
	Category      *IngredientCategory        `json:"category,omitempty"`
	DensityGPerMl nullable.Nullable[float64] `json:"density_g_per_ml,omitempty"`
	GramsPerPiece nullable.Nullable[float64] `json:"grams_per_piece,omitempty"`
	Name          *string                    `json:"name,omitempty"`

	// Nutrients Amount per 100 g for each tracked nutrient. A null value means the amount is unknown.
	Nutrients *NutrientAmounts `json:"nutrients,omitempty"`
}

// UpdateProfileRequest defines model for UpdateProfileRequest.
type UpdateProfileRequest struct {
	DisplayName    *string                    `json:"display_name,omitempty"`
	TargetCarbsG   nullable.Nullable[float64] `json:"target_carbs_g,omitempty"`
	TargetFatG     nullable.Nullable[float64] `json:"target_fat_g,omitempty"`
	TargetKcal     nullable.Nullable[float64] `json:"target_kcal,omitempty"`
	TargetProteinG nullable.Nullable[float64] `json:"target_protein_g,omitempty"`
}

// User defines model for User.
type User struct {
	CreatedAt      time.Time                  `json:"created_at"`
	DisplayName    string                     `json:"display_name"`
	Email          string                     `json:"email"`
	Id             openapi_types.UUID         `json:"id"`
	TargetCarbsG   nullable.Nullable[float64] `json:"target_carbs_g,omitempty"`
	TargetFatG     nullable.Nullable[float64] `json:"target_fat_g,omitempty"`
	TargetKcal     nullable.Nullable[float64] `json:"target_kcal,omitempty"`
	TargetProteinG nullable.Nullable[float64] `json:"target_protein_g,omitempty"`
	UpdatedAt      time.Time                  `json:"updated_at"`
}

// BadRequest RFC 9457 problem details with a stable machine-readable code.
type BadRequest = Problem

// Conflict RFC 9457 problem details with a stable machine-readable code.
type Conflict = Problem

// NotFound RFC 9457 problem details with a stable machine-readable code.
type NotFound = Problem

// TooManyRequests RFC 9457 problem details with a stable machine-readable code.
type TooManyRequests = Problem

// Unauthorized RFC 9457 problem details with a stable machine-readable code.
type Unauthorized = Problem

// ListIngredientsParams defines parameters for ListIngredients.
type ListIngredientsParams struct {
	Q        *string             `form:"q,omitempty" json:"q,omitempty"`
	Category *IngredientCategory `form:"category,omitempty" json:"category,omitempty"`
	Cursor   *string             `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit    *int                `form:"limit,omitempty" json:"limit,omitempty"`
}

// LoginUserJSONRequestBody defines body for LoginUser for application/json ContentType.
type LoginUserJSONRequestBody = LoginRequest

// LogoutUserJSONRequestBody defines body for LogoutUser for application/json ContentType.
type LogoutUserJSONRequestBody = RefreshRequest

// RefreshSessionJSONRequestBody defines body for RefreshSession for application/json ContentType.
type RefreshSessionJSONRequestBody = RefreshRequest

// RegisterUserJSONRequestBody defines body for RegisterUser for application/json ContentType.
type RegisterUserJSONRequestBody = RegisterRequest

// CreateIngredientJSONRequestBody defines body for CreateIngredient for application/json ContentType.
type CreateIngredientJSONRequestBody = CreateIngredientRequest

// UpdateIngredientJSONRequestBody defines body for UpdateIngredient for application/json ContentType.
type UpdateIngredientJSONRequestBody = UpdateIngredientRequest

// UpdateMeJSONRequestBody defines body for UpdateMe for application/json ContentType.
type UpdateMeJSONRequestBody = UpdateProfileRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// LoginUser Sign in with email and password
	// (POST /auth/login)
	LoginUser(w http.ResponseWriter, r *http.Request)
	// LogoutUser Revoke a refresh-token session
	// (POST /auth/logout)
	LogoutUser(w http.ResponseWriter, r *http.Request)
	// RefreshSession Exchange a refresh token for a new token pair
	// (POST /auth/refresh)
	RefreshSession(w http.ResponseWriter, r *http.Request)
	// RegisterUser Create an account
	// (POST /auth/register)
	RegisterUser(w http.ResponseWriter, r *http.Request)
	// GetHealth Liveness probe
	// (GET /healthz)
	GetHealth(w http.ResponseWriter, r *http.Request)
	// ListIngredients List or search ingredients
	// (GET /ingredients)
	ListIngredients(w http.ResponseWriter, r *http.Request, params ListIngredientsParams)
	// CreateIngredient Create a custom ingredient
	// (POST /ingredients)
	CreateIngredient(w http.ResponseWriter, r *http.Request)
	// DeleteIngredient Delete a custom ingredient
	// (DELETE /ingredients/{id})
	DeleteIngredient(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// UpdateIngredient Update a custom ingredient
	// (PATCH /ingredients/{id})
	UpdateIngredient(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// DeleteMe Delete the signed-in user's account
	// (DELETE /me)
	DeleteMe(w http.ResponseWriter, r *http.Request)
	// GetMe Get the signed-in user's profile
	// (GET /me)
	GetMe(w http.ResponseWriter, r *http.Request)
	// UpdateMe Update the signed-in user's profile
	// (PATCH /me)
	UpdateMe(w http.ResponseWriter, r *http.Request)
	// GetReady Readiness probe
	// (GET /readyz)
	GetReady(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// LoginUser Sign in with email and password
// (POST /auth/login)
func (_ Unimplemented) LoginUser(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// LogoutUser Revoke a refresh-token session
// (POST /auth/logout)
func (_ Unimplemented) LogoutUser(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// RefreshSession Exchange a refresh token for a new token pair
// (POST /auth/refresh)
func (_ Unimplemented) RefreshSession(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// RegisterUser Create an account
// (POST /auth/register)
func (_ Unimplemented) RegisterUser(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetHealth Liveness probe
// (GET /healthz)
func (_ Unimplemented) GetHealth(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ListIngredients List or search ingredients
// (GET /ingredients)
func (_ Unimplemented) ListIngredients(w http.ResponseWriter, r *http.Request, params ListIngredientsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// CreateIngredient Create a custom ingredient
// (POST /ingredients)
func (_ Unimplemented) CreateIngredient(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// DeleteIngredient Delete a custom ingredient
// (DELETE /ingredients/{id})
func (_ Unimplemented) DeleteIngredient(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// UpdateIngredient Update a custom ingredient
// (PATCH /ingredients/{id})
func (_ Unimplemented) UpdateIngredient(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// DeleteMe Delete the signed-in user's account
// (DELETE /me)
func (_ Unimplemented) DeleteMe(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetMe Get the signed-in user's profile
// (GET /me)
func (_ Unimplemented) GetMe(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// UpdateMe Update the signed-in user's profile
// (PATCH /me)
func (_ Unimplemented) UpdateMe(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetReady Readiness probe
// (GET /readyz)
func (_ Unimplemented) GetReady(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// LoginUser operation middleware
func (siw *ServerInterfaceWrapper) LoginUser(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.LoginUser(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// LogoutUser operation middleware
func (siw *ServerInterfaceWrapper) LogoutUser(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.LogoutUser(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RefreshSession operation middleware
func (siw *ServerInterfaceWrapper) RefreshSession(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RefreshSession(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RegisterUser operation middleware
func (siw *ServerInterfaceWrapper) RegisterUser(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RegisterUser(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListIngredients operation middleware
func (siw *ServerInterfaceWrapper) ListIngredients(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListIngredientsParams

	// ------------- Optional query parameter "q" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "q", r.URL.Query(), &params.Q, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "q"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "q", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "category" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "category", r.URL.Query(), &params.Category, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "category"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "category", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", r.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "cursor"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListIngredients(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateIngredient operation middleware
func (siw *ServerInterfaceWrapper) CreateIngredient(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateIngredient(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteIngredient operation middleware
func (siw *ServerInterfaceWrapper) DeleteIngredient(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteIngredient(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateIngredient operation middleware
func (siw *ServerInterfaceWrapper) UpdateIngredient(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateIngredient(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteMe operation middleware
func (siw *ServerInterfaceWrapper) DeleteMe(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteMe(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMe operation middleware
func (siw *ServerInterfaceWrapper) GetMe(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMe(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateMe operation middleware
func (siw *ServerInterfaceWrapper) UpdateMe(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateMe(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetReady operation middleware
func (siw *ServerInterfaceWrapper) GetReady(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetReady(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/ingredients", wrapper.ListIngredients)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/ingredients", wrapper.CreateIngredient)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/ingredients/{id}", wrapper.DeleteIngredient)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/ingredients/{id}", wrapper.UpdateIngredient)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/healthz", wrapper.GetHealth)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/readyz", wrapper.GetReady)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/register", wrapper.RegisterUser)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/login", wrapper.LoginUser)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/refresh", wrapper.RefreshSession)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/logout", wrapper.LogoutUser)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/me", wrapper.DeleteMe)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/me", wrapper.GetMe)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/me", wrapper.UpdateMe)
	})

	return r
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7Ftfc9vGrv8qGN47cx8uLctOMjdVn9y06U0naT12MnnIeBSIBMmtl7vM7tK2kvF3P7N/KJEUZcv0n7Q9",
	"580UuQAW+AELYOFvUSLLSgoSRkezb5EiXUmhyT38hOkJfalJG/uUSGFIuD+xqjhL0DAp9islF5zK//1T",
	"S2Hf6aSgEu1f/60oi2bRf+2vWez7t3r/2K+Krq+v4yglnShWWXLRLHpfECjPFpiGEnkmVUkpSAUZMq7h",
	"AjlLHfcJvGbEU0jJuDeoCJiAz6SUVPrzJLqOo1dSZJwl320PSeCv4ZKZAuiKacNEDtqgISfh79K8lrVI",
	"n15CLWuVEKSSNAhpvHCx1bT7S8Oidkaw7y6YZgtOYCSYgiBBzkk5+Rs2Tyj+kQBnY5BJUitFqRPkvZTv",
	"UCwDaPVTCnSChoCzklklJkSpFSmOCsKUlJPkhIxa7h1lhlSXo1lWFM0iJgzlpCzx6zj6ILA2hVTsKz0p",
	"Lt4xrZnIY2DCuZnHQsUUpZAoSkkYhlz39vbx48e9o9oU9m2ChgY3qI1iInf7u47Da7farjwJgcc+V0pW",
	"pAzzUQiThLSeG3lOYoBaHHnx9Jy51z2cuMXgFgNnGRlWuhChKZEidfvo6z+OFGWKdHEDT/dm7n/+FpGo",
	"y2j2KfqJUJGKzuLNBbX2Zr/JLB+0M7/l/6W2Grc0O9vvi9YRpKOJwHEtilz8SYlxAVERGnojckUpI2Fa",
	"MR7TlFnNIT9u2SBDrinumcWaOZdqedum1nxeNSsc6IRmZjnP5xWpecmdFq8SXmt2Qe+YYKXVqFE1xZEN",
	"/2iiWZTKesHtPku88h88i6Oy+XgaR6LmHO0nYWXYuqjLhTdsrrDUjmXFKKGRXA+m0+n0jpwFlo5diVdv",
	"SeSmiGaHgUjzfDAAG1EbxZrD+SY1/x4+PCplbT/vw8jxj9dWGwKGO0t/sWF10wsTmdKme50au2lgLixk",
	"jFQMNMkn0HCOwUg514VUxv/JZSu2zL2O189WovXTBfKaWg661kpmBd2U5hhNATJzx5PMMhKpPWd/O/3j",
	"d3ArgnCfqUTGPw9Q7unMs4n93ocU9v+E3Fquryx7tNe6HRnk+UBU6LELq4YYrZ1owDL3csTEBYN0jo7y",
	"GvRoaM/GyiH1DznvpruMccYRVFjaWVjXLB2Smel5Umsjy03YvFc1QSYVIPhPgK1UBfJSUAqLZSvn+RFc",
	"QHRL7K85lwvk8OH05yNI0CCXeQtbCyk5oWjHgAf08jiqq/SOBuzBzumrHx7aCtu01AAE2pvooKoj4c3Y",
	"ftVCcuM4lZJp7VkiU8s55bllUBKauSbMpEy9gEzo+UIR2kdOeV2Snova6LkmSp1MUqSstALOJeP2F12x",
	"hPS8ILWwjwu6IIU5uVeXRHatwOTcPktTbDnY1+K/ZXrAPZmhsvvHbk7qsgzPDJVC56yCrsw8qZX2EXqL",
	"b2yzs+PfJTJkj7cyZ2JcTuACaweG/pe4c+y9eD6gxgq1vpQq7Z2RB4cvbzkje7tsGK7oDW2x70abaaN7",
	"ARUpOJhOIXe+TpgUYBQm55RCg/YJHIG1A7jTCkpCoV1UQE+CaajFuZCXwsaEfuTmCavLkYEvQS5VoDRq",
	"uVrIYpkqNKNpZP2gs/tKtlBjI34meSgxxhwXyhdKI5aWmAvS4w1WSYP6PuuVNMTGSq/R1MrF4fFW0zId",
	"L76uc1Qj114wgyUTc7zn+sXB4T0pJPdcn45c/5WJcax78XEVNdZ46seCxlSNl3o/7yNohYY2sONVTAue",
	"1vaasIm2Ndt6beuoa7GVyw/F8lbzqdeRef0Kfnj+4v8g9EhWTULXhkPQvnYpMSmYoD2bOrgfbLY/EKt3",
	"q38g4S4HghIrMBK4TJCzr5SCoSsTCpAKlRGk5kKaOWfi3LeKBtJsE47TzZaH628OVECk9rJ2RzSGSpF2",
	"iaxo9U3nGTJOaaMa1wbZKT9plYgD+cm67tnsqRhm+HD223RR1jm8YnuKMlIkktvz19D78PRXMtxQtZ34",
	"Fsq4FGejNdRKVl4cHN4tWekSG5Y1Z9qQGidsynTFcTkfaD68vL338ATZ3PTO6Vzc3dSQzj64euM//a1/",
	"fH9ri+WPlcwYp+/hMgZVTmZuz1M9z4fP65WaX9xdy4F+huZW6oejqZ8nOBavh9PRXEM28vD7GgRK6Mb3",
	"XH5ML6yHl+1RdLMltVvnahdMPQBw7oqO8RRusfStZB6m49WcLB0D3qVzZfMdSmrFzPLUBimPoYW7Ajqq",
	"fVvYP71uRPzt4/so3Hy51qC/LlpRLoyp/J0cE5nczO5eSWEUJmbVeXxHyOGYoxCk4Oj4zQTeF0yDjX7A",
	"fBtCM5FzgnDRKzMwqjbFj+7dApNzEmkMl7QAFCmwP05XCSwqgpwEuYwfMiVLYGaySrRmUZ+5TdpJaS/q",
	"dHIwmVpjyYoEViyaRc8m08kzd5SbwqlqH2tT7HOZ+5q2kj5YW490SeqbNJr5bpRzV29D0uYnmS5vuBK9",
	"21Vop9t13UWKxZ/7oTUTcTidPhjvzr3nljv6WpOyttQsF5QCE+6i+7mXYoj4Str91viGW3Jw+5LOrbNd",
	"dPjD7Yv6t+7XcfRiF/nWt9BrT4pmn85s/VmWaFOv6JTlApgIoxPWZR1QW+mgwVxbp3Yud2ZprXAla9MG",
	"Vle5b1IqK2l8C080TTqQCpDbWnC5p+hCntvKzV0ehykIDIMH1hM2kCpr84hQ7dUtO4H1+cB1h40KpK2j",
	"2k2FXY6G1fdGyImTHxBCMbXnzRV2eANAwvfbEXIiDRryYTR87LEwgWNfVDORW0A0gKk1pd0vg3Y9jctC",
	"8rXqMywZX27CKFj5dCX/XwVKTxf3jkDQZVBghUz9e4W8X66SAkXegnRQhb+i7KrmRnz71sF2gPtBEO0g",
	"nCTuumJLnHUP9gjySPaHkhgCr+f5qFGw2xHZCbsHT3pmr5SJGkI+OR7CO6BxNeH4V4CvB1ULU8MQLdzo",
	"xFfLM6eh4EumVkLD4XQKlwUJh7tKSTfOxTTU1QR+bsYWjayTwn2RosEFatqE5q9kwrjGI0a2wGELLjSp",
	"C5a41Bw5u/DDnw+m+LfsgoTVTqXkglpaD0J5va9HG/RW3X9kppC1gc9fPsfA3RxoaxkgrwpckGEJcr70",
	"IcPfJ0OFORNhMtdS8SQ0oUoK0rBYgi2zXDRRwcCuECFtoERjP4qdRQMh3xnv5VlMmzetXdiKQmFJxs0i",
	"fvoW2XIi+lKTG2PwdXn0pam7sN+SvLVJdR0Pk2zNSuwGjqFO4Vbi/n4+vmGKcstKN4PaWZhShjU30exw",
	"2m3ytdooB5tjkNdnj+govamJoUFUCwebYLWg9w9NBFourI2tQLzDtHfecuc29s/ctfJQ3dwf8nyk03jb",
	"LOkTn8rtsZnh2Nsa6XqQY/nvAajmMN4cbNsKqN4hsf+Npdc+inDyUxddoP3sfu8BbZcatGcRT7+xyBj1",
	"ekY3L1r9q8X3sYdX1p3sMXy8VegSmRDzXUOz623tA+CWFrMN9JWNtpt2cte99oxG4xqCuHB3yfZPTpmB",
	"WvhaJZ3AH4Ivd52ghAQFLAhCf3XzjO9f4T1S9Np2U/jE9fDt0SsoqqXWp41cfwPX8ra8c6grqRvcNuYp",
	"SrT8+TIEqDDcFyo8m8jSBaml8amKQ7vexLP3+3e0c3Bsl5D3j4zfLdD5G4hcULrHhGsb/I8eqAvDja2L",
	"dqEi2SjehpT3cC4Y/vVm0PkqL93fSv+/khlWftjMFuXf/xg4ghQZX4K/6wNt5ZB+QpZpSDih2h7wg40f",
	"K9D3BgOeOMrfBLEmvneh9o9NS0OsvjNAbcB2rfY79o2axotNO5Qb42ZGr3pFMbyYPgM34X/JtrSOTizX",
	"v0TnyO3f/RMunhMYhVnGktBJevZQVyqYsltaSd3l3XvvT2c2pbQyNzlrd0dvZYIcUrogLqvSn9C14uEG",
	"fLa/76YmC6nN7OX05XT/4iCyBIMQG9SavpfvKjWiJwUl5+4oDklyo+F4EzI508bbOwZ3Hx1oDVwotSm6",
	"3W7Sez8Ea3kpGmg74uEQbFFrYD5MMPyTkWvKk9oLHfhVkt36v6NArp3qXJ9d/ysAAP//",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
