// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"encoding/base64"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/nullable"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for AuthResponseTokenType.
const (
	AuthResponseTokenTypeBearer AuthResponseTokenType = "Bearer"
)

// Valid indicates whether the value is a known member of the AuthResponseTokenType enum.
func (e AuthResponseTokenType) Valid() bool {
	switch e {
	case AuthResponseTokenTypeBearer:
		return true
	default:
		return false
	}
}

// Defines values for HealthStatus.
const (
	HealthStatusOk HealthStatus = "ok"
)

// Valid indicates whether the value is a known member of the HealthStatus enum.
func (e HealthStatus) Valid() bool {
	switch e {
	case HealthStatusOk:
		return true
	default:
		return false
	}
}

// Defines values for IngredientCategory.
const (
	IngredientCategoryBeverages        IngredientCategory = "beverages"
	IngredientCategoryCondimentsOils   IngredientCategory = "condiments_oils"
	IngredientCategoryDairyEggs        IngredientCategory = "dairy_eggs"
	IngredientCategoryGrainsBread      IngredientCategory = "grains_bread"
	IngredientCategoryLegumesNutsSeeds IngredientCategory = "legumes_nuts_seeds"
	IngredientCategoryMeatSeafood      IngredientCategory = "meat_seafood"
	IngredientCategoryOther            IngredientCategory = "other"
	IngredientCategoryProduce          IngredientCategory = "produce"
	IngredientCategorySpicesHerbs      IngredientCategory = "spices_herbs"
	IngredientCategorySweetsSnacks     IngredientCategory = "sweets_snacks"
)

// Valid indicates whether the value is a known member of the IngredientCategory enum.
func (e IngredientCategory) Valid() bool {
	switch e {
	case IngredientCategoryBeverages:
		return true
	case IngredientCategoryCondimentsOils:
		return true
	case IngredientCategoryDairyEggs:
		return true
	case IngredientCategoryGrainsBread:
		return true
	case IngredientCategoryLegumesNutsSeeds:
		return true
	case IngredientCategoryMeatSeafood:
		return true
	case IngredientCategoryOther:
		return true
	case IngredientCategoryProduce:
		return true
	case IngredientCategorySpicesHerbs:
		return true
	case IngredientCategorySweetsSnacks:
		return true
	default:
		return false
	}
}

// Defines values for Unit.
const (
	UnitG     Unit = "g"
	UnitMl    Unit = "ml"
	UnitPiece Unit = "piece"
)

// Valid indicates whether the value is a known member of the Unit enum.
func (e Unit) Valid() bool {
	switch e {
	case UnitG:
		return true
	case UnitMl:
		return true
	case UnitPiece:
		return true
	default:
		return false
	}
}

// AuthResponse defines model for AuthResponse.
type AuthResponse struct {
	AccessToken string `json:"access_token"`

	// ExpiresIn Access token lifetime in seconds.
	ExpiresIn    int                   `json:"expires_in"`
	RefreshToken string                `json:"refresh_token"`
	TokenType    AuthResponseTokenType `json:"token_type"`
	User         User                  `json:"user"`
}

// AuthResponseTokenType defines model for AuthResponse.TokenType.
type AuthResponseTokenType string

// CreateIngredientRequest defines model for CreateIngredientRequest.
type CreateIngredientRequest struct {
	Category      IngredientCategory         `json:"category"`
	DensityGPerMl nullable.Nullable[float64] `json:"density_g_per_ml,omitempty"`
	GramsPerPiece nullable.Nullable[float64] `json:"grams_per_piece,omitempty"`
	Name          string                     `json:"name"`

	// Nutrients Amount per 100 g for each tracked nutrient the caller wants to set. Supplying the `nutrients` field replaces the ingredient's entire nutrient set — any of the 18 keys omitted, or explicitly set to null, is cleared. Omitting the `nutrients` field entirely from the request body leaves the ingredient's existing nutrients unchanged.
	Nutrients *NutrientAmountsInput `json:"nutrients,omitempty"`
}

// CreateMealRequest defines model for CreateMealRequest.
type CreateMealRequest struct {
	Name              string                    `json:"name"`
	Notes             nullable.Nullable[string] `json:"notes,omitempty"`
	Servings          float64                   `json:"servings"`
	SharedWithPartner *bool                     `json:"shared_with_partner,omitempty"`
}

// FieldError defines model for FieldError.
type FieldError struct {
	// Code Stable identifier, e.g. required, too_short, too_long, invalid_format, invalid_type, invalid_value.
	Code string `json:"code"`

	// Field Path of the offending JSON field, e.g. `email`.
	Field string `json:"field"`
}

// Health defines model for Health.
type Health struct {
	Status HealthStatus `json:"status"`
}

// HealthStatus defines model for Health.Status.
type HealthStatus string

// Ingredient defines model for Ingredient.
type Ingredient struct {
	Category      IngredientCategory         `json:"category"`
	CreatedAt     time.Time                  `json:"created_at"`
	DensityGPerMl nullable.Nullable[float64] `json:"density_g_per_ml"`
	GramsPerPiece nullable.Nullable[float64] `json:"grams_per_piece"`
	Id            openapi_types.UUID         `json:"id"`

	// IsCustom True for a custom ingredient owned by the caller; false for the global USDA catalog.
	IsCustom bool   `json:"is_custom"`
	Name     string `json:"name"`

	// Nutrients Amount per 100 g for each tracked nutrient. A null value means the amount is unknown. Units: kcal for calories; g for protein, carbohydrates, sugar, fibre, fat and saturated_fat; mg for sodium, potassium, calcium, iron, magnesium, zinc and vitamin_c; µg for vitamin_a, vitamin_d, vitamin_b12 and folate.
	Nutrients NutrientAmounts `json:"nutrients"`
	UpdatedAt time.Time       `json:"updated_at"`
}

// IngredientCategory defines model for IngredientCategory.
type IngredientCategory string

// IngredientList defines model for IngredientList.
type IngredientList struct {
	Items      []Ingredient              `json:"items"`
	NextCursor nullable.Nullable[string] `json:"next_cursor"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
}

// Meal defines model for Meal.
type Meal struct {
	CreatedAt   time.Time                 `json:"created_at"`
	Id          openapi_types.UUID        `json:"id"`
	Ingredients []MealIngredient          `json:"ingredients"`
	Name        string                    `json:"name"`
	Notes       nullable.Nullable[string] `json:"notes"`

	// NutritionPerServing Amount per 100 g for each tracked nutrient. A null value means the amount is unknown. Units: kcal for calories; g for protein, carbohydrates, sugar, fibre, fat and saturated_fat; mg for sodium, potassium, calcium, iron, magnesium, zinc and vitamin_c; µg for vitamin_a, vitamin_d, vitamin_b12 and folate.
	NutritionPerServing NutrientAmounts `json:"nutrition_per_serving"`
	Servings            float64         `json:"servings"`
	SharedWithPartner   bool            `json:"shared_with_partner"`
	UpdatedAt           time.Time       `json:"updated_at"`
}

// MealIngredient defines model for MealIngredient.
type MealIngredient struct {
	Id                 openapi_types.UUID `json:"id"`
	IngredientCategory IngredientCategory `json:"ingredient_category"`
	IngredientId       openapi_types.UUID `json:"ingredient_id"`
	IngredientName     string             `json:"ingredient_name"`
	Position           int                `json:"position"`
	Quantity           float64            `json:"quantity"`
	Unit               Unit               `json:"unit"`
}

// MealIngredientInput defines model for MealIngredientInput.
type MealIngredientInput struct {
	IngredientId openapi_types.UUID `json:"ingredient_id"`
	Quantity     float64            `json:"quantity"`
	Unit         Unit               `json:"unit"`
}

// MealList defines model for MealList.
type MealList struct {
	Items      []MealSummary             `json:"items"`
	NextCursor nullable.Nullable[string] `json:"next_cursor"`
}

// MealSummary defines model for MealSummary.
type MealSummary struct {
	CreatedAt         time.Time                 `json:"created_at"`
	Id                openapi_types.UUID        `json:"id"`
	Name              string                    `json:"name"`
	Notes             nullable.Nullable[string] `json:"notes"`
	Servings          float64                   `json:"servings"`
	SharedWithPartner bool                      `json:"shared_with_partner"`
	UpdatedAt         time.Time                 `json:"updated_at"`
}

// NutrientAmounts Amount per 100 g for each tracked nutrient. A null value means the amount is unknown. Units: kcal for calories; g for protein, carbohydrates, sugar, fibre, fat and saturated_fat; mg for sodium, potassium, calcium, iron, magnesium, zinc and vitamin_c; µg for vitamin_a, vitamin_d, vitamin_b12 and folate.
type NutrientAmounts struct {
	Calcium       nullable.Nullable[float64] `json:"calcium"`
	Calories      nullable.Nullable[float64] `json:"calories"`
	Carbohydrates nullable.Nullable[float64] `json:"carbohydrates"`
	Fat           nullable.Nullable[float64] `json:"fat"`
	Fibre         nullable.Nullable[float64] `json:"fibre"`
	Folate        nullable.Nullable[float64] `json:"folate"`
	Iron          nullable.Nullable[float64] `json:"iron"`
	Magnesium     nullable.Nullable[float64] `json:"magnesium"`
	Potassium     nullable.Nullable[float64] `json:"potassium"`
	Protein       nullable.Nullable[float64] `json:"protein"`
	SaturatedFat  nullable.Nullable[float64] `json:"saturated_fat"`
	Sodium        nullable.Nullable[float64] `json:"sodium"`
	Sugar         nullable.Nullable[float64] `json:"sugar"`
	VitaminA      nullable.Nullable[float64] `json:"vitamin_a"`
	VitaminB12    nullable.Nullable[float64] `json:"vitamin_b12"`
	VitaminC      nullable.Nullable[float64] `json:"vitamin_c"`
	VitaminD      nullable.Nullable[float64] `json:"vitamin_d"`
	Zinc          nullable.Nullable[float64] `json:"zinc"`
}

// NutrientAmountsInput Amount per 100 g for each tracked nutrient the caller wants to set. Supplying the `nutrients` field replaces the ingredient's entire nutrient set — any of the 18 keys omitted, or explicitly set to null, is cleared. Omitting the `nutrients` field entirely from the request body leaves the ingredient's existing nutrients unchanged.
type NutrientAmountsInput struct {
	Calcium       nullable.Nullable[float64] `json:"calcium,omitempty"`
	Calories      nullable.Nullable[float64] `json:"calories,omitempty"`
	Carbohydrates nullable.Nullable[float64] `json:"carbohydrates,omitempty"`
	Fat           nullable.Nullable[float64] `json:"fat,omitempty"`
	Fibre         nullable.Nullable[float64] `json:"fibre,omitempty"`
	Folate        nullable.Nullable[float64] `json:"folate,omitempty"`
	Iron          nullable.Nullable[float64] `json:"iron,omitempty"`
	Magnesium     nullable.Nullable[float64] `json:"magnesium,omitempty"`
	Potassium     nullable.Nullable[float64] `json:"potassium,omitempty"`
	Protein       nullable.Nullable[float64] `json:"protein,omitempty"`
	SaturatedFat  nullable.Nullable[float64] `json:"saturated_fat,omitempty"`
	Sodium        nullable.Nullable[float64] `json:"sodium,omitempty"`
	Sugar         nullable.Nullable[float64] `json:"sugar,omitempty"`
	VitaminA      nullable.Nullable[float64] `json:"vitamin_a,omitempty"`
	VitaminB12    nullable.Nullable[float64] `json:"vitamin_b12,omitempty"`
	VitaminC      nullable.Nullable[float64] `json:"vitamin_c,omitempty"`
	VitaminD      nullable.Nullable[float64] `json:"vitamin_d,omitempty"`
	Zinc          nullable.Nullable[float64] `json:"zinc,omitempty"`
}

// Problem RFC 9457 problem details with a stable machine-readable code.
type Problem struct {
	// Code Stable identifier clients map to localized text, e.g. partner_not_linked.
	Code   string  `json:"code"`
	Detail *string `json:"detail,omitempty"`

	// Errors Per-field details, present on validation_failed problems.
	Errors *[]FieldError `json:"errors,omitempty"`
	Status int           `json:"status"`
	Title  string        `json:"title"`
	Type   string        `json:"type"`
}

// RefreshRequest defines model for RefreshRequest.
type RefreshRequest struct {
	RefreshToken string `json:"refresh_token"`
}

// RegisterRequest defines model for RegisterRequest.
type RegisterRequest struct {
	DisplayName string              `json:"display_name"`
	Email       openapi_types.Email `json:"email"`
	Password    string              `json:"password"`
}

// ReplaceMealIngredientsRequest defines model for ReplaceMealIngredientsRequest.
type ReplaceMealIngredientsRequest struct {
	Items []MealIngredientInput `json:"items"`
}

// Unit defines model for Unit.
type Unit string

// UpdateIngredientRequest defines model for UpdateIngredientRequest.
type UpdateIngredientRequest struct {
	Category      *IngredientCategory        `json:"category,omitempty"`
	DensityGPerMl nullable.Nullable[float64] `json:"density_g_per_ml,omitempty"`
	GramsPerPiece nullable.Nullable[float64] `json:"grams_per_piece,omitempty"`
	Name          *string                    `json:"name,omitempty"`

	// Nutrients Amount per 100 g for each tracked nutrient the caller wants to set. Supplying the `nutrients` field replaces the ingredient's entire nutrient set — any of the 18 keys omitted, or explicitly set to null, is cleared. Omitting the `nutrients` field entirely from the request body leaves the ingredient's existing nutrients unchanged.
	Nutrients *NutrientAmountsInput `json:"nutrients,omitempty"`
}

// UpdateMealRequest defines model for UpdateMealRequest.
type UpdateMealRequest struct {
	Name              *string                   `json:"name,omitempty"`
	Notes             nullable.Nullable[string] `json:"notes,omitempty"`
	Servings          *float64                  `json:"servings,omitempty"`
	SharedWithPartner *bool                     `json:"shared_with_partner,omitempty"`
}

// UpdateProfileRequest defines model for UpdateProfileRequest.
type UpdateProfileRequest struct {
	DisplayName    *string                    `json:"display_name,omitempty"`
	TargetCarbsG   nullable.Nullable[float64] `json:"target_carbs_g,omitempty"`
	TargetFatG     nullable.Nullable[float64] `json:"target_fat_g,omitempty"`
	TargetKcal     nullable.Nullable[float64] `json:"target_kcal,omitempty"`
	TargetProteinG nullable.Nullable[float64] `json:"target_protein_g,omitempty"`
}

// User defines model for User.
type User struct {
	CreatedAt      time.Time                  `json:"created_at"`
	DisplayName    string                     `json:"display_name"`
	Email          string                     `json:"email"`
	Id             openapi_types.UUID         `json:"id"`
	TargetCarbsG   nullable.Nullable[float64] `json:"target_carbs_g,omitempty"`
	TargetFatG     nullable.Nullable[float64] `json:"target_fat_g,omitempty"`
	TargetKcal     nullable.Nullable[float64] `json:"target_kcal,omitempty"`
	TargetProteinG nullable.Nullable[float64] `json:"target_protein_g,omitempty"`
	UpdatedAt      time.Time                  `json:"updated_at"`
}

// BadRequest RFC 9457 problem details with a stable machine-readable code.
type BadRequest = Problem

// Conflict RFC 9457 problem details with a stable machine-readable code.
type Conflict = Problem

// NotFound RFC 9457 problem details with a stable machine-readable code.
type NotFound = Problem

// TooManyRequests RFC 9457 problem details with a stable machine-readable code.
type TooManyRequests = Problem

// Unauthorized RFC 9457 problem details with a stable machine-readable code.
type Unauthorized = Problem

// ListIngredientsParams defines parameters for ListIngredients.
type ListIngredientsParams struct {
	Q        *string             `form:"q,omitempty" json:"q,omitempty"`
	Category *IngredientCategory `form:"category,omitempty" json:"category,omitempty"`
	Cursor   *string             `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit    *int                `form:"limit,omitempty" json:"limit,omitempty"`
}

// ListMealsParams defines parameters for ListMeals.
type ListMealsParams struct {
	Cursor *string `form:"cursor,omitempty" json:"cursor,omitempty"`
	Limit  *int    `form:"limit,omitempty" json:"limit,omitempty"`
}

// LoginUserJSONRequestBody defines body for LoginUser for application/json ContentType.
type LoginUserJSONRequestBody = LoginRequest

// LogoutUserJSONRequestBody defines body for LogoutUser for application/json ContentType.
type LogoutUserJSONRequestBody = RefreshRequest

// RefreshSessionJSONRequestBody defines body for RefreshSession for application/json ContentType.
type RefreshSessionJSONRequestBody = RefreshRequest

// RegisterUserJSONRequestBody defines body for RegisterUser for application/json ContentType.
type RegisterUserJSONRequestBody = RegisterRequest

// CreateIngredientJSONRequestBody defines body for CreateIngredient for application/json ContentType.
type CreateIngredientJSONRequestBody = CreateIngredientRequest

// UpdateIngredientJSONRequestBody defines body for UpdateIngredient for application/json ContentType.
type UpdateIngredientJSONRequestBody = UpdateIngredientRequest

// UpdateMeJSONRequestBody defines body for UpdateMe for application/json ContentType.
type UpdateMeJSONRequestBody = UpdateProfileRequest

// CreateMealJSONRequestBody defines body for CreateMeal for application/json ContentType.
type CreateMealJSONRequestBody = CreateMealRequest

// UpdateMealJSONRequestBody defines body for UpdateMeal for application/json ContentType.
type UpdateMealJSONRequestBody = UpdateMealRequest

// ReplaceMealIngredientsJSONRequestBody defines body for ReplaceMealIngredients for application/json ContentType.
type ReplaceMealIngredientsJSONRequestBody = ReplaceMealIngredientsRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// LoginUser Sign in with email and password
	// (POST /auth/login)
	LoginUser(w http.ResponseWriter, r *http.Request)
	// LogoutUser Revoke a refresh-token session
	// (POST /auth/logout)
	LogoutUser(w http.ResponseWriter, r *http.Request)
	// RefreshSession Exchange a refresh token for a new token pair
	// (POST /auth/refresh)
	RefreshSession(w http.ResponseWriter, r *http.Request)
	// RegisterUser Create an account
	// (POST /auth/register)
	RegisterUser(w http.ResponseWriter, r *http.Request)
	// GetHealth Liveness probe
	// (GET /healthz)
	GetHealth(w http.ResponseWriter, r *http.Request)
	// ListIngredients List or search ingredients
	// (GET /ingredients)
	ListIngredients(w http.ResponseWriter, r *http.Request, params ListIngredientsParams)
	// CreateIngredient Create a custom ingredient
	// (POST /ingredients)
	CreateIngredient(w http.ResponseWriter, r *http.Request)
	// DeleteIngredient Delete a custom ingredient
	// (DELETE /ingredients/{id})
	DeleteIngredient(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// UpdateIngredient Update a custom ingredient
	// (PATCH /ingredients/{id})
	UpdateIngredient(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// DeleteMe Delete the signed-in user's account
	// (DELETE /me)
	DeleteMe(w http.ResponseWriter, r *http.Request)
	// GetMe Get the signed-in user's profile
	// (GET /me)
	GetMe(w http.ResponseWriter, r *http.Request)
	// UpdateMe Update the signed-in user's profile
	// (PATCH /me)
	UpdateMe(w http.ResponseWriter, r *http.Request)
	// ListMeals List the caller's meals
	// (GET /meals)
	ListMeals(w http.ResponseWriter, r *http.Request, params ListMealsParams)
	// CreateMeal Create a meal
	// (POST /meals)
	CreateMeal(w http.ResponseWriter, r *http.Request)
	// DeleteMeal Delete a meal
	// (DELETE /meals/{id})
	DeleteMeal(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// GetMeal Get a meal
	// (GET /meals/{id})
	GetMeal(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// UpdateMeal Update a meal
	// (PATCH /meals/{id})
	UpdateMeal(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// CopyMeal Copy a meal
	// (POST /meals/{id}/copy)
	CopyMeal(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// ReplaceMealIngredients Replace a meal's ingredient list
	// (PUT /meals/{id}/ingredients)
	ReplaceMealIngredients(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// GetReady Readiness probe
	// (GET /readyz)
	GetReady(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// LoginUser Sign in with email and password
// (POST /auth/login)
func (_ Unimplemented) LoginUser(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// LogoutUser Revoke a refresh-token session
// (POST /auth/logout)
func (_ Unimplemented) LogoutUser(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// RefreshSession Exchange a refresh token for a new token pair
// (POST /auth/refresh)
func (_ Unimplemented) RefreshSession(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// RegisterUser Create an account
// (POST /auth/register)
func (_ Unimplemented) RegisterUser(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetHealth Liveness probe
// (GET /healthz)
func (_ Unimplemented) GetHealth(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ListIngredients List or search ingredients
// (GET /ingredients)
func (_ Unimplemented) ListIngredients(w http.ResponseWriter, r *http.Request, params ListIngredientsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// CreateIngredient Create a custom ingredient
// (POST /ingredients)
func (_ Unimplemented) CreateIngredient(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// DeleteIngredient Delete a custom ingredient
// (DELETE /ingredients/{id})
func (_ Unimplemented) DeleteIngredient(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// UpdateIngredient Update a custom ingredient
// (PATCH /ingredients/{id})
func (_ Unimplemented) UpdateIngredient(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// DeleteMe Delete the signed-in user's account
// (DELETE /me)
func (_ Unimplemented) DeleteMe(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetMe Get the signed-in user's profile
// (GET /me)
func (_ Unimplemented) GetMe(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// UpdateMe Update the signed-in user's profile
// (PATCH /me)
func (_ Unimplemented) UpdateMe(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ListMeals List the caller's meals
// (GET /meals)
func (_ Unimplemented) ListMeals(w http.ResponseWriter, r *http.Request, params ListMealsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// CreateMeal Create a meal
// (POST /meals)
func (_ Unimplemented) CreateMeal(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// DeleteMeal Delete a meal
// (DELETE /meals/{id})
func (_ Unimplemented) DeleteMeal(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetMeal Get a meal
// (GET /meals/{id})
func (_ Unimplemented) GetMeal(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// UpdateMeal Update a meal
// (PATCH /meals/{id})
func (_ Unimplemented) UpdateMeal(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// CopyMeal Copy a meal
// (POST /meals/{id}/copy)
func (_ Unimplemented) CopyMeal(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ReplaceMealIngredients Replace a meal's ingredient list
// (PUT /meals/{id}/ingredients)
func (_ Unimplemented) ReplaceMealIngredients(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// GetReady Readiness probe
// (GET /readyz)
func (_ Unimplemented) GetReady(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// LoginUser operation middleware
func (siw *ServerInterfaceWrapper) LoginUser(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.LoginUser(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// LogoutUser operation middleware
func (siw *ServerInterfaceWrapper) LogoutUser(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.LogoutUser(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RefreshSession operation middleware
func (siw *ServerInterfaceWrapper) RefreshSession(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RefreshSession(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RegisterUser operation middleware
func (siw *ServerInterfaceWrapper) RegisterUser(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RegisterUser(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListIngredients operation middleware
func (siw *ServerInterfaceWrapper) ListIngredients(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListIngredientsParams

	// ------------- Optional query parameter "q" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "q", r.URL.Query(), &params.Q, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "q"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "q", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "category" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "category", r.URL.Query(), &params.Category, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "category"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "category", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", r.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "cursor"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListIngredients(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateIngredient operation middleware
func (siw *ServerInterfaceWrapper) CreateIngredient(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateIngredient(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteIngredient operation middleware
func (siw *ServerInterfaceWrapper) DeleteIngredient(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteIngredient(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateIngredient operation middleware
func (siw *ServerInterfaceWrapper) UpdateIngredient(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateIngredient(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteMe operation middleware
func (siw *ServerInterfaceWrapper) DeleteMe(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteMe(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMe operation middleware
func (siw *ServerInterfaceWrapper) GetMe(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMe(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateMe operation middleware
func (siw *ServerInterfaceWrapper) UpdateMe(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateMe(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListMeals operation middleware
func (siw *ServerInterfaceWrapper) ListMeals(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListMealsParams

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", r.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "cursor"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListMeals(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateMeal operation middleware
func (siw *ServerInterfaceWrapper) CreateMeal(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateMeal(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteMeal operation middleware
func (siw *ServerInterfaceWrapper) DeleteMeal(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteMeal(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetMeal operation middleware
func (siw *ServerInterfaceWrapper) GetMeal(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetMeal(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateMeal operation middleware
func (siw *ServerInterfaceWrapper) UpdateMeal(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateMeal(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CopyMeal operation middleware
func (siw *ServerInterfaceWrapper) CopyMeal(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CopyMeal(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ReplaceMealIngredients operation middleware
func (siw *ServerInterfaceWrapper) ReplaceMealIngredients(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid", ValueIsUnescaped: r.URL.RawPath == ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ReplaceMealIngredients(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetReady operation middleware
func (siw *ServerInterfaceWrapper) GetReady(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetReady(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/ingredients", wrapper.ListIngredients)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/ingredients", wrapper.CreateIngredient)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/ingredients/{id}", wrapper.DeleteIngredient)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/ingredients/{id}", wrapper.UpdateIngredient)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/meals", wrapper.ListMeals)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/meals", wrapper.CreateMeal)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/meals/{id}", wrapper.DeleteMeal)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/meals/{id}", wrapper.GetMeal)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/meals/{id}", wrapper.UpdateMeal)
	})
	r.Group(func(r chi.Router) {
		r.Put(options.BaseURL+"/meals/{id}/ingredients", wrapper.ReplaceMealIngredients)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/meals/{id}/copy", wrapper.CopyMeal)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/healthz", wrapper.GetHealth)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/readyz", wrapper.GetReady)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/register", wrapper.RegisterUser)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/login", wrapper.LoginUser)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/refresh", wrapper.RefreshSession)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/logout", wrapper.LogoutUser)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/me", wrapper.DeleteMe)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/me", wrapper.GetMe)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/me", wrapper.UpdateMe)
	})

	return r
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7Hzdbty4kv+rFPT/A7OLle22M8HmOFeezMzZHCQzQT6QiyBos6VqNY8pUiEpOz2BgX2IfZV9gX2UfZIF",
	"i5RaX+3ulu1OJuO7/hDJYtWvqljFKn2JEpUXSqK0Jjr9Emk0hZIG6ctPLH2Nn0o01n1LlLQo6SMrCsET",
	"ZrmSR4VWM4H5v/3TKOn+M8kCc+Y+/X+N8+g0+n9HqyWO/L/m6JUfFV1fX8dRiibRvHDTRafR2wWC9ssC",
	"N5AzMVc6xxSUhjnjwsAlEzyl1Q/hV44ihRQt/cM0Apdwjlorbc4Po+s4eqbkXPDkq+0hCesbuOJ2AfiZ",
	"G8tlBsYyi0Thb8r+qkqZ7p9Co0qdIKQKDUhlPXGx4zR9MjArSQjuv0tu+EwgWAV2gZAwIVAT/dUyeyT/",
	"TALJGFSSlFpjSoS8Veolk8sAWrNPgl4ziyB4zh0TE8TUkRRHC2QpaqLkNVq9PDibW9TtFe2ywOg04tJi",
	"htpNfh1H7yQr7UJp/gfuFRcvuTFcZjFwSWrmsVBwjSkkGlOUljNhOnt7//79wVlpF+7fhFkc3KCxmsuM",
	"9ncdh79ptBv5Ohge973QqkBtubdCLEnQmKlVFygHZosjT56Zcvq7gxMaDDQYBJ+j5TmZCIOJkinto8v/",
	"ONI412gWN6xJ/0z9z18ilGUenX6IfkKmUUcf4/6A0nix3ySWd4bE79b/VDqOuzlb2++S1iKkxYmw4ooU",
	"NfsnJpYMokZm8bnMNKYcpW3YeJam3HGOiVcNGcyZMBh3xOLEnCm93LSp1TrPqhEEOmm4XU6zaYF6mgvi",
	"4udElIZf4ksuee44anWJceTMP7PRaZSqcibcPnP22T/wKI7y6uFJHMlSCOYeCSPD1mWZz7xgM81yQ0sW",
	"HBMcuerxZDKZ7LiyZDktl7PPL1BmdhGdnoRJqu/HA7CRpdW8cs43sfm38OBZrkppzXNZlLaHJSIiXolu",
	"PTpeIhPjcDF2o8r68e1x61m7GmpQX3KZmVtIsy3MnvDMgmlMp85/TwumrfS6HJ6bKSWQyXXcrskb4jYd",
	"X35xnqxv+BKVYt+ivbGOGcDJEs856hjwMDuEauUYrFJTs1Da+o9CNcz51DNi9d1RtPp2yUSJDZu4YvLc",
	"Edqn5hWzC1BzOhGo+Rxl6o42/3jz+29AIwJx55gzLs4HZu7wzC8T+70PMew/kAmHjS6z3GmqNE1jrC4G",
	"DHFnuTBqaKGV3RqQzK1sX0Ialk4ZzbxCJrN44NzTEPuH7GUf02Ps34hZeNoaWJY8HaKZm2lSGqvyPmze",
	"6hJhrjQw8I8Ar1kF6kpiCrNl45j5FMjW0BD3aybUjAl49+bnM0iYZUJlDWzVCrkyu3dmWMmXF+mOAuzA",
	"jvjVNcZNhvUlNQCB5iZaqGpReDO2nzWQXClOoVVa+iUZ18spZplbIEdmpwbZXKnUE8ilmc40MvdVYFbm",
	"aKaytGZqEFOiScmU547AqeLC/WIKnqCZLlDP3NcZXqJmGdJfV4hurGTJhfuu7GLNWWpF/gtuBtSTW8zb",
	"H7ZTUjrY+cWY1oyUVeJnO01KbbyF3uCMunKm9duTDMnjhcq4HOduybC2YOh/iVuO9PGPA2wsmDFXSqcd",
	"r3t88mSDt+7sslqwnm9oi+5AMWBIR5jCba1PLdbtoeCI3ACHtfakOr9sPK6Q0jrpkh6H08EIK9Q89vSN",
	"+NgzzB1bN8+WBrHDhLTFtY5Huxm5jjD7VmJXHE1v5/YbE+2+9FrcFcpw71S/DASyn0omLbfLLTFSSm43",
	"BqnumUGRtzfYJ3+Ylw0iAwGNTW2Wqw90drOZu0uiycexAeOmIGM88zt87/JzHRPvwnm6ed6Uec48xr+K",
	"92zSsE8Pcwe+4Puy4btY565D62fu6A8oUMPxZAIZnf2RJQuwmiUXmEJ1+j2EM3CcBopeIUcmDUUJzE/B",
	"DZTyQqoreQhOgcwpXCRM0IQJE0pzNE/DAoVWFrmMIWF6phbLVDOLJgZTZkzHMOczjTHMmQUmUzDMlpp2",
	"OWf2KeR+DqNSXuYxFMoyY+hjwkRCH7hWMoacZRL9P39wmdBcl9yynMtp8hT+57/9RNVPLK4/pquPs+MT",
	"GjhXgi4S+gk6WnNkjFcxZvTwBvtGzjHvonf7kU5MY8cSO8dGxtp74hFDa0yMHF+jbex4j/yRo1uaMHYO",
	"0puxg52Cjhxb69ktx8+OT245Q3LL8enI8c4KjRracRu11VjhqWsLKlFVWur1vIugGg1NYMe1TQua1tSa",
	"sImmNJt8bfKoLbFa5bdwU9udNsc6skbCC66YtAasAoP2EN6URSGWXGb0yHmd9zn3WVbQWAiWoHd7q/Pg",
	"DwZQWq5xtYRBC//7n/8FTC6rvO3xE7jApQGVc2sxDde/heAJt2JJI6wiDxs7X5oIdM7/EH53z6+nya8s",
	"ljDXKqdnqhvxmUqXIJBdDhJc3Y/XE0IpkwWTmb9RfXByD07uwck9OLn9OrmeY2jUvHQKQX59Bn/78fG/",
	"QyjNqGuTqPqHgfH3dzlLFlzigUaW0g+JSocO8dvdAUIivKnMWeGMtVAJE/wPTMHiZxsu4UKgNpXKTgWX",
	"F96eDlw12ZBS7ldaUFnVwC0g6oN5sxArhkKjocsc2SjXms4ZF5hWrKHqi63SDI1r0oEsw+rur58Bs9yK",
	"4Si9Kt5YxfmaH2ico0aZbI6QQ8mFn7+m4Yaby9e+cmNcmr9XkdJI2D8+PtktYd+ebJjWjBuLehyxKTeF",
	"YMvpQCnAk82VAHu40ZjsfKURtzc1zDM6g7XTk2YcB3dPwnUzouRsPz/3w6kAo601g7m2oW29C2nJ6nYw",
	"c4Ig3tC95ND93DtK/TwUGP01Coz6iCHxP1QQjasgWsPOV1rNucCvYZAt0xnaqYt2zDQbPkHVvHi8O3LD",
	"/HNmN85+Mnr2i4SNtQEnk9Grhnjj7vc1CJRQYnr7C5AuXtb76LF3J9tg6g6Asys6xs+wQdIbp7mbG5vq",
	"3NIS4C4XM2QMk1Jzu3zjDL/H0Izqms9KX3jnv/1akfiP92+jUM5NtszXQNczL6wtfKE5l3PVjx2eKWk1",
	"S2xd2+UcB7wSTErUcPbq+SG8XXADzvoB9wkjw2UmEEL3gpqD1aVdPKX/Ziy5QJnGcIUzuh/hv7+pwyOm",
	"ETKUSFG8T0xxe1gf40+j7uJRHF2iNp7UyeHx4cQJSxUoWcGj0+jR4eTwER0U7YJYdcRKuzgSKvNZhkJ5",
	"Y+00kkKg52l06ut9SF29DNHYn1S6vKHOf7f6/lY90XUbKQ5/9EOj0edkMrmztVvF/GsaT0qD2snS8Exi",
	"ClxS98aPnoqhyWtqjxo9STTkePOQViuFG3Tyt82Duq0k13H0eBv6Vq0VK02KTj98jCNTXVFHb3gmgcvQ",
	"D+RUloDaCDYsc4eRD9QZEX10c9W4Uj4BXQGrzdznKeaFsv5SVFbXnqA0MKGRpcsDjZfqAtPQERFae1jo",
	"pnGa0EOqKu09QrUTFW8F1h8HCkqdVUDjFNVtKuxyNKy+NkJeE/3AIITqB15cYYc3ACQ8vx4hr5VlNuTd",
	"w8MeC4fwyqdsuMwcICrAlAbT9pOBu36Oq4USK9bPWc7Fsg+jIOU3Nf3fCpT2Z/fOQOJVYGDBuP5rmbxf",
	"PvsrnBWkAyt8EXibNTfi2yem1gPc968YgnCS0NXbGjvrSzh4FqpFvFOSQ+D1a96rFWzn27bC7vFefXbN",
	"TGYgnCfHQ3gLNNZtu98CfD2oGpgahuiCmlP+cGtmOGR80ZZaGjiZTOBqgZJwV2hFPYrcQFkcws9VL65V",
	"ZbKgJ1Jm2YwZ7EPz72hDQ8w9WrawwhpcUO4koaM5E/zSdzTfGeNf8EuUjjuFVjNscD0Q5fneqfUe5P17",
	"bheqtHD+6TwGQc3NjWHARLFgM7Q8YUIsvcnwNYdQsIzL0G7uZvFTGGQ6WaCB2RJcmEXWRAcBUyCCxkLO",
	"rHsoJomGify9S+ecxY193iqBLphmOVpqsP3wJXLhRPSpRKqY9XF59KmKu1g34b0xXXYdD0/ZKMvdDhxD",
	"2de1k/sazviG1uA1I6mxujUwxTkrhY1OTybtTFwjjXLc7+29/niPitLpSxnqrnZwcAesBvS+04NAQ4WN",
	"dRGIVxhoF/pX6tzE/kdf1j4QN3c7l+/JG69rkN6zV252ogzb3kbT3J245T8HoCpn3G8dXAuojpM4+sLT",
	"a29FBPo6mDbQfqbfO0DbJgbtSMTPX0lkDHv9QjcPqt8f8m2frWoBeu7uJMBhf1gwOvkEJ0EZ0LZ6Nj3G",
	"hpy08wyFM899wVL1gXPqzFIGkc2otMF9FDi3jfo0+F2K5bZNrZAwCTOEkJDtHwq696j3ZO7WXdfuOYDe",
	"bO4Coxps3a+p21kX969aXpY728Yc29awV96TM7e+WAaLFvorQkjoTr54iXpp/dmG0G76ePZ6/xK3tqbN",
	"mPP2pvSrGTp/ZZFJTA+4pDzDD2YgkAxXvGTtQgjTi/aGmHd3KhheQDOofIWn7k/F/7+jHWZ+2Mwa5t/e",
	"DZxByrhYgr8cbJZQNyuo1xj8IOP7MvSdSoI9W/mbIFbZ9zbUvttzbLDVOwPUG2wm1uc6nlGgfVDnG+JW",
	"eqPKWDRyTVwmokyxlRFRGtxmSlt1KLjJn8IcbUJ1rP4O1hESrm7VUIbKRX8viditUhrfe4qg7rtdowL+",
	"ZPiDIb7+NVIDtrftBuo9dJoZgeFsv5uEoOirrCVgXthl8wAuuLGHcJamLZDT4+ev3r0Fr1IUGTZDxfM+",
	"pFdvyLrX/EOzgG7PmQfa2xqEei7/BbMNuRd4F5m1Nd4yqVDjZpsDcM3sr5BI+Ip5gTWsjoe93XPvvLq9",
	"ZKTxFJvU3oua8EKxZ7zybkqCRpYOXq8Mi2uyN1V7SB31TvQ34ONPlCSiN+ZdyZAGKqu43ct8XWBwby6n",
	"X7O957jgJj2o4oKGPnyrGZ8/gQq9a0Jto0M7SlThX6uyD9W6uaKDykQcafFQOjX2hzkKp1iOFOLQvSu9",
	"vyNU+PuK0MblG9CpWxVLYOKKLQ0Yy3R9MBwo2z/3ryIcOBaqYjnsLfZzMHObePAW7bMbyXVLoHeKCPaC",
	"93IA7mdW5aEKodXWP6fsUTeg+eUS9RK0ugJevxgfU/iXzlkoL014uztpwAyHX+cee/2gnnseRs0ctOQl",
	"auue/1eY4Vw5/yardK+BK82tRfl0FXidU0PZOVC3mU94+V0Q1QMlVkO9c/dWbHVTo96D3/tOjUEQe7AH",
	"P5iuLq2xEFQFu2NJV1UT5U52ml714VSqKuOK4fHkEdDrTa/4mqqu127Vb6Koi/ZPVoJdIFjN5nOehCKv",
	"R3dV7cxSvqHKqz283ZLy4aMzpo7mylq3d/RCJUxAipcoVJH7u7BSi9Cccnp0RO3yC2Xs6ZPJk8nR5XHk",
	"JgxE9GarStJ8wVdFerLA5IIuvYJ7qDgc9yGTcWO9vGOgVpEw10Ctd3NG2m1/vrdDCWR1JaskMk0erpsa",
	"s1UJ5eEJwxuWqV4W9UEojq0VpvHS5TBd0273pySNglnJhQ1tN6vHw8FtFaUPBeZhFa+Z1x+v/y8AAP//",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
