// Generated by swift-openapi-generator, do not modify.
@_spi(Generated) public import OpenAPIRuntime
#if os(Linux)
@preconcurrency public import struct Foundation.URL
@preconcurrency public import struct Foundation.Data
@preconcurrency public import struct Foundation.Date
#else
public import struct Foundation.URL
public import struct Foundation.Data
public import struct Foundation.Date
#endif
/// A type that performs HTTP operations defined by the OpenAPI document.
public protocol APIProtocol: Sendable {
    /// List or search ingredients
    ///
    /// Without `q`, lists ingredients alphabetically with cursor pagination. With `q`, searches by name and returns the best matches, not paginated.
    ///
    /// - Remark: HTTP `GET /ingredients`.
    /// - Remark: Generated from `#/paths//ingredients/get(listIngredients)`.
    func listIngredients(_ input: Operations.ListIngredients.Input) async throws -> Operations.ListIngredients.Output
    /// Create a custom ingredient
    ///
    /// - Remark: HTTP `POST /ingredients`.
    /// - Remark: Generated from `#/paths//ingredients/post(createIngredient)`.
    func createIngredient(_ input: Operations.CreateIngredient.Input) async throws -> Operations.CreateIngredient.Output
    /// Update a custom ingredient
    ///
    /// Fields that are absent are left unchanged. Only a custom ingredient owned by the caller can be updated. Clearing `grams_per_piece` or `density_g_per_ml` while a meal still uses this ingredient with the `piece` or `ml` unit is rejected (`409 unit_not_convertible`).
    ///
    /// - Remark: HTTP `PATCH /ingredients/{id}`.
    /// - Remark: Generated from `#/paths//ingredients/{id}/patch(updateIngredient)`.
    func updateIngredient(_ input: Operations.UpdateIngredient.Input) async throws -> Operations.UpdateIngredient.Output
    /// Delete a custom ingredient
    ///
    /// - Remark: HTTP `DELETE /ingredients/{id}`.
    /// - Remark: Generated from `#/paths//ingredients/{id}/delete(deleteIngredient)`.
    func deleteIngredient(_ input: Operations.DeleteIngredient.Input) async throws -> Operations.DeleteIngredient.Output
    /// List the caller's diet templates
    ///
    /// Cursor-paginated, alphabetical by name. Lists only the caller's own templates (the partner's shared ones are at `GET /partner/diet-templates`). Does not include slots; fetch a single template for those.
    ///
    /// - Remark: HTTP `GET /diet-templates`.
    /// - Remark: Generated from `#/paths//diet-templates/get(listDietTemplates)`.
    func listDietTemplates(_ input: Operations.ListDietTemplates.Input) async throws -> Operations.ListDietTemplates.Output
    /// Create a diet template
    ///
    /// Creates the template with no slots. Add slots with `PUT /diet-templates/{id}/slots`.
    ///
    /// - Remark: HTTP `POST /diet-templates`.
    /// - Remark: Generated from `#/paths//diet-templates/post(createDietTemplate)`.
    func createDietTemplate(_ input: Operations.CreateDietTemplate.Input) async throws -> Operations.CreateDietTemplate.Output
    /// Get a diet template
    ///
    /// Includes the slot list. Returns the caller's own template, or a template the partner has shared (`is_owner` false), whose slots show each meal's id and name even if that meal is not shared itself (its detail stays `404`). Any other template is `404`.
    ///
    /// - Remark: HTTP `GET /diet-templates/{id}`.
    /// - Remark: Generated from `#/paths//diet-templates/{id}/get(getDietTemplate)`.
    func getDietTemplate(_ input: Operations.GetDietTemplate.Input) async throws -> Operations.GetDietTemplate.Output
    /// Update a diet template
    ///
    /// Fields that are absent are left unchanged. day_count cannot be changed after creation; recreate or copy the template instead.
    ///
    /// - Remark: HTTP `PATCH /diet-templates/{id}`.
    /// - Remark: Generated from `#/paths//diet-templates/{id}/patch(updateDietTemplate)`.
    func updateDietTemplate(_ input: Operations.UpdateDietTemplate.Input) async throws -> Operations.UpdateDietTemplate.Output
    /// Delete a diet template
    ///
    /// Any plan entries created by applying this template keep their row, with from_template_id set to null.
    ///
    /// - Remark: HTTP `DELETE /diet-templates/{id}`.
    /// - Remark: Generated from `#/paths//diet-templates/{id}/delete(deleteDietTemplate)`.
    func deleteDietTemplate(_ input: Operations.DeleteDietTemplate.Input) async throws -> Operations.DeleteDietTemplate.Output
    /// Replace a diet template's slot list
    ///
    /// Atomically replaces the full slot list. Every row is validated (day_index must be within the template's day_count, and the meal must exist and be visible to the caller) before anything is written; an empty `items` array clears the list.
    ///
    /// - Remark: HTTP `PUT /diet-templates/{id}/slots`.
    /// - Remark: Generated from `#/paths//diet-templates/{id}/slots/put(replaceTemplateSlots)`.
    func replaceTemplateSlots(_ input: Operations.ReplaceTemplateSlots.Input) async throws -> Operations.ReplaceTemplateSlots.Output
    /// Apply a template to the plan
    ///
    /// Copies the template's slots into plan entries starting at `start_date`. Without `overwrite`, fails if any non-snack target date+slot already has an entry; snack slots are always added. With `overwrite`, the same non-snack targets are replaced.
    ///
    /// - Remark: HTTP `POST /diet-templates/{id}/apply`.
    /// - Remark: Generated from `#/paths//diet-templates/{id}/apply/post(applyDietTemplate)`.
    func applyDietTemplate(_ input: Operations.ApplyDietTemplate.Input) async throws -> Operations.ApplyDietTemplate.Output
    /// Copy a diet template
    ///
    /// Creates a new template, owned by the caller, with the same name, day_count and slots. The original may be the caller's own or one the partner has shared. Copying the partner's template also copies its meals (each once, with the same ingredient rules as `POST /meals/{id}/copy`), so the copy can be applied to the caller's own plan. The copy always starts with `shared_with_partner` false.
    ///
    /// - Remark: HTTP `POST /diet-templates/{id}/copy`.
    /// - Remark: Generated from `#/paths//diet-templates/{id}/copy/post(copyDietTemplate)`.
    func copyDietTemplate(_ input: Operations.CopyDietTemplate.Input) async throws -> Operations.CopyDietTemplate.Output
    /// List the caller's meals
    ///
    /// Cursor-paginated, alphabetical by name. Lists only the caller's own meals (the partner's shared ones are at `GET /partner/meals`). Does not include ingredients or computed nutrition; fetch a single meal for those.
    ///
    /// - Remark: HTTP `GET /meals`.
    /// - Remark: Generated from `#/paths//meals/get(listMeals)`.
    func listMeals(_ input: Operations.ListMeals.Input) async throws -> Operations.ListMeals.Output
    /// Create a meal
    ///
    /// Creates the meal with an empty ingredient list. Add ingredients with `PUT /meals/{id}/ingredients`.
    ///
    /// - Remark: HTTP `POST /meals`.
    /// - Remark: Generated from `#/paths//meals/post(createMeal)`.
    func createMeal(_ input: Operations.CreateMeal.Input) async throws -> Operations.CreateMeal.Output
    /// Get a meal
    ///
    /// Includes the ingredient list and nutrition per serving, computed on read. Returns the caller's own meal, or a meal the partner has shared (`is_owner` false). Any other meal is `404`.
    ///
    /// - Remark: HTTP `GET /meals/{id}`.
    /// - Remark: Generated from `#/paths//meals/{id}/get(getMeal)`.
    func getMeal(_ input: Operations.GetMeal.Input) async throws -> Operations.GetMeal.Output
    /// Update a meal
    ///
    /// Fields that are absent are left unchanged. Only the owner can update a meal; for anyone else, including the partner, it is `404`.
    ///
    /// - Remark: HTTP `PATCH /meals/{id}`.
    /// - Remark: Generated from `#/paths//meals/{id}/patch(updateMeal)`.
    func updateMeal(_ input: Operations.UpdateMeal.Input) async throws -> Operations.UpdateMeal.Output
    /// Delete a meal
    ///
    /// - Remark: HTTP `DELETE /meals/{id}`.
    /// - Remark: Generated from `#/paths//meals/{id}/delete(deleteMeal)`.
    func deleteMeal(_ input: Operations.DeleteMeal.Input) async throws -> Operations.DeleteMeal.Output
    /// Replace a meal's ingredient list
    ///
    /// Atomically replaces the full ingredient list. Every row is validated (the ingredient must exist and be visible to the caller, and its unit must be convertible) before anything is written; an empty `items` array clears the list.
    ///
    /// - Remark: HTTP `PUT /meals/{id}/ingredients`.
    /// - Remark: Generated from `#/paths//meals/{id}/ingredients/put(replaceMealIngredients)`.
    func replaceMealIngredients(_ input: Operations.ReplaceMealIngredients.Input) async throws -> Operations.ReplaceMealIngredients.Output
    /// Copy a meal
    ///
    /// Creates a new meal, owned by the caller, with the same name, notes, servings and ingredients. The original may be the caller's own or one the partner has shared. Copying the partner's meal also copies each custom ingredient it uses into the caller's library (once per copy; global ingredients are shared). The copy always starts with `shared_with_partner` false.
    ///
    /// - Remark: HTTP `POST /meals/{id}/copy`.
    /// - Remark: Generated from `#/paths//meals/{id}/copy/post(copyMeal)`.
    func copyMeal(_ input: Operations.CopyMeal.Input) async throws -> Operations.CopyMeal.Output
    /// Get the plan for a date range
    ///
    /// One DailyTotal per calendar date in [from, to] inclusive, with nutrition computed from each entry's meal and compared against the caller's targets. Capped at 92 days.
    ///
    /// - Remark: HTTP `GET /plan`.
    /// - Remark: Generated from `#/paths//plan/get(getPlan)`.
    func getPlan(_ input: Operations.GetPlan.Input) async throws -> Operations.GetPlan.Output
    /// Set or swap the meal for a date and slot
    ///
    /// For breakfast/lunch/dinner this upserts the one entry for that date+slot. For snack, since the URL can't select among several, this always adds a new entry. Either way, the written entry's from_template_id is null.
    ///
    /// - Remark: HTTP `PUT /plan/{date}/{slot}`.
    /// - Remark: Generated from `#/paths//plan/{date}/{slot}/put(setPlanEntry)`.
    func setPlanEntry(_ input: Operations.SetPlanEntry.Input) async throws -> Operations.SetPlanEntry.Output
    /// Remove the plan entry (or entries) for a date and slot
    ///
    /// For breakfast/lunch/dinner this removes the one entry. For snack this removes every snack entry for that date.
    ///
    /// - Remark: HTTP `DELETE /plan/{date}/{slot}`.
    /// - Remark: Generated from `#/paths//plan/{date}/{slot}/delete(deletePlanEntry)`.
    func deletePlanEntry(_ input: Operations.DeletePlanEntry.Input) async throws -> Operations.DeletePlanEntry.Output
    /// List the caller's shopping lists
    ///
    /// Cursor-paginated, newest first. Lists only the caller's own lists (the partner's shared ones are at `GET /partner/shopping-lists`). Does not include items; fetch a single list for those.
    ///
    /// - Remark: HTTP `GET /shopping-lists`.
    /// - Remark: Generated from `#/paths//shopping-lists/get(listShoppingLists)`.
    func listShoppingLists(_ input: Operations.ListShoppingLists.Input) async throws -> Operations.ListShoppingLists.Output
    /// Create an empty shopping list
    ///
    /// Creates a list with no items and no source date range. Add items with `POST /shopping-lists/{id}/items`, or use `POST /shopping-lists/generate` to build one from the plan.
    ///
    /// - Remark: HTTP `POST /shopping-lists`.
    /// - Remark: Generated from `#/paths//shopping-lists/post(createShoppingList)`.
    func createShoppingList(_ input: Operations.CreateShoppingList.Input) async throws -> Operations.CreateShoppingList.Output
    /// Generate a shopping list from the plan
    ///
    /// Sums the ingredients of every plan entry in [from, to] inclusive (capped at 92 days), merging lines of the same ingredient, and groups them by category. Without `list_id` this creates a new list (201). With `list_id` it regenerates that list (200), replacing every `generated` item, keeping every `manual` item untouched, and updating its source range.
    ///
    /// - Remark: HTTP `POST /shopping-lists/generate`.
    /// - Remark: Generated from `#/paths//shopping-lists/generate/post(generateShoppingList)`.
    func generateShoppingList(_ input: Operations.GenerateShoppingList.Input) async throws -> Operations.GenerateShoppingList.Output
    /// Get a shopping list
    ///
    /// Includes every item, ordered by position. Returns the caller's own list, or a list the partner has shared (`is_owner` false). Any other list is `404`. Renaming, deleting, sharing and regenerating are owner-only (`404` for the partner); the partner may add, edit, check and delete items, and open the event stream.
    ///
    /// - Remark: HTTP `GET /shopping-lists/{id}`.
    /// - Remark: Generated from `#/paths//shopping-lists/{id}/get(getShoppingList)`.
    func getShoppingList(_ input: Operations.GetShoppingList.Input) async throws -> Operations.GetShoppingList.Output
    /// Update a shopping list
    ///
    /// Fields that are absent are left unchanged.
    ///
    /// - Remark: HTTP `PATCH /shopping-lists/{id}`.
    /// - Remark: Generated from `#/paths//shopping-lists/{id}/patch(updateShoppingList)`.
    func updateShoppingList(_ input: Operations.UpdateShoppingList.Input) async throws -> Operations.UpdateShoppingList.Output
    /// Delete a shopping list
    ///
    /// Deletes the list and all of its items. Open event streams for the list receive a final `list_deleted` event and are closed.
    ///
    /// - Remark: HTTP `DELETE /shopping-lists/{id}`.
    /// - Remark: Generated from `#/paths//shopping-lists/{id}/delete(deleteShoppingList)`.
    func deleteShoppingList(_ input: Operations.DeleteShoppingList.Input) async throws -> Operations.DeleteShoppingList.Output
    /// Add an item to a shopping list
    ///
    /// Adds a `manual` item at the end of the list. With `ingredient_id`, the ingredient must be visible to the caller, and `category` defaults to the ingredient's category; without it, `category` defaults to `other`.
    ///
    /// - Remark: HTTP `POST /shopping-lists/{id}/items`.
    /// - Remark: Generated from `#/paths//shopping-lists/{id}/items/post(createShoppingItem)`.
    func createShoppingItem(_ input: Operations.CreateShoppingItem.Input) async throws -> Operations.CreateShoppingItem.Output
    /// Edit or check off a shopping item
    ///
    /// Fields that are absent are left unchanged. Changing `name`, `quantity`, `unit` or `category` requires `version`, which must equal the item's current version, or the request fails with `409 version_conflict` carrying the current item in `current`. A request that changes only `checked` is last-write-wins and does not need `version`; setting `checked` to the value it already has is a no-op that returns the item unchanged. Every change increments `version`.
    ///
    /// - Remark: HTTP `PATCH /shopping-lists/{id}/items/{item_id}`.
    /// - Remark: Generated from `#/paths//shopping-lists/{id}/items/{item_id}/patch(updateShoppingItem)`.
    func updateShoppingItem(_ input: Operations.UpdateShoppingItem.Input) async throws -> Operations.UpdateShoppingItem.Output
    /// Remove an item from a shopping list
    ///
    /// Removes the item regardless of its version (removes merge, per the sync rules).
    ///
    /// - Remark: HTTP `DELETE /shopping-lists/{id}/items/{item_id}`.
    /// - Remark: Generated from `#/paths//shopping-lists/{id}/items/{item_id}/delete(deleteShoppingItem)`.
    func deleteShoppingItem(_ input: Operations.DeleteShoppingItem.Input) async throws -> Operations.DeleteShoppingItem.Output
    /// Stream live changes to a shopping list
    ///
    /// A Server-Sent Events stream. Each event's `event:` field is its type and its `data:` field is one JSON object `{"type", "list_id", "item_id"?, "version"?}`. `item_changed` and `item_deleted` carry `item_id` and the item's `version` (for `item_deleted`, the version the item had when it was removed); `list_changed` (renamed or regenerated) and `list_deleted` carry only `type` and `list_id`. After `list_deleted` the server closes the stream. Comment lines (`: keep-alive`) are sent every 25 seconds. The server may also close the stream at any time (shutdown, or a client too slow to keep up); clients reconnect and refetch the list, and refetch whenever they see a version gap. Events for the same item can arrive out of order; a client should ignore an event whose `version` is less than or equal to the version it already has for that item. Authenticate with the `Authorization` header like every other route: access tokens are never accepted in the query string.
    ///
    ///
    /// - Remark: HTTP `GET /shopping-lists/{id}/events`.
    /// - Remark: Generated from `#/paths//shopping-lists/{id}/events/get(streamShoppingListEvents)`.
    func streamShoppingListEvents(_ input: Operations.StreamShoppingListEvents.Input) async throws -> Operations.StreamShoppingListEvents.Output
    /// Get the caller's partnership
    ///
    /// Returns the active partnership (the partner's `display_name` and `linked_at`), or the caller's own pending invite (`expires_at`; the code is never returned again). `404 partner_not_linked` when there is neither, and also once a pending invite has expired.
    ///
    /// - Remark: HTTP `GET /partner`.
    /// - Remark: Generated from `#/paths//partner/get(getPartner)`.
    func getPartner(_ input: Operations.GetPartner.Input) async throws -> Operations.GetPartner.Output
    /// End the partnership or cancel a pending invite
    ///
    /// Either side may unlink. Access ends at once, so the former partner's next read of shared meals, diet templates and shopping lists is `404`, and their open shopping-list event streams are closed. Every list, meal and template stays with its owner; copies are independent. Re-linking needs a fresh invite.
    ///
    /// - Remark: HTTP `DELETE /partner`.
    /// - Remark: Generated from `#/paths//partner/delete(unlinkPartner)`.
    func unlinkPartner(_ input: Operations.UnlinkPartner.Input) async throws -> Operations.UnlinkPartner.Output
    /// Create an invite code
    ///
    /// Creates an invite for the caller and returns its code, which is shown only here (only its hash is stored). The code has 8 characters from `23456789ABCDEFGHJKMNPQRSTUVWXYZ` and expires after 48 hours. A new invite replaces the caller's pending one. `409 partner_already_linked` if the caller already has a partner.
    ///
    /// - Remark: HTTP `POST /partner/invite`.
    /// - Remark: Generated from `#/paths//partner/invite/post(createPartnerInvite)`.
    func createPartnerInvite(_ input: Operations.CreatePartnerInvite.Input) async throws -> Operations.CreatePartnerInvite.Output
    /// Accept an invite code
    ///
    /// Links the caller with the user who issued the code. A wrong, expired, own or already used code all return the same `404 invite_invalid`. A caller who already has a partner gets `409 partner_already_linked` whatever the code. Case, spaces and dashes in the code do not matter. This route has its own, tighter rate limit (per user and per client IP).
    ///
    /// - Remark: HTTP `POST /partner/accept`.
    /// - Remark: Generated from `#/paths//partner/accept/post(acceptPartnerInvite)`.
    func acceptPartnerInvite(_ input: Operations.AcceptPartnerInvite.Input) async throws -> Operations.AcceptPartnerInvite.Output
    /// List the meals the partner has shared
    ///
    /// Cursor-paginated, alphabetical by name, like `GET /meals`, but only the meals the partner has marked `shared_with_partner`, never the caller's own. Open one with `GET /meals/{id}` (`is_owner` is false) or copy it with `POST /meals/{id}/copy`. `404 partner_not_linked` without an active partner.
    ///
    /// - Remark: HTTP `GET /partner/meals`.
    /// - Remark: Generated from `#/paths//partner/meals/get(listPartnerMeals)`.
    func listPartnerMeals(_ input: Operations.ListPartnerMeals.Input) async throws -> Operations.ListPartnerMeals.Output
    /// List the diet templates the partner has shared
    ///
    /// Cursor-paginated, alphabetical by name, like `GET /diet-templates`, but only the templates the partner has marked `shared_with_partner`, never the caller's own. Open one with `GET /diet-templates/{id}` (`is_owner` is false) or copy it with `POST /diet-templates/{id}/copy`, which copies its meals too. `404 partner_not_linked` without an active partner.
    ///
    /// - Remark: HTTP `GET /partner/diet-templates`.
    /// - Remark: Generated from `#/paths//partner/diet-templates/get(listPartnerDietTemplates)`.
    func listPartnerDietTemplates(_ input: Operations.ListPartnerDietTemplates.Input) async throws -> Operations.ListPartnerDietTemplates.Output
    /// List the shopping lists the partner has shared
    ///
    /// Cursor-paginated, newest first, like `GET /shopping-lists`, but only the lists the partner has marked `shared_with_partner`, never the caller's own. Open one with `GET /shopping-lists/{id}` (`is_owner` is false); both partners may edit its items. `404 partner_not_linked` without an active partner.
    ///
    /// - Remark: HTTP `GET /partner/shopping-lists`.
    /// - Remark: Generated from `#/paths//partner/shopping-lists/get(listPartnerShoppingLists)`.
    func listPartnerShoppingLists(_ input: Operations.ListPartnerShoppingLists.Input) async throws -> Operations.ListPartnerShoppingLists.Output
    /// Liveness probe
    ///
    /// Returns 200 when the process is up. Does not touch the database.
    ///
    /// - Remark: HTTP `GET /healthz`.
    /// - Remark: Generated from `#/paths//healthz/get(getHealth)`.
    func getHealth(_ input: Operations.GetHealth.Input) async throws -> Operations.GetHealth.Output
    /// Readiness probe
    ///
    /// Returns 200 when the service can reach its database, 503 otherwise.
    ///
    /// - Remark: HTTP `GET /readyz`.
    /// - Remark: Generated from `#/paths//readyz/get(getReady)`.
    func getReady(_ input: Operations.GetReady.Input) async throws -> Operations.GetReady.Output
    /// Create an account
    ///
    /// Creates an account with email and password and signs the user in.
    ///
    /// - Remark: HTTP `POST /auth/register`.
    /// - Remark: Generated from `#/paths//auth/register/post(registerUser)`.
    func registerUser(_ input: Operations.RegisterUser.Input) async throws -> Operations.RegisterUser.Output
    /// Sign in with email and password
    ///
    /// - Remark: HTTP `POST /auth/login`.
    /// - Remark: Generated from `#/paths//auth/login/post(loginUser)`.
    func loginUser(_ input: Operations.LoginUser.Input) async throws -> Operations.LoginUser.Output
    /// Exchange a refresh token for a new token pair
    ///
    /// Rotates the refresh token. Presenting an already-used refresh token revokes the whole session family.
    ///
    /// - Remark: HTTP `POST /auth/refresh`.
    /// - Remark: Generated from `#/paths//auth/refresh/post(refreshSession)`.
    func refreshSession(_ input: Operations.RefreshSession.Input) async throws -> Operations.RefreshSession.Output
    /// Revoke a refresh-token session
    ///
    /// Idempotent. An unknown or already-revoked token is not an error.
    ///
    /// - Remark: HTTP `POST /auth/logout`.
    /// - Remark: Generated from `#/paths//auth/logout/post(logoutUser)`.
    func logoutUser(_ input: Operations.LogoutUser.Input) async throws -> Operations.LogoutUser.Output
    /// Get the signed-in user's profile
    ///
    /// - Remark: HTTP `GET /me`.
    /// - Remark: Generated from `#/paths//me/get(getMe)`.
    func getMe(_ input: Operations.GetMe.Input) async throws -> Operations.GetMe.Output
    /// Update the signed-in user's profile
    ///
    /// Fields that are absent are left unchanged. A daily target set to null is cleared.
    ///
    /// - Remark: HTTP `PATCH /me`.
    /// - Remark: Generated from `#/paths//me/patch(updateMe)`.
    func updateMe(_ input: Operations.UpdateMe.Input) async throws -> Operations.UpdateMe.Output
    /// Delete the signed-in user's account
    ///
    /// Permanently deletes the account and everything it owns.
    ///
    /// - Remark: HTTP `DELETE /me`.
    /// - Remark: Generated from `#/paths//me/delete(deleteMe)`.
    func deleteMe(_ input: Operations.DeleteMe.Input) async throws -> Operations.DeleteMe.Output
}

/// Convenience overloads for operation inputs.
extension APIProtocol {
    /// List or search ingredients
    ///
    /// Without `q`, lists ingredients alphabetically with cursor pagination. With `q`, searches by name and returns the best matches, not paginated.
    ///
    /// - Remark: HTTP `GET /ingredients`.
    /// - Remark: Generated from `#/paths//ingredients/get(listIngredients)`.
    public func listIngredients(
        query: Operations.ListIngredients.Input.Query = .init(),
        headers: Operations.ListIngredients.Input.Headers = .init()
    ) async throws -> Operations.ListIngredients.Output {
        try await listIngredients(Operations.ListIngredients.Input(
            query: query,
            headers: headers
        ))
    }
    /// Create a custom ingredient
    ///
    /// - Remark: HTTP `POST /ingredients`.
    /// - Remark: Generated from `#/paths//ingredients/post(createIngredient)`.
    public func createIngredient(
        headers: Operations.CreateIngredient.Input.Headers = .init(),
        body: Operations.CreateIngredient.Input.Body
    ) async throws -> Operations.CreateIngredient.Output {
        try await createIngredient(Operations.CreateIngredient.Input(
            headers: headers,
            body: body
        ))
    }
    /// Update a custom ingredient
    ///
    /// Fields that are absent are left unchanged. Only a custom ingredient owned by the caller can be updated. Clearing `grams_per_piece` or `density_g_per_ml` while a meal still uses this ingredient with the `piece` or `ml` unit is rejected (`409 unit_not_convertible`).
    ///
    /// - Remark: HTTP `PATCH /ingredients/{id}`.
    /// - Remark: Generated from `#/paths//ingredients/{id}/patch(updateIngredient)`.
    public func updateIngredient(
        path: Operations.UpdateIngredient.Input.Path,
        headers: Operations.UpdateIngredient.Input.Headers = .init(),
        body: Operations.UpdateIngredient.Input.Body
    ) async throws -> Operations.UpdateIngredient.Output {
        try await updateIngredient(Operations.UpdateIngredient.Input(
            path: path,
            headers: headers,
            body: body
        ))
    }
    /// Delete a custom ingredient
    ///
    /// - Remark: HTTP `DELETE /ingredients/{id}`.
    /// - Remark: Generated from `#/paths//ingredients/{id}/delete(deleteIngredient)`.
    public func deleteIngredient(
        path: Operations.DeleteIngredient.Input.Path,
        headers: Operations.DeleteIngredient.Input.Headers = .init()
    ) async throws -> Operations.DeleteIngredient.Output {
        try await deleteIngredient(Operations.DeleteIngredient.Input(
            path: path,
            headers: headers
        ))
    }
    /// List the caller's diet templates
    ///
    /// Cursor-paginated, alphabetical by name. Lists only the caller's own templates (the partner's shared ones are at `GET /partner/diet-templates`). Does not include slots; fetch a single template for those.
    ///
    /// - Remark: HTTP `GET /diet-templates`.
    /// - Remark: Generated from `#/paths//diet-templates/get(listDietTemplates)`.
    public func listDietTemplates(
        query: Operations.ListDietTemplates.Input.Query = .init(),
        headers: Operations.ListDietTemplates.Input.Headers = .init()
    ) async throws -> Operations.ListDietTemplates.Output {
        try await listDietTemplates(Operations.ListDietTemplates.Input(
            query: query,
            headers: headers
        ))
    }
    /// Create a diet template
    ///
    /// Creates the template with no slots. Add slots with `PUT /diet-templates/{id}/slots`.
    ///
    /// - Remark: HTTP `POST /diet-templates`.
    /// - Remark: Generated from `#/paths//diet-templates/post(createDietTemplate)`.
    public func createDietTemplate(
        headers: Operations.CreateDietTemplate.Input.Headers = .init(),
        body: Operations.CreateDietTemplate.Input.Body
    ) async throws -> Operations.CreateDietTemplate.Output {
        try await createDietTemplate(Operations.CreateDietTemplate.Input(
            headers: headers,
            body: body
        ))
    }
    /// Get a diet template
    ///
    /// Includes the slot list. Returns the caller's own template, or a template the partner has shared (`is_owner` false), whose slots show each meal's id and name even if that meal is not shared itself (its detail stays `404`). Any other template is `404`.
    ///
    /// - Remark: HTTP `GET /diet-templates/{id}`.
    /// - Remark: Generated from `#/paths//diet-templates/{id}/get(getDietTemplate)`.
    public func getDietTemplate(
        path: Operations.GetDietTemplate.Input.Path,
        headers: Operations.GetDietTemplate.Input.Headers = .init()
    ) async throws -> Operations.GetDietTemplate.Output {
        try await getDietTemplate(Operations.GetDietTemplate.Input(
            path: path,
            headers: headers
        ))
    }
    /// Update a diet template
    ///
    /// Fields that are absent are left unchanged. day_count cannot be changed after creation; recreate or copy the template instead.
    ///
    /// - Remark: HTTP `PATCH /diet-templates/{id}`.
    /// - Remark: Generated from `#/paths//diet-templates/{id}/patch(updateDietTemplate)`.
    public func updateDietTemplate(
        path: Operations.UpdateDietTemplate.Input.Path,
        headers: Operations.UpdateDietTemplate.Input.Headers = .init(),
        body: Operations.UpdateDietTemplate.Input.Body
    ) async throws -> Operations.UpdateDietTemplate.Output {
        try await updateDietTemplate(Operations.UpdateDietTemplate.Input(
            path: path,
            headers: headers,
            body: body
        ))
    }
    /// Delete a diet template
    ///
    /// Any plan entries created by applying this template keep their row, with from_template_id set to null.
    ///
    /// - Remark: HTTP `DELETE /diet-templates/{id}`.
    /// - Remark: Generated from `#/paths//diet-templates/{id}/delete(deleteDietTemplate)`.
    public func deleteDietTemplate(
        path: Operations.DeleteDietTemplate.Input.Path,
        headers: Operations.DeleteDietTemplate.Input.Headers = .init()
    ) async throws -> Operations.DeleteDietTemplate.Output {
        try await deleteDietTemplate(Operations.DeleteDietTemplate.Input(
            path: path,
            headers: headers
        ))
    }
    /// Replace a diet template's slot list
    ///
    /// Atomically replaces the full slot list. Every row is validated (day_index must be within the template's day_count, and the meal must exist and be visible to the caller) before anything is written; an empty `items` array clears the list.
    ///
    /// - Remark: HTTP `PUT /diet-templates/{id}/slots`.
    /// - Remark: Generated from `#/paths//diet-templates/{id}/slots/put(replaceTemplateSlots)`.
    public func replaceTemplateSlots(
        path: Operations.ReplaceTemplateSlots.Input.Path,
        headers: Operations.ReplaceTemplateSlots.Input.Headers = .init(),
        body: Operations.ReplaceTemplateSlots.Input.Body
    ) async throws -> Operations.ReplaceTemplateSlots.Output {
        try await replaceTemplateSlots(Operations.ReplaceTemplateSlots.Input(
            path: path,
            headers: headers,
            body: body
        ))
    }
    /// Apply a template to the plan
    ///
    /// Copies the template's slots into plan entries starting at `start_date`. Without `overwrite`, fails if any non-snack target date+slot already has an entry; snack slots are always added. With `overwrite`, the same non-snack targets are replaced.
    ///
    /// - Remark: HTTP `POST /diet-templates/{id}/apply`.
    /// - Remark: Generated from `#/paths//diet-templates/{id}/apply/post(applyDietTemplate)`.
    public func applyDietTemplate(
        path: Operations.ApplyDietTemplate.Input.Path,
        headers: Operations.ApplyDietTemplate.Input.Headers = .init(),
        body: Operations.ApplyDietTemplate.Input.Body
    ) async throws -> Operations.ApplyDietTemplate.Output {
        try await applyDietTemplate(Operations.ApplyDietTemplate.Input(
            path: path,
            headers: headers,
            body: body
        ))
    }
    /// Copy a diet template
    ///
    /// Creates a new template, owned by the caller, with the same name, day_count and slots. The original may be the caller's own or one the partner has shared. Copying the partner's template also copies its meals (each once, with the same ingredient rules as `POST /meals/{id}/copy`), so the copy can be applied to the caller's own plan. The copy always starts with `shared_with_partner` false.
    ///
    /// - Remark: HTTP `POST /diet-templates/{id}/copy`.
    /// - Remark: Generated from `#/paths//diet-templates/{id}/copy/post(copyDietTemplate)`.
    public func copyDietTemplate(
        path: Operations.CopyDietTemplate.Input.Path,
        headers: Operations.CopyDietTemplate.Input.Headers = .init()
    ) async throws -> Operations.CopyDietTemplate.Output {
        try await copyDietTemplate(Operations.CopyDietTemplate.Input(
            path: path,
            headers: headers
        ))
    }
    /// List the caller's meals
    ///
    /// Cursor-paginated, alphabetical by name. Lists only the caller's own meals (the partner's shared ones are at `GET /partner/meals`). Does not include ingredients or computed nutrition; fetch a single meal for those.
    ///
    /// - Remark: HTTP `GET /meals`.
    /// - Remark: Generated from `#/paths//meals/get(listMeals)`.
    public func listMeals(
        query: Operations.ListMeals.Input.Query = .init(),
        headers: Operations.ListMeals.Input.Headers = .init()
    ) async throws -> Operations.ListMeals.Output {
        try await listMeals(Operations.ListMeals.Input(
            query: query,
            headers: headers
        ))
    }
    /// Create a meal
    ///
    /// Creates the meal with an empty ingredient list. Add ingredients with `PUT /meals/{id}/ingredients`.
    ///
    /// - Remark: HTTP `POST /meals`.
    /// - Remark: Generated from `#/paths//meals/post(createMeal)`.
    public func createMeal(
        headers: Operations.CreateMeal.Input.Headers = .init(),
        body: Operations.CreateMeal.Input.Body
    ) async throws -> Operations.CreateMeal.Output {
        try await createMeal(Operations.CreateMeal.Input(
            headers: headers,
            body: body
        ))
    }
    /// Get a meal
    ///
    /// Includes the ingredient list and nutrition per serving, computed on read. Returns the caller's own meal, or a meal the partner has shared (`is_owner` false). Any other meal is `404`.
    ///
    /// - Remark: HTTP `GET /meals/{id}`.
    /// - Remark: Generated from `#/paths//meals/{id}/get(getMeal)`.
    public func getMeal(
        path: Operations.GetMeal.Input.Path,
        headers: Operations.GetMeal.Input.Headers = .init()
    ) async throws -> Operations.GetMeal.Output {
        try await getMeal(Operations.GetMeal.Input(
            path: path,
            headers: headers
        ))
    }
    /// Update a meal
    ///
    /// Fields that are absent are left unchanged. Only the owner can update a meal; for anyone else, including the partner, it is `404`.
    ///
    /// - Remark: HTTP `PATCH /meals/{id}`.
    /// - Remark: Generated from `#/paths//meals/{id}/patch(updateMeal)`.
    public func updateMeal(
        path: Operations.UpdateMeal.Input.Path,
        headers: Operations.UpdateMeal.Input.Headers = .init(),
        body: Operations.UpdateMeal.Input.Body
    ) async throws -> Operations.UpdateMeal.Output {
        try await updateMeal(Operations.UpdateMeal.Input(
            path: path,
            headers: headers,
            body: body
        ))
    }
    /// Delete a meal
    ///
    /// - Remark: HTTP `DELETE /meals/{id}`.
    /// - Remark: Generated from `#/paths//meals/{id}/delete(deleteMeal)`.
    public func deleteMeal(
        path: Operations.DeleteMeal.Input.Path,
        headers: Operations.DeleteMeal.Input.Headers = .init()
    ) async throws -> Operations.DeleteMeal.Output {
        try await deleteMeal(Operations.DeleteMeal.Input(
            path: path,
            headers: headers
        ))
    }
    /// Replace a meal's ingredient list
    ///
    /// Atomically replaces the full ingredient list. Every row is validated (the ingredient must exist and be visible to the caller, and its unit must be convertible) before anything is written; an empty `items` array clears the list.
    ///
    /// - Remark: HTTP `PUT /meals/{id}/ingredients`.
    /// - Remark: Generated from `#/paths//meals/{id}/ingredients/put(replaceMealIngredients)`.
    public func replaceMealIngredients(
        path: Operations.ReplaceMealIngredients.Input.Path,
        headers: Operations.ReplaceMealIngredients.Input.Headers = .init(),
        body: Operations.ReplaceMealIngredients.Input.Body
    ) async throws -> Operations.ReplaceMealIngredients.Output {
        try await replaceMealIngredients(Operations.ReplaceMealIngredients.Input(
            path: path,
            headers: headers,
            body: body
        ))
    }
    /// Copy a meal
    ///
    /// Creates a new meal, owned by the caller, with the same name, notes, servings and ingredients. The original may be the caller's own or one the partner has shared. Copying the partner's meal also copies each custom ingredient it uses into the caller's library (once per copy; global ingredients are shared). The copy always starts with `shared_with_partner` false.
    ///
    /// - Remark: HTTP `POST /meals/{id}/copy`.
    /// - Remark: Generated from `#/paths//meals/{id}/copy/post(copyMeal)`.
    public func copyMeal(
        path: Operations.CopyMeal.Input.Path,
        headers: Operations.CopyMeal.Input.Headers = .init()
    ) async throws -> Operations.CopyMeal.Output {
        try await copyMeal(Operations.CopyMeal.Input(
            path: path,
            headers: headers
        ))
    }
    /// Get the plan for a date range
    ///
    /// One DailyTotal per calendar date in [from, to] inclusive, with nutrition computed from each entry's meal and compared against the caller's targets. Capped at 92 days.
    ///
    /// - Remark: HTTP `GET /plan`.
    /// - Remark: Generated from `#/paths//plan/get(getPlan)`.
    public func getPlan(
        query: Operations.GetPlan.Input.Query,
        headers: Operations.GetPlan.Input.Headers = .init()
    ) async throws -> Operations.GetPlan.Output {
        try await getPlan(Operations.GetPlan.Input(
            query: query,
            headers: headers
        ))
    }
    /// Set or swap the meal for a date and slot
    ///
    /// For breakfast/lunch/dinner this upserts the one entry for that date+slot. For snack, since the URL can't select among several, this always adds a new entry. Either way, the written entry's from_template_id is null.
    ///
    /// - Remark: HTTP `PUT /plan/{date}/{slot}`.
    /// - Remark: Generated from `#/paths//plan/{date}/{slot}/put(setPlanEntry)`.
    public func setPlanEntry(
        path: Operations.SetPlanEntry.Input.Path,
        headers: Operations.SetPlanEntry.Input.Headers = .init(),
        body: Operations.SetPlanEntry.Input.Body
    ) async throws -> Operations.SetPlanEntry.Output {
        try await setPlanEntry(Operations.SetPlanEntry.Input(
            path: path,
            headers: headers,
            body: body
        ))
    }
    /// Remove the plan entry (or entries) for a date and slot
    ///
    /// For breakfast/lunch/dinner this removes the one entry. For snack this removes every snack entry for that date.
    ///
    /// - Remark: HTTP `DELETE /plan/{date}/{slot}`.
    /// - Remark: Generated from `#/paths//plan/{date}/{slot}/delete(deletePlanEntry)`.
    public func deletePlanEntry(
        path: Operations.DeletePlanEntry.Input.Path,
        headers: Operations.DeletePlanEntry.Input.Headers = .init()
    ) async throws -> Operations.DeletePlanEntry.Output {
        try await deletePlanEntry(Operations.DeletePlanEntry.Input(
            path: path,
            headers: headers
        ))
    }
    /// List the caller's shopping lists
    ///
    /// Cursor-paginated, newest first. Lists only the caller's own lists (the partner's shared ones are at `GET /partner/shopping-lists`). Does not include items; fetch a single list for those.
    ///
    /// - Remark: HTTP `GET /shopping-lists`.
    /// - Remark: Generated from `#/paths//shopping-lists/get(listShoppingLists)`.
    public func listShoppingLists(
        query: Operations.ListShoppingLists.Input.Query = .init(),
        headers: Operations.ListShoppingLists.Input.Headers = .init()
    ) async throws -> Operations.ListShoppingLists.Output {
        try await listShoppingLists(Operations.ListShoppingLists.Input(
            query: query,
            headers: headers
        ))
    }
    /// Create an empty shopping list
    ///
    /// Creates a list with no items and no source date range. Add items with `POST /shopping-lists/{id}/items`, or use `POST /shopping-lists/generate` to build one from the plan.
    ///
    /// - Remark: HTTP `POST /shopping-lists`.
    /// - Remark: Generated from `#/paths//shopping-lists/post(createShoppingList)`.
    public func createShoppingList(
        headers: Operations.CreateShoppingList.Input.Headers = .init(),
        body: Operations.CreateShoppingList.Input.Body
    ) async throws -> Operations.CreateShoppingList.Output {
        try await createShoppingList(Operations.CreateShoppingList.Input(
            headers: headers,
            body: body
        ))
    }
    /// Generate a shopping list from the plan
    ///
    /// Sums the ingredients of every plan entry in [from, to] inclusive (capped at 92 days), merging lines of the same ingredient, and groups them by category. Without `list_id` this creates a new list (201). With `list_id` it regenerates that list (200), replacing every `generated` item, keeping every `manual` item untouched, and updating its source range.
    ///
    /// - Remark: HTTP `POST /shopping-lists/generate`.
    /// - Remark: Generated from `#/paths//shopping-lists/generate/post(generateShoppingList)`.
    public func generateShoppingList(
        headers: Operations.GenerateShoppingList.Input.Headers = .init(),
        body: Operations.GenerateShoppingList.Input.Body
    ) async throws -> Operations.GenerateShoppingList.Output {
        try await generateShoppingList(Operations.GenerateShoppingList.Input(
            headers: headers,
            body: body
        ))
    }
    /// Get a shopping list
    ///
    /// Includes every item, ordered by position. Returns the caller's own list, or a list the partner has shared (`is_owner` false). Any other list is `404`. Renaming, deleting, sharing and regenerating are owner-only (`404` for the partner); the partner may add, edit, check and delete items, and open the event stream.
    ///
    /// - Remark: HTTP `GET /shopping-lists/{id}`.
    /// - Remark: Generated from `#/paths//shopping-lists/{id}/get(getShoppingList)`.
    public func getShoppingList(
        path: Operations.GetShoppingList.Input.Path,
        headers: Operations.GetShoppingList.Input.Headers = .init()
    ) async throws -> Operations.GetShoppingList.Output {
        try await getShoppingList(Operations.GetShoppingList.Input(
            path: path,
            headers: headers
        ))
    }
    /// Update a shopping list
    ///
    /// Fields that are absent are left unchanged.
    ///
    /// - Remark: HTTP `PATCH /shopping-lists/{id}`.
    /// - Remark: Generated from `#/paths//shopping-lists/{id}/patch(updateShoppingList)`.
    public func updateShoppingList(
        path: Operations.UpdateShoppingList.Input.Path,
        headers: Operations.UpdateShoppingList.Input.Headers = .init(),
        body: Operations.UpdateShoppingList.Input.Body
    ) async throws -> Operations.UpdateShoppingList.Output {
        try await updateShoppingList(Operations.UpdateShoppingList.Input(
            path: path,
            headers: headers,
            body: body
        ))
    }
    /// Delete a shopping list
    ///
    /// Deletes the list and all of its items. Open event streams for the list receive a final `list_deleted` event and are closed.
    ///
    /// - Remark: HTTP `DELETE /shopping-lists/{id}`.
    /// - Remark: Generated from `#/paths//shopping-lists/{id}/delete(deleteShoppingList)`.
    public func deleteShoppingList(
        path: Operations.DeleteShoppingList.Input.Path,
        headers: Operations.DeleteShoppingList.Input.Headers = .init()
    ) async throws -> Operations.DeleteShoppingList.Output {
        try await deleteShoppingList(Operations.DeleteShoppingList.Input(
            path: path,
            headers: headers
        ))
    }
    /// Add an item to a shopping list
    ///
    /// Adds a `manual` item at the end of the list. With `ingredient_id`, the ingredient must be visible to the caller, and `category` defaults to the ingredient's category; without it, `category` defaults to `other`.
    ///
    /// - Remark: HTTP `POST /shopping-lists/{id}/items`.
    /// - Remark: Generated from `#/paths//shopping-lists/{id}/items/post(createShoppingItem)`.
    public func createShoppingItem(
        path: Operations.CreateShoppingItem.Input.Path,
        headers: Operations.CreateShoppingItem.Input.Headers = .init(),
        body: Operations.CreateShoppingItem.Input.Body
    ) async throws -> Operations.CreateShoppingItem.Output {
        try await createShoppingItem(Operations.CreateShoppingItem.Input(
            path: path,
            headers: headers,
            body: body
        ))
    }
    /// Edit or check off a shopping item
    ///
    /// Fields that are absent are left unchanged. Changing `name`, `quantity`, `unit` or `category` requires `version`, which must equal the item's current version, or the request fails with `409 version_conflict` carrying the current item in `current`. A request that changes only `checked` is last-write-wins and does not need `version`; setting `checked` to the value it already has is a no-op that returns the item unchanged. Every change increments `version`.
    ///
    /// - Remark: HTTP `PATCH /shopping-lists/{id}/items/{item_id}`.
    /// - Remark: Generated from `#/paths//shopping-lists/{id}/items/{item_id}/patch(updateShoppingItem)`.
    public func updateShoppingItem(
        path: Operations.UpdateShoppingItem.Input.Path,
        headers: Operations.UpdateShoppingItem.Input.Headers = .init(),
        body: Operations.UpdateShoppingItem.Input.Body
    ) async throws -> Operations.UpdateShoppingItem.Output {
        try await updateShoppingItem(Operations.UpdateShoppingItem.Input(
            path: path,
            headers: headers,
            body: body
        ))
    }
    /// Remove an item from a shopping list
    ///
    /// Removes the item regardless of its version (removes merge, per the sync rules).
    ///
    /// - Remark: HTTP `DELETE /shopping-lists/{id}/items/{item_id}`.
    /// - Remark: Generated from `#/paths//shopping-lists/{id}/items/{item_id}/delete(deleteShoppingItem)`.
    public func deleteShoppingItem(
        path: Operations.DeleteShoppingItem.Input.Path,
        headers: Operations.DeleteShoppingItem.Input.Headers = .init()
    ) async throws -> Operations.DeleteShoppingItem.Output {
        try await deleteShoppingItem(Operations.DeleteShoppingItem.Input(
            path: path,
            headers: headers
        ))
    }
    /// Stream live changes to a shopping list
    ///
    /// A Server-Sent Events stream. Each event's `event:` field is its type and its `data:` field is one JSON object `{"type", "list_id", "item_id"?, "version"?}`. `item_changed` and `item_deleted` carry `item_id` and the item's `version` (for `item_deleted`, the version the item had when it was removed); `list_changed` (renamed or regenerated) and `list_deleted` carry only `type` and `list_id`. After `list_deleted` the server closes the stream. Comment lines (`: keep-alive`) are sent every 25 seconds. The server may also close the stream at any time (shutdown, or a client too slow to keep up); clients reconnect and refetch the list, and refetch whenever they see a version gap. Events for the same item can arrive out of order; a client should ignore an event whose `version` is less than or equal to the version it already has for that item. Authenticate with the `Authorization` header like every other route: access tokens are never accepted in the query string.
    ///
    ///
    /// - Remark: HTTP `GET /shopping-lists/{id}/events`.
    /// - Remark: Generated from `#/paths//shopping-lists/{id}/events/get(streamShoppingListEvents)`.
    public func streamShoppingListEvents(
        path: Operations.StreamShoppingListEvents.Input.Path,
        headers: Operations.StreamShoppingListEvents.Input.Headers = .init()
    ) async throws -> Operations.StreamShoppingListEvents.Output {
        try await streamShoppingListEvents(Operations.StreamShoppingListEvents.Input(
            path: path,
            headers: headers
        ))
    }
    /// Get the caller's partnership
    ///
    /// Returns the active partnership (the partner's `display_name` and `linked_at`), or the caller's own pending invite (`expires_at`; the code is never returned again). `404 partner_not_linked` when there is neither, and also once a pending invite has expired.
    ///
    /// - Remark: HTTP `GET /partner`.
    /// - Remark: Generated from `#/paths//partner/get(getPartner)`.
    public func getPartner(headers: Operations.GetPartner.Input.Headers = .init()) async throws -> Operations.GetPartner.Output {
        try await getPartner(Operations.GetPartner.Input(headers: headers))
    }
    /// End the partnership or cancel a pending invite
    ///
    /// Either side may unlink. Access ends at once, so the former partner's next read of shared meals, diet templates and shopping lists is `404`, and their open shopping-list event streams are closed. Every list, meal and template stays with its owner; copies are independent. Re-linking needs a fresh invite.
    ///
    /// - Remark: HTTP `DELETE /partner`.
    /// - Remark: Generated from `#/paths//partner/delete(unlinkPartner)`.
    public func unlinkPartner(headers: Operations.UnlinkPartner.Input.Headers = .init()) async throws -> Operations.UnlinkPartner.Output {
        try await unlinkPartner(Operations.UnlinkPartner.Input(headers: headers))
    }
    /// Create an invite code
    ///
    /// Creates an invite for the caller and returns its code, which is shown only here (only its hash is stored). The code has 8 characters from `23456789ABCDEFGHJKMNPQRSTUVWXYZ` and expires after 48 hours. A new invite replaces the caller's pending one. `409 partner_already_linked` if the caller already has a partner.
    ///
    /// - Remark: HTTP `POST /partner/invite`.
    /// - Remark: Generated from `#/paths//partner/invite/post(createPartnerInvite)`.
    public func createPartnerInvite(headers: Operations.CreatePartnerInvite.Input.Headers = .init()) async throws -> Operations.CreatePartnerInvite.Output {
        try await createPartnerInvite(Operations.CreatePartnerInvite.Input(headers: headers))
    }
    /// Accept an invite code
    ///
    /// Links the caller with the user who issued the code. A wrong, expired, own or already used code all return the same `404 invite_invalid`. A caller who already has a partner gets `409 partner_already_linked` whatever the code. Case, spaces and dashes in the code do not matter. This route has its own, tighter rate limit (per user and per client IP).
    ///
    /// - Remark: HTTP `POST /partner/accept`.
    /// - Remark: Generated from `#/paths//partner/accept/post(acceptPartnerInvite)`.
    public func acceptPartnerInvite(
        headers: Operations.AcceptPartnerInvite.Input.Headers = .init(),
        body: Operations.AcceptPartnerInvite.Input.Body
    ) async throws -> Operations.AcceptPartnerInvite.Output {
        try await acceptPartnerInvite(Operations.AcceptPartnerInvite.Input(
            headers: headers,
            body: body
        ))
    }
    /// List the meals the partner has shared
    ///
    /// Cursor-paginated, alphabetical by name, like `GET /meals`, but only the meals the partner has marked `shared_with_partner`, never the caller's own. Open one with `GET /meals/{id}` (`is_owner` is false) or copy it with `POST /meals/{id}/copy`. `404 partner_not_linked` without an active partner.
    ///
    /// - Remark: HTTP `GET /partner/meals`.
    /// - Remark: Generated from `#/paths//partner/meals/get(listPartnerMeals)`.
    public func listPartnerMeals(
        query: Operations.ListPartnerMeals.Input.Query = .init(),
        headers: Operations.ListPartnerMeals.Input.Headers = .init()
    ) async throws -> Operations.ListPartnerMeals.Output {
        try await listPartnerMeals(Operations.ListPartnerMeals.Input(
            query: query,
            headers: headers
        ))
    }
    /// List the diet templates the partner has shared
    ///
    /// Cursor-paginated, alphabetical by name, like `GET /diet-templates`, but only the templates the partner has marked `shared_with_partner`, never the caller's own. Open one with `GET /diet-templates/{id}` (`is_owner` is false) or copy it with `POST /diet-templates/{id}/copy`, which copies its meals too. `404 partner_not_linked` without an active partner.
    ///
    /// - Remark: HTTP `GET /partner/diet-templates`.
    /// - Remark: Generated from `#/paths//partner/diet-templates/get(listPartnerDietTemplates)`.
    public func listPartnerDietTemplates(
        query: Operations.ListPartnerDietTemplates.Input.Query = .init(),
        headers: Operations.ListPartnerDietTemplates.Input.Headers = .init()
    ) async throws -> Operations.ListPartnerDietTemplates.Output {
        try await listPartnerDietTemplates(Operations.ListPartnerDietTemplates.Input(
            query: query,
            headers: headers
        ))
    }
    /// List the shopping lists the partner has shared
    ///
    /// Cursor-paginated, newest first, like `GET /shopping-lists`, but only the lists the partner has marked `shared_with_partner`, never the caller's own. Open one with `GET /shopping-lists/{id}` (`is_owner` is false); both partners may edit its items. `404 partner_not_linked` without an active partner.
    ///
    /// - Remark: HTTP `GET /partner/shopping-lists`.
    /// - Remark: Generated from `#/paths//partner/shopping-lists/get(listPartnerShoppingLists)`.
    public func listPartnerShoppingLists(
        query: Operations.ListPartnerShoppingLists.Input.Query = .init(),
        headers: Operations.ListPartnerShoppingLists.Input.Headers = .init()
    ) async throws -> Operations.ListPartnerShoppingLists.Output {
        try await listPartnerShoppingLists(Operations.ListPartnerShoppingLists.Input(
            query: query,
            headers: headers
        ))
    }
    /// Liveness probe
    ///
    /// Returns 200 when the process is up. Does not touch the database.
    ///
    /// - Remark: HTTP `GET /healthz`.
    /// - Remark: Generated from `#/paths//healthz/get(getHealth)`.
    public func getHealth(headers: Operations.GetHealth.Input.Headers = .init()) async throws -> Operations.GetHealth.Output {
        try await getHealth(Operations.GetHealth.Input(headers: headers))
    }
    /// Readiness probe
    ///
    /// Returns 200 when the service can reach its database, 503 otherwise.
    ///
    /// - Remark: HTTP `GET /readyz`.
    /// - Remark: Generated from `#/paths//readyz/get(getReady)`.
    public func getReady(headers: Operations.GetReady.Input.Headers = .init()) async throws -> Operations.GetReady.Output {
        try await getReady(Operations.GetReady.Input(headers: headers))
    }
    /// Create an account
    ///
    /// Creates an account with email and password and signs the user in.
    ///
    /// - Remark: HTTP `POST /auth/register`.
    /// - Remark: Generated from `#/paths//auth/register/post(registerUser)`.
    public func registerUser(
        headers: Operations.RegisterUser.Input.Headers = .init(),
        body: Operations.RegisterUser.Input.Body
    ) async throws -> Operations.RegisterUser.Output {
        try await registerUser(Operations.RegisterUser.Input(
            headers: headers,
            body: body
        ))
    }
    /// Sign in with email and password
    ///
    /// - Remark: HTTP `POST /auth/login`.
    /// - Remark: Generated from `#/paths//auth/login/post(loginUser)`.
    public func loginUser(
        headers: Operations.LoginUser.Input.Headers = .init(),
        body: Operations.LoginUser.Input.Body
    ) async throws -> Operations.LoginUser.Output {
        try await loginUser(Operations.LoginUser.Input(
            headers: headers,
            body: body
        ))
    }
    /// Exchange a refresh token for a new token pair
    ///
    /// Rotates the refresh token. Presenting an already-used refresh token revokes the whole session family.
    ///
    /// - Remark: HTTP `POST /auth/refresh`.
    /// - Remark: Generated from `#/paths//auth/refresh/post(refreshSession)`.
    public func refreshSession(
        headers: Operations.RefreshSession.Input.Headers = .init(),
        body: Operations.RefreshSession.Input.Body
    ) async throws -> Operations.RefreshSession.Output {
        try await refreshSession(Operations.RefreshSession.Input(
            headers: headers,
            body: body
        ))
    }
    /// Revoke a refresh-token session
    ///
    /// Idempotent. An unknown or already-revoked token is not an error.
    ///
    /// - Remark: HTTP `POST /auth/logout`.
    /// - Remark: Generated from `#/paths//auth/logout/post(logoutUser)`.
    public func logoutUser(
        headers: Operations.LogoutUser.Input.Headers = .init(),
        body: Operations.LogoutUser.Input.Body
    ) async throws -> Operations.LogoutUser.Output {
        try await logoutUser(Operations.LogoutUser.Input(
            headers: headers,
            body: body
        ))
    }
    /// Get the signed-in user's profile
    ///
    /// - Remark: HTTP `GET /me`.
    /// - Remark: Generated from `#/paths//me/get(getMe)`.
    public func getMe(headers: Operations.GetMe.Input.Headers = .init()) async throws -> Operations.GetMe.Output {
        try await getMe(Operations.GetMe.Input(headers: headers))
    }
    /// Update the signed-in user's profile
    ///
    /// Fields that are absent are left unchanged. A daily target set to null is cleared.
    ///
    /// - Remark: HTTP `PATCH /me`.
    /// - Remark: Generated from `#/paths//me/patch(updateMe)`.
    public func updateMe(
        headers: Operations.UpdateMe.Input.Headers = .init(),
        body: Operations.UpdateMe.Input.Body
    ) async throws -> Operations.UpdateMe.Output {
        try await updateMe(Operations.UpdateMe.Input(
            headers: headers,
            body: body
        ))
    }
    /// Delete the signed-in user's account
    ///
    /// Permanently deletes the account and everything it owns.
    ///
    /// - Remark: HTTP `DELETE /me`.
    /// - Remark: Generated from `#/paths//me/delete(deleteMe)`.
    public func deleteMe(headers: Operations.DeleteMe.Input.Headers = .init()) async throws -> Operations.DeleteMe.Output {
        try await deleteMe(Operations.DeleteMe.Input(headers: headers))
    }
}

/// Server URLs defined in the OpenAPI document.
public enum Servers {
    /// Local development
    public enum Server1 {
        /// Local development
        public static func url() throws -> Foundation.URL {
            try Foundation.URL(
                validatingOpenAPIServerURL: "http://localhost:8080/v1",
                variables: []
            )
        }
    }
    /// Local development
    @available(*, deprecated, renamed: "Servers.Server1.url")
    public static func server1() throws -> Foundation.URL {
        try Foundation.URL(
            validatingOpenAPIServerURL: "http://localhost:8080/v1",
            variables: []
        )
    }
}
