// Generated by swift-openapi-generator, do not modify.
@_spi(Generated) public import OpenAPIRuntime
#if os(Linux)
@preconcurrency public import struct Foundation.URL
@preconcurrency public import struct Foundation.Data
@preconcurrency public import struct Foundation.Date
#else
public import struct Foundation.URL
public import struct Foundation.Data
public import struct Foundation.Date
#endif
extension Components {
    /// Types generated from the `#/components/responses` section of the OpenAPI document.
    public enum Responses {
        public struct Problem: Sendable, Hashable {
            /// - Remark: Generated from `#/components/responses/Problem/content`.
            @frozen public enum Body: Sendable, Hashable {
                /// - Remark: Generated from `#/components/responses/Problem/content/application\/problem+json`.
                case applicationProblemJson(Components.Schemas.Problem)
                /// The associated value of the enum case if `self` is `.applicationProblemJson`.
                ///
                /// - Throws: An error if `self` is not `.applicationProblemJson`.
                /// - SeeAlso: `.applicationProblemJson`.
                public var applicationProblemJson: Components.Schemas.Problem {
                    get throws {
                        switch self {
                        case let .applicationProblemJson(body):
                            return body
                        }
                    }
                }
            }
            /// Received HTTP response body
            public var body: Components.Responses.Problem.Body
            /// Creates a new `Problem`.
            ///
            /// - Parameters:
            ///   - body: Received HTTP response body
            public init(body: Components.Responses.Problem.Body) {
                self.body = body
            }
        }
        public struct BadRequest: Sendable, Hashable {
            /// - Remark: Generated from `#/components/responses/BadRequest/content`.
            @frozen public enum Body: Sendable, Hashable {
                /// - Remark: Generated from `#/components/responses/BadRequest/content/application\/problem+json`.
                case applicationProblemJson(Components.Schemas.Problem)
                /// The associated value of the enum case if `self` is `.applicationProblemJson`.
                ///
                /// - Throws: An error if `self` is not `.applicationProblemJson`.
                /// - SeeAlso: `.applicationProblemJson`.
                public var applicationProblemJson: Components.Schemas.Problem {
                    get throws {
                        switch self {
                        case let .applicationProblemJson(body):
                            return body
                        }
                    }
                }
            }
            /// Received HTTP response body
            public var body: Components.Responses.BadRequest.Body
            /// Creates a new `BadRequest`.
            ///
            /// - Parameters:
            ///   - body: Received HTTP response body
            public init(body: Components.Responses.BadRequest.Body) {
                self.body = body
            }
        }
        public struct Unauthorized: Sendable, Hashable {
            /// - Remark: Generated from `#/components/responses/Unauthorized/headers`.
            public struct Headers: Sendable, Hashable {
                /// - Remark: Generated from `#/components/responses/Unauthorized/headers/WWW-Authenticate`.
                public var wwwAuthenticate: Swift.String?
                /// Creates a new `Headers`.
                ///
                /// - Parameters:
                ///   - wwwAuthenticate:
                public init(wwwAuthenticate: Swift.String? = nil) {
                    self.wwwAuthenticate = wwwAuthenticate
                }
            }
            /// Received HTTP response headers
            public var headers: Components.Responses.Unauthorized.Headers
            /// - Remark: Generated from `#/components/responses/Unauthorized/content`.
            @frozen public enum Body: Sendable, Hashable {
                /// - Remark: Generated from `#/components/responses/Unauthorized/content/application\/problem+json`.
                case applicationProblemJson(Components.Schemas.Problem)
                /// The associated value of the enum case if `self` is `.applicationProblemJson`.
                ///
                /// - Throws: An error if `self` is not `.applicationProblemJson`.
                /// - SeeAlso: `.applicationProblemJson`.
                public var applicationProblemJson: Components.Schemas.Problem {
                    get throws {
                        switch self {
                        case let .applicationProblemJson(body):
                            return body
                        }
                    }
                }
            }
            /// Received HTTP response body
            public var body: Components.Responses.Unauthorized.Body
            /// Creates a new `Unauthorized`.
            ///
            /// - Parameters:
            ///   - headers: Received HTTP response headers
            ///   - body: Received HTTP response body
            public init(
                headers: Components.Responses.Unauthorized.Headers = .init(),
                body: Components.Responses.Unauthorized.Body
            ) {
                self.headers = headers
                self.body = body
            }
        }
        public struct NotFound: Sendable, Hashable {
            /// - Remark: Generated from `#/components/responses/NotFound/content`.
            @frozen public enum Body: Sendable, Hashable {
                /// - Remark: Generated from `#/components/responses/NotFound/content/application\/problem+json`.
                case applicationProblemJson(Components.Schemas.Problem)
                /// The associated value of the enum case if `self` is `.applicationProblemJson`.
                ///
                /// - Throws: An error if `self` is not `.applicationProblemJson`.
                /// - SeeAlso: `.applicationProblemJson`.
                public var applicationProblemJson: Components.Schemas.Problem {
                    get throws {
                        switch self {
                        case let .applicationProblemJson(body):
                            return body
                        }
                    }
                }
            }
            /// Received HTTP response body
            public var body: Components.Responses.NotFound.Body
            /// Creates a new `NotFound`.
            ///
            /// - Parameters:
            ///   - body: Received HTTP response body
            public init(body: Components.Responses.NotFound.Body) {
                self.body = body
            }
        }
        public struct Conflict: Sendable, Hashable {
            /// - Remark: Generated from `#/components/responses/Conflict/content`.
            @frozen public enum Body: Sendable, Hashable {
                /// - Remark: Generated from `#/components/responses/Conflict/content/application\/problem+json`.
                case applicationProblemJson(Components.Schemas.Problem)
                /// The associated value of the enum case if `self` is `.applicationProblemJson`.
                ///
                /// - Throws: An error if `self` is not `.applicationProblemJson`.
                /// - SeeAlso: `.applicationProblemJson`.
                public var applicationProblemJson: Components.Schemas.Problem {
                    get throws {
                        switch self {
                        case let .applicationProblemJson(body):
                            return body
                        }
                    }
                }
            }
            /// Received HTTP response body
            public var body: Components.Responses.Conflict.Body
            /// Creates a new `Conflict`.
            ///
            /// - Parameters:
            ///   - body: Received HTTP response body
            public init(body: Components.Responses.Conflict.Body) {
                self.body = body
            }
        }
        public struct TooManyRequests: Sendable, Hashable {
            /// - Remark: Generated from `#/components/responses/TooManyRequests/headers`.
            public struct Headers: Sendable, Hashable {
                /// - Remark: Generated from `#/components/responses/TooManyRequests/headers/Retry-After`.
                public var retryAfter: Swift.Int?
                /// Creates a new `Headers`.
                ///
                /// - Parameters:
                ///   - retryAfter:
                public init(retryAfter: Swift.Int? = nil) {
                    self.retryAfter = retryAfter
                }
            }
            /// Received HTTP response headers
            public var headers: Components.Responses.TooManyRequests.Headers
            /// - Remark: Generated from `#/components/responses/TooManyRequests/content`.
            @frozen public enum Body: Sendable, Hashable {
                /// - Remark: Generated from `#/components/responses/TooManyRequests/content/application\/problem+json`.
                case applicationProblemJson(Components.Schemas.Problem)
                /// The associated value of the enum case if `self` is `.applicationProblemJson`.
                ///
                /// - Throws: An error if `self` is not `.applicationProblemJson`.
                /// - SeeAlso: `.applicationProblemJson`.
                public var applicationProblemJson: Components.Schemas.Problem {
                    get throws {
                        switch self {
                        case let .applicationProblemJson(body):
                            return body
                        }
                    }
                }
            }
            /// Received HTTP response body
            public var body: Components.Responses.TooManyRequests.Body
            /// Creates a new `TooManyRequests`.
            ///
            /// - Parameters:
            ///   - headers: Received HTTP response headers
            ///   - body: Received HTTP response body
            public init(
                headers: Components.Responses.TooManyRequests.Headers = .init(),
                body: Components.Responses.TooManyRequests.Body
            ) {
                self.headers = headers
                self.body = body
            }
        }
    }
}
