// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: diet_templates.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createDietTemplate = `-- name: CreateDietTemplate :one
INSERT INTO diet_templates (owner_id, name, day_count, shared_with_partner)
VALUES ($1, $2, $3, $4)
RETURNING id, owner_id, name, day_count, shared_with_partner, created_at, updated_at
`

type CreateDietTemplateParams struct {
	OwnerID           uuid.UUID
	Name              string
	DayCount          int32
	SharedWithPartner bool
}

func (q *Queries) CreateDietTemplate(ctx context.Context, arg CreateDietTemplateParams) (DietTemplate, error) {
	row := q.db.QueryRow(ctx, createDietTemplate,
		arg.OwnerID,
		arg.Name,
		arg.DayCount,
		arg.SharedWithPartner,
	)
	var i DietTemplate
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.DayCount,
		&i.SharedWithPartner,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDietTemplate = `-- name: DeleteDietTemplate :execrows
DELETE FROM diet_templates WHERE id = $1 AND owner_id = $2
`

type DeleteDietTemplateParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteDietTemplate(ctx context.Context, arg DeleteDietTemplateParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteDietTemplate, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteDietTemplatesForUser = `-- name: DeleteDietTemplatesForUser :exec
DELETE FROM diet_templates WHERE owner_id = $1
`

// Used by Auth.DeleteUser (Task 4), ahead of deleting the user row.
func (q *Queries) DeleteDietTemplatesForUser(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteDietTemplatesForUser, userID)
	return err
}

const deleteTemplateSlots = `-- name: DeleteTemplateSlots :exec
DELETE FROM template_slots WHERE template_id = $1
`

func (q *Queries) DeleteTemplateSlots(ctx context.Context, templateID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteTemplateSlots, templateID)
	return err
}

const getDietTemplateForUser = `-- name: GetDietTemplateForUser :one
SELECT id, owner_id, name, day_count, shared_with_partner, created_at, updated_at FROM diet_templates
WHERE id = $1
  AND (
    owner_id = $2
    OR (owner_id = $3::uuid AND shared_with_partner)
  )
`

type GetDietTemplateForUserParams struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	PartnerID *uuid.UUID
}

// The read predicate (spec §5): the caller's own template, or one the
// caller's active partner has shared. partner_id is NULL when the caller has
// no partner (or wants owner-only access, as Apply does), which makes the
// second branch match nothing. Every write keeps the strict owner-only
// queries.
func (q *Queries) GetDietTemplateForUser(ctx context.Context, arg GetDietTemplateForUserParams) (DietTemplate, error) {
	row := q.db.QueryRow(ctx, getDietTemplateForUser, arg.ID, arg.UserID, arg.PartnerID)
	var i DietTemplate
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.DayCount,
		&i.SharedWithPartner,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTemplateSlots = `-- name: GetTemplateSlots :many
SELECT id, template_id, day_index, slot, meal_id, portion FROM template_slots
WHERE template_id = $1
ORDER BY day_index, array_position(ARRAY['breakfast', 'lunch', 'dinner', 'snack'], slot), id
`

// Ordered by meal-time position (breakfast, lunch, dinner, snack), not
// plain text ("slot" would sort dinner before lunch). template_slots has no
// timestamps (see backend/CLAUDE.md's line-item-table exception), so id is
// the tiebreak for same-day, same-slot rows (only possible for snack, which
// allows several per day).
func (q *Queries) GetTemplateSlots(ctx context.Context, templateID uuid.UUID) ([]TemplateSlot, error) {
	rows, err := q.db.Query(ctx, getTemplateSlots, templateID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TemplateSlot
	for rows.Next() {
		var i TemplateSlot
		if err := rows.Scan(
			&i.ID,
			&i.TemplateID,
			&i.DayIndex,
			&i.Slot,
			&i.MealID,
			&i.Portion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertTemplateSlot = `-- name: InsertTemplateSlot :one
INSERT INTO template_slots (template_id, day_index, slot, meal_id, portion)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, template_id, day_index, slot, meal_id, portion
`

type InsertTemplateSlotParams struct {
	TemplateID uuid.UUID
	DayIndex   int32
	Slot       string
	MealID     uuid.UUID
	Portion    float64
}

func (q *Queries) InsertTemplateSlot(ctx context.Context, arg InsertTemplateSlotParams) (TemplateSlot, error) {
	row := q.db.QueryRow(ctx, insertTemplateSlot,
		arg.TemplateID,
		arg.DayIndex,
		arg.Slot,
		arg.MealID,
		arg.Portion,
	)
	var i TemplateSlot
	err := row.Scan(
		&i.ID,
		&i.TemplateID,
		&i.DayIndex,
		&i.Slot,
		&i.MealID,
		&i.Portion,
	)
	return i, err
}

const listDietTemplatesForUser = `-- name: ListDietTemplatesForUser :many
SELECT id, owner_id, name, day_count, shared_with_partner, created_at, updated_at FROM diet_templates
WHERE owner_id = $1
  AND (NOT $2::boolean OR shared_with_partner)
  AND (
    NOT $3::boolean
    OR name > $4::text
    OR (name = $4::text AND id > $5::uuid)
  )
ORDER BY name, id
LIMIT $6
`

type ListDietTemplatesForUserParams struct {
	UserID     uuid.UUID
	SharedOnly bool
	HasCursor  bool
	CursorName string
	CursorID   uuid.UUID
	RowLimit   int32
}

// shared_only is for GET partner/diet-templates: user_id is then the partner's
// id and only what the partner has shared comes back.
func (q *Queries) ListDietTemplatesForUser(ctx context.Context, arg ListDietTemplatesForUserParams) ([]DietTemplate, error) {
	rows, err := q.db.Query(ctx, listDietTemplatesForUser,
		arg.UserID,
		arg.SharedOnly,
		arg.HasCursor,
		arg.CursorName,
		arg.CursorID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DietTemplate
	for rows.Next() {
		var i DietTemplate
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.DayCount,
			&i.SharedWithPartner,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchDietTemplateForUser = `-- name: TouchDietTemplateForUser :one
UPDATE diet_templates SET updated_at = now()
WHERE id = $1 AND owner_id = $2
RETURNING id, owner_id, name, day_count, shared_with_partner, created_at, updated_at
`

type TouchDietTemplateForUserParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

// Bumps updated_at (via the diet_templates_set_updated_at trigger) and, just
// as importantly, takes the row's write lock: ReplaceSlots uses this instead
// of a plain SELECT so two concurrent slot replaces on the same template
// serialize instead of racing the DELETE+INSERT below it. See ReplaceSlots
// in internal/service/diet_templates.go, and TouchMealForUser in
// meals.sql for the same fix in the meals domain.
func (q *Queries) TouchDietTemplateForUser(ctx context.Context, arg TouchDietTemplateForUserParams) (DietTemplate, error) {
	row := q.db.QueryRow(ctx, touchDietTemplateForUser, arg.ID, arg.UserID)
	var i DietTemplate
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.DayCount,
		&i.SharedWithPartner,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateDietTemplate = `-- name: UpdateDietTemplate :one
UPDATE diet_templates SET
    name                = COALESCE($1, name),
    shared_with_partner = COALESCE($2, shared_with_partner)
WHERE id = $3 AND owner_id = $4
RETURNING id, owner_id, name, day_count, shared_with_partner, created_at, updated_at
`

type UpdateDietTemplateParams struct {
	Name              *string
	SharedWithPartner *bool
	ID                uuid.UUID
	UserID            uuid.UUID
}

// day_count is immutable after creation (see Global Constraints), so it has
// no place in this UPDATE.
func (q *Queries) UpdateDietTemplate(ctx context.Context, arg UpdateDietTemplateParams) (DietTemplate, error) {
	row := q.db.QueryRow(ctx, updateDietTemplate,
		arg.Name,
		arg.SharedWithPartner,
		arg.ID,
		arg.UserID,
	)
	var i DietTemplate
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.DayCount,
		&i.SharedWithPartner,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
