// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ingredients.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createIngredient = `-- name: CreateIngredient :one
INSERT INTO ingredients (name, category, owner_id, grams_per_piece, density_g_per_ml)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, category, owner_id, usda_fdc_id, grams_per_piece, density_g_per_ml, created_at, updated_at
`

type CreateIngredientParams struct {
	Name          string
	Category      string
	OwnerID       *uuid.UUID
	GramsPerPiece *float64
	DensityGPerMl *float64
}

func (q *Queries) CreateIngredient(ctx context.Context, arg CreateIngredientParams) (Ingredient, error) {
	row := q.db.QueryRow(ctx, createIngredient,
		arg.Name,
		arg.Category,
		arg.OwnerID,
		arg.GramsPerPiece,
		arg.DensityGPerMl,
	)
	var i Ingredient
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Category,
		&i.OwnerID,
		&i.UsdaFdcID,
		&i.GramsPerPiece,
		&i.DensityGPerMl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteIngredient = `-- name: DeleteIngredient :execrows
DELETE FROM ingredients WHERE id = $1 AND owner_id = $2
`

type DeleteIngredientParams struct {
	ID     uuid.UUID
	UserID *uuid.UUID
}

// Deleting an ingredient referenced by a meal_ingredients row fails with a
// foreign-key violation on meal_ingredients_ingredient_id_fkey, which
// Ingredients.Delete (internal/service/ingredients.go) translates into
// ErrIngredientInUse.
func (q *Queries) DeleteIngredient(ctx context.Context, arg DeleteIngredientParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteIngredient, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getIngredientForUser = `-- name: GetIngredientForUser :one
SELECT id, name, category, owner_id, usda_fdc_id, grams_per_piece, density_g_per_ml, created_at, updated_at FROM ingredients
WHERE id = $1 AND (owner_id IS NULL OR owner_id = $2)
`

type GetIngredientForUserParams struct {
	ID     uuid.UUID
	UserID *uuid.UUID
}

func (q *Queries) GetIngredientForUser(ctx context.Context, arg GetIngredientForUserParams) (Ingredient, error) {
	row := q.db.QueryRow(ctx, getIngredientForUser, arg.ID, arg.UserID)
	var i Ingredient
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Category,
		&i.OwnerID,
		&i.UsdaFdcID,
		&i.GramsPerPiece,
		&i.DensityGPerMl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getIngredientNutrients = `-- name: GetIngredientNutrients :many
SELECT ingredient_id, nutrient_key, amount_per_100g FROM ingredient_nutrients WHERE ingredient_id = ANY($1::uuid[])
`

func (q *Queries) GetIngredientNutrients(ctx context.Context, ingredientIds []uuid.UUID) ([]IngredientNutrient, error) {
	rows, err := q.db.Query(ctx, getIngredientNutrients, ingredientIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IngredientNutrient
	for rows.Next() {
		var i IngredientNutrient
		if err := rows.Scan(&i.IngredientID, &i.NutrientKey, &i.AmountPer100g); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getIngredientsForUser = `-- name: GetIngredientsForUser :many
SELECT id, name, category, owner_id, usda_fdc_id, grams_per_piece, density_g_per_ml, created_at, updated_at FROM ingredients
WHERE id = ANY($1::uuid[]) AND (owner_id IS NULL OR owner_id = $2)
`

type GetIngredientsForUserParams struct {
	Ids    []uuid.UUID
	UserID *uuid.UUID
}

func (q *Queries) GetIngredientsForUser(ctx context.Context, arg GetIngredientsForUserParams) ([]Ingredient, error) {
	rows, err := q.db.Query(ctx, getIngredientsForUser, arg.Ids, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ingredient
	for rows.Next() {
		var i Ingredient
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Category,
			&i.OwnerID,
			&i.UsdaFdcID,
			&i.GramsPerPiece,
			&i.DensityGPerMl,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIngredients = `-- name: ListIngredients :many
SELECT id, name, category, owner_id, usda_fdc_id, grams_per_piece, density_g_per_ml, created_at, updated_at FROM ingredients
WHERE (owner_id IS NULL OR owner_id = $1)
  AND ($2::text IS NULL OR category = $2)
  AND (
    NOT $3::boolean
    OR name > $4::text
    OR (name = $4::text AND id > $5::uuid)
  )
ORDER BY name, id
LIMIT $6
`

type ListIngredientsParams struct {
	UserID     *uuid.UUID
	Category   *string
	HasCursor  bool
	CursorName string
	CursorID   uuid.UUID
	RowLimit   int32
}

func (q *Queries) ListIngredients(ctx context.Context, arg ListIngredientsParams) ([]Ingredient, error) {
	rows, err := q.db.Query(ctx, listIngredients,
		arg.UserID,
		arg.Category,
		arg.HasCursor,
		arg.CursorName,
		arg.CursorID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ingredient
	for rows.Next() {
		var i Ingredient
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Category,
			&i.OwnerID,
			&i.UsdaFdcID,
			&i.GramsPerPiece,
			&i.DensityGPerMl,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const replaceIngredientNutrients = `-- name: ReplaceIngredientNutrients :exec
DELETE FROM ingredient_nutrients WHERE ingredient_id = $1
`

func (q *Queries) ReplaceIngredientNutrients(ctx context.Context, ingredientID uuid.UUID) error {
	_, err := q.db.Exec(ctx, replaceIngredientNutrients, ingredientID)
	return err
}

const searchIngredients = `-- name: SearchIngredients :many
SELECT id, name, category, owner_id, usda_fdc_id, grams_per_piece, density_g_per_ml, created_at, updated_at FROM ingredients
WHERE (owner_id IS NULL OR owner_id = $1)
  AND ($2::text IS NULL OR category = $2)
  AND name % $3::text
ORDER BY similarity(name, $3::text) DESC, name
LIMIT $4
`

type SearchIngredientsParams struct {
	UserID   *uuid.UUID
	Category *string
	Query    string
	RowLimit int32
}

func (q *Queries) SearchIngredients(ctx context.Context, arg SearchIngredientsParams) ([]Ingredient, error) {
	rows, err := q.db.Query(ctx, searchIngredients,
		arg.UserID,
		arg.Category,
		arg.Query,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ingredient
	for rows.Next() {
		var i Ingredient
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Category,
			&i.OwnerID,
			&i.UsdaFdcID,
			&i.GramsPerPiece,
			&i.DensityGPerMl,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateIngredient = `-- name: UpdateIngredient :one
UPDATE ingredients SET
    name             = COALESCE($1, name),
    category         = COALESCE($2, category),
    grams_per_piece  = CASE WHEN $3::boolean THEN $4 ELSE grams_per_piece END,
    density_g_per_ml = CASE WHEN $5::boolean THEN $6 ELSE density_g_per_ml END
WHERE id = $7 AND owner_id = $8
RETURNING id, name, category, owner_id, usda_fdc_id, grams_per_piece, density_g_per_ml, created_at, updated_at
`

type UpdateIngredientParams struct {
	Name             *string
	Category         *string
	SetGramsPerPiece bool
	GramsPerPiece    *float64
	SetDensityGPerMl bool
	DensityGPerMl    *float64
	ID               uuid.UUID
	UserID           *uuid.UUID
}

func (q *Queries) UpdateIngredient(ctx context.Context, arg UpdateIngredientParams) (Ingredient, error) {
	row := q.db.QueryRow(ctx, updateIngredient,
		arg.Name,
		arg.Category,
		arg.SetGramsPerPiece,
		arg.GramsPerPiece,
		arg.SetDensityGPerMl,
		arg.DensityGPerMl,
		arg.ID,
		arg.UserID,
	)
	var i Ingredient
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Category,
		&i.OwnerID,
		&i.UsdaFdcID,
		&i.GramsPerPiece,
		&i.DensityGPerMl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertIngredientNutrient = `-- name: UpsertIngredientNutrient :exec
INSERT INTO ingredient_nutrients (ingredient_id, nutrient_key, amount_per_100g)
VALUES ($1, $2, $3)
ON CONFLICT (ingredient_id, nutrient_key) DO UPDATE SET amount_per_100g = EXCLUDED.amount_per_100g
`

type UpsertIngredientNutrientParams struct {
	IngredientID  uuid.UUID
	NutrientKey   NutrientKey
	AmountPer100g float64
}

func (q *Queries) UpsertIngredientNutrient(ctx context.Context, arg UpsertIngredientNutrientParams) error {
	_, err := q.db.Exec(ctx, upsertIngredientNutrient, arg.IngredientID, arg.NutrientKey, arg.AmountPer100g)
	return err
}

const upsertUSDAIngredient = `-- name: UpsertUSDAIngredient :one
INSERT INTO ingredients (name, category, usda_fdc_id)
VALUES ($1, $2, $3)
ON CONFLICT (usda_fdc_id) DO UPDATE SET name = EXCLUDED.name, category = EXCLUDED.category
RETURNING id, name, category, owner_id, usda_fdc_id, grams_per_piece, density_g_per_ml, created_at, updated_at
`

type UpsertUSDAIngredientParams struct {
	Name      string
	Category  string
	UsdaFdcID *int32
}

func (q *Queries) UpsertUSDAIngredient(ctx context.Context, arg UpsertUSDAIngredientParams) (Ingredient, error) {
	row := q.db.QueryRow(ctx, upsertUSDAIngredient, arg.Name, arg.Category, arg.UsdaFdcID)
	var i Ingredient
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Category,
		&i.OwnerID,
		&i.UsdaFdcID,
		&i.GramsPerPiece,
		&i.DensityGPerMl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
