// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: meals.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createMeal = `-- name: CreateMeal :one
INSERT INTO meals (owner_id, name, notes, servings, shared_with_partner)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, owner_id, name, notes, servings, shared_with_partner, created_at, updated_at
`

type CreateMealParams struct {
	OwnerID           uuid.UUID
	Name              string
	Notes             *string
	Servings          float64
	SharedWithPartner bool
}

func (q *Queries) CreateMeal(ctx context.Context, arg CreateMealParams) (Meal, error) {
	row := q.db.QueryRow(ctx, createMeal,
		arg.OwnerID,
		arg.Name,
		arg.Notes,
		arg.Servings,
		arg.SharedWithPartner,
	)
	var i Meal
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Notes,
		&i.Servings,
		&i.SharedWithPartner,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteMeal = `-- name: DeleteMeal :execrows
DELETE FROM meals WHERE id = $1 AND owner_id = $2
`

type DeleteMealParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteMeal(ctx context.Context, arg DeleteMealParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteMeal, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteMealsForUser = `-- name: DeleteMealsForUser :exec
DELETE FROM meals WHERE owner_id = $1
`

// Used by account deletion, before the users row itself goes. users cascades
// to both ingredients and meals, but meal_ingredients.ingredient_id is NO
// ACTION (that is what makes deleting an in-use ingredient a 409), and
// Postgres fires the ingredients cascade first. Clearing the owner's meals up
// front removes the meal_ingredients rows (ON DELETE CASCADE on meal_id) that
// would otherwise block that cascade.
func (q *Queries) DeleteMealsForUser(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteMealsForUser, userID)
	return err
}

const getMealForUser = `-- name: GetMealForUser :one
SELECT id, owner_id, name, notes, servings, shared_with_partner, created_at, updated_at FROM meals
WHERE id = $1
  AND (
    owner_id = $2
    OR (owner_id = $3::uuid AND shared_with_partner)
  )
`

type GetMealForUserParams struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	PartnerID *uuid.UUID
}

// The read predicate (spec §5): the caller's own meal, or one the caller's
// active partner has shared. partner_id is NULL when the caller has no
// partner (or when the caller wants owner-only access), which makes the second
// branch match nothing. Every write keeps the strict owner-only queries.
func (q *Queries) GetMealForUser(ctx context.Context, arg GetMealForUserParams) (Meal, error) {
	row := q.db.QueryRow(ctx, getMealForUser, arg.ID, arg.UserID, arg.PartnerID)
	var i Meal
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Notes,
		&i.Servings,
		&i.SharedWithPartner,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMealIngredients = `-- name: GetMealIngredients :many
SELECT id, meal_id, ingredient_id, quantity, unit, position FROM meal_ingredients WHERE meal_id = $1 ORDER BY position
`

func (q *Queries) GetMealIngredients(ctx context.Context, mealID uuid.UUID) ([]MealIngredient, error) {
	rows, err := q.db.Query(ctx, getMealIngredients, mealID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MealIngredient
	for rows.Next() {
		var i MealIngredient
		if err := rows.Scan(
			&i.ID,
			&i.MealID,
			&i.IngredientID,
			&i.Quantity,
			&i.Unit,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMealIngredientsForMeals = `-- name: GetMealIngredientsForMeals :many
SELECT id, meal_id, ingredient_id, quantity, unit, position FROM meal_ingredients
WHERE meal_id = ANY($1::uuid[])
ORDER BY meal_id, position
`

// The batch counterpart to GetMealIngredients, for ShoppingLists.Generate:
// every ingredient line of every meal scheduled in a date range, in one query.
func (q *Queries) GetMealIngredientsForMeals(ctx context.Context, mealIds []uuid.UUID) ([]MealIngredient, error) {
	rows, err := q.db.Query(ctx, getMealIngredientsForMeals, mealIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MealIngredient
	for rows.Next() {
		var i MealIngredient
		if err := rows.Scan(
			&i.ID,
			&i.MealID,
			&i.IngredientID,
			&i.Quantity,
			&i.Unit,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMealsForUser = `-- name: GetMealsForUser :many
SELECT id, owner_id, name, notes, servings, shared_with_partner, created_at, updated_at FROM meals
WHERE id = ANY($1::uuid[]) AND owner_id = $2
`

type GetMealsForUserParams struct {
	Ids    []uuid.UUID
	UserID uuid.UUID
}

// The batch counterpart to GetMealForUser: given a set of meal ids, returns
// only the ones that exist and are owned by user_id. Used by DietTemplates
// and Plan (Tasks 5, 6) to validate a slot's or entry's meal_id, and by
// DietTemplates.toTemplate to fetch each slot's meal name in one query.
func (q *Queries) GetMealsForUser(ctx context.Context, arg GetMealsForUserParams) ([]Meal, error) {
	rows, err := q.db.Query(ctx, getMealsForUser, arg.Ids, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Meal
	for rows.Next() {
		var i Meal
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.Notes,
			&i.Servings,
			&i.SharedWithPartner,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertMealIngredient = `-- name: InsertMealIngredient :one
INSERT INTO meal_ingredients (meal_id, ingredient_id, quantity, unit, position)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, meal_id, ingredient_id, quantity, unit, position
`

type InsertMealIngredientParams struct {
	MealID       uuid.UUID
	IngredientID uuid.UUID
	Quantity     float64
	Unit         string
	Position     int32
}

func (q *Queries) InsertMealIngredient(ctx context.Context, arg InsertMealIngredientParams) (MealIngredient, error) {
	row := q.db.QueryRow(ctx, insertMealIngredient,
		arg.MealID,
		arg.IngredientID,
		arg.Quantity,
		arg.Unit,
		arg.Position,
	)
	var i MealIngredient
	err := row.Scan(
		&i.ID,
		&i.MealID,
		&i.IngredientID,
		&i.Quantity,
		&i.Unit,
		&i.Position,
	)
	return i, err
}

const listMealsForUser = `-- name: ListMealsForUser :many
SELECT id, owner_id, name, notes, servings, shared_with_partner, created_at, updated_at FROM meals
WHERE owner_id = $1
  AND (NOT $2::boolean OR shared_with_partner)
  AND (
    NOT $3::boolean
    OR name > $4::text
    OR (name = $4::text AND id > $5::uuid)
  )
ORDER BY name, id
LIMIT $6
`

type ListMealsForUserParams struct {
	UserID     uuid.UUID
	SharedOnly bool
	HasCursor  bool
	CursorName string
	CursorID   uuid.UUID
	RowLimit   int32
}

// shared_only is for GET partner/meals: user_id is then the partner's id and
// only what the partner has shared comes back.
func (q *Queries) ListMealsForUser(ctx context.Context, arg ListMealsForUserParams) ([]Meal, error) {
	rows, err := q.db.Query(ctx, listMealsForUser,
		arg.UserID,
		arg.SharedOnly,
		arg.HasCursor,
		arg.CursorName,
		arg.CursorID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Meal
	for rows.Next() {
		var i Meal
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.Notes,
			&i.Servings,
			&i.SharedWithPartner,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const replaceMealIngredients = `-- name: ReplaceMealIngredients :exec
DELETE FROM meal_ingredients WHERE meal_id = $1
`

func (q *Queries) ReplaceMealIngredients(ctx context.Context, mealID uuid.UUID) error {
	_, err := q.db.Exec(ctx, replaceMealIngredients, mealID)
	return err
}

const touchMealForUser = `-- name: TouchMealForUser :one
UPDATE meals SET updated_at = now()
WHERE id = $1 AND owner_id = $2
RETURNING id, owner_id, name, notes, servings, shared_with_partner, created_at, updated_at
`

type TouchMealForUserParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

// Bumps updated_at (via the meals_set_updated_at trigger) and, just as
// importantly, takes the row's write lock: ReplaceIngredients uses this
// instead of a plain SELECT so two concurrent replaces on the same meal
// serialize instead of racing the DELETE+INSERT below it. See
// ReplaceIngredients in internal/service/meals.go.
func (q *Queries) TouchMealForUser(ctx context.Context, arg TouchMealForUserParams) (Meal, error) {
	row := q.db.QueryRow(ctx, touchMealForUser, arg.ID, arg.UserID)
	var i Meal
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Notes,
		&i.Servings,
		&i.SharedWithPartner,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateMeal = `-- name: UpdateMeal :one
UPDATE meals SET
    name                = COALESCE($1, name),
    notes               = CASE WHEN $2::boolean THEN $3 ELSE notes END,
    servings            = COALESCE($4, servings),
    shared_with_partner = COALESCE($5, shared_with_partner)
WHERE id = $6 AND owner_id = $7
RETURNING id, owner_id, name, notes, servings, shared_with_partner, created_at, updated_at
`

type UpdateMealParams struct {
	Name              *string
	SetNotes          bool
	Notes             *string
	Servings          *float64
	SharedWithPartner *bool
	ID                uuid.UUID
	UserID            uuid.UUID
}

func (q *Queries) UpdateMeal(ctx context.Context, arg UpdateMealParams) (Meal, error) {
	row := q.db.QueryRow(ctx, updateMeal,
		arg.Name,
		arg.SetNotes,
		arg.Notes,
		arg.Servings,
		arg.SharedWithPartner,
		arg.ID,
		arg.UserID,
	)
	var i Meal
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Notes,
		&i.Servings,
		&i.SharedWithPartner,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
