// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type NutrientKey string

const (
	NutrientKeyCalories      NutrientKey = "calories"
	NutrientKeyProtein       NutrientKey = "protein"
	NutrientKeyCarbohydrates NutrientKey = "carbohydrates"
	NutrientKeySugar         NutrientKey = "sugar"
	NutrientKeyFibre         NutrientKey = "fibre"
	NutrientKeyFat           NutrientKey = "fat"
	NutrientKeySaturatedFat  NutrientKey = "saturated_fat"
	NutrientKeySodium        NutrientKey = "sodium"
	NutrientKeyPotassium     NutrientKey = "potassium"
	NutrientKeyCalcium       NutrientKey = "calcium"
	NutrientKeyIron          NutrientKey = "iron"
	NutrientKeyMagnesium     NutrientKey = "magnesium"
	NutrientKeyZinc          NutrientKey = "zinc"
	NutrientKeyVitaminA      NutrientKey = "vitamin_a"
	NutrientKeyVitaminC      NutrientKey = "vitamin_c"
	NutrientKeyVitaminD      NutrientKey = "vitamin_d"
	NutrientKeyVitaminB12    NutrientKey = "vitamin_b12"
	NutrientKeyFolate        NutrientKey = "folate"
)

func (e *NutrientKey) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = NutrientKey(s)
	case string:
		*e = NutrientKey(s)
	default:
		return fmt.Errorf("unsupported scan type for NutrientKey: %T", src)
	}
	return nil
}

type NullNutrientKey struct {
	NutrientKey NutrientKey
	Valid       bool // Valid is true if NutrientKey is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullNutrientKey) Scan(value interface{}) error {
	if value == nil {
		ns.NutrientKey, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.NutrientKey.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullNutrientKey) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.NutrientKey), nil
}

type DietTemplate struct {
	ID                uuid.UUID
	OwnerID           uuid.UUID
	Name              string
	DayCount          int32
	SharedWithPartner bool
	CreatedAt         time.Time
	UpdatedAt         time.Time
}

type Ingredient struct {
	ID            uuid.UUID
	Name          string
	Category      string
	OwnerID       *uuid.UUID
	UsdaFdcID     *int32
	GramsPerPiece *float64
	DensityGPerMl *float64
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type IngredientNutrient struct {
	IngredientID  uuid.UUID
	NutrientKey   NutrientKey
	AmountPer100g float64
}

type Meal struct {
	ID                uuid.UUID
	OwnerID           uuid.UUID
	Name              string
	Notes             *string
	Servings          float64
	SharedWithPartner bool
	CreatedAt         time.Time
	UpdatedAt         time.Time
}

type MealIngredient struct {
	ID           uuid.UUID
	MealID       uuid.UUID
	IngredientID uuid.UUID
	Quantity     float64
	Unit         string
	Position     int32
}

type Partnership struct {
	ID              uuid.UUID
	UserA           uuid.UUID
	UserB           *uuid.UUID
	Status          string
	InviteCodeHash  []byte
	InviteExpiresAt *time.Time
	CreatedBy       uuid.UUID
	CreatedAt       time.Time
	UpdatedAt       time.Time
}

type PlanEntry struct {
	ID             uuid.UUID
	OwnerID        uuid.UUID
	Date           pgtype.Date
	Slot           string
	MealID         uuid.UUID
	Portion        float64
	FromTemplateID *uuid.UUID
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type RefreshToken struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	FamilyID  uuid.UUID
	TokenHash []byte
	ExpiresAt time.Time
	RevokedAt *time.Time
	CreatedAt time.Time
	UpdatedAt time.Time
}

type ShoppingItem struct {
	ID           uuid.UUID
	ListID       uuid.UUID
	IngredientID *uuid.UUID
	Name         string
	Quantity     *float64
	Unit         *string
	Category     string
	Checked      bool
	CheckedBy    *uuid.UUID
	Position     int32
	Version      int32
	Origin       string
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type ShoppingList struct {
	ID                uuid.UUID
	OwnerID           uuid.UUID
	Name              string
	SharedWithPartner bool
	SourceFrom        pgtype.Date
	SourceTo          pgtype.Date
	CreatedAt         time.Time
	UpdatedAt         time.Time
}

type TemplateSlot struct {
	ID         uuid.UUID
	TemplateID uuid.UUID
	DayIndex   int32
	Slot       string
	MealID     uuid.UUID
	Portion    float64
}

type User struct {
	ID             uuid.UUID
	Email          string
	PasswordHash   *string
	AppleSub       *string
	DisplayName    string
	TargetKcal     *float64
	TargetProteinG *float64
	TargetCarbsG   *float64
	TargetFatG     *float64
	CreatedAt      time.Time
	UpdatedAt      time.Time
}
