// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"time"

	"github.com/google/uuid"
)

type RefreshToken struct {
	ID        uuid.UUID
	UserID    uuid.UUID
	FamilyID  uuid.UUID
	TokenHash []byte
	ExpiresAt time.Time
	RevokedAt *time.Time
	CreatedAt time.Time
	UpdatedAt time.Time
}

type User struct {
	ID             uuid.UUID
	Email          string
	PasswordHash   *string
	AppleSub       *string
	DisplayName    string
	TargetKcal     *float64
	TargetProteinG *float64
	TargetCarbsG   *float64
	TargetFatG     *float64
	CreatedAt      time.Time
	UpdatedAt      time.Time
}
