// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: partnerships.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const activatePartnership = `-- name: ActivatePartnership :one
UPDATE partnerships SET
    user_b            = $1,
    status            = 'active',
    invite_code_hash  = NULL,
    invite_expires_at = NULL
WHERE id = $2 AND status = 'pending'
RETURNING id, user_a, user_b, status, invite_code_hash, invite_expires_at, created_by, created_at, updated_at
`

type ActivatePartnershipParams struct {
	UserB *uuid.UUID
	ID    uuid.UUID
}

// Turns a pending invite into an active partnership and clears the code, so a
// spent code cannot be replayed. No row means the invite is gone (cancelled,
// replaced or accepted a moment ago).
func (q *Queries) ActivatePartnership(ctx context.Context, arg ActivatePartnershipParams) (Partnership, error) {
	row := q.db.QueryRow(ctx, activatePartnership, arg.UserB, arg.ID)
	var i Partnership
	err := row.Scan(
		&i.ID,
		&i.UserA,
		&i.UserB,
		&i.Status,
		&i.InviteCodeHash,
		&i.InviteExpiresAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPartnerInvite = `-- name: CreatePartnerInvite :one
INSERT INTO partnerships (user_a, status, invite_code_hash, invite_expires_at, created_by)
VALUES ($1, 'pending', $2, $3, $1)
RETURNING id, user_a, user_b, status, invite_code_hash, invite_expires_at, created_by, created_at, updated_at
`

type CreatePartnerInviteParams struct {
	UserID          uuid.UUID
	InviteCodeHash  []byte
	InviteExpiresAt *time.Time
}

func (q *Queries) CreatePartnerInvite(ctx context.Context, arg CreatePartnerInviteParams) (Partnership, error) {
	row := q.db.QueryRow(ctx, createPartnerInvite, arg.UserID, arg.InviteCodeHash, arg.InviteExpiresAt)
	var i Partnership
	err := row.Scan(
		&i.ID,
		&i.UserA,
		&i.UserB,
		&i.Status,
		&i.InviteCodeHash,
		&i.InviteExpiresAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePartnershipsForUser = `-- name: DeletePartnershipsForUser :many
DELETE FROM partnerships
WHERE user_a = $1 OR user_b = $1
RETURNING id, user_a, user_b, status
`

type DeletePartnershipsForUserRow struct {
	ID     uuid.UUID
	UserA  uuid.UUID
	UserB  *uuid.UUID
	Status string
}

// Ends the user's active partnership or cancels their pending invite. Returns
// what was deleted so Partners.Unlink can close the partner's event streams.
func (q *Queries) DeletePartnershipsForUser(ctx context.Context, userID uuid.UUID) ([]DeletePartnershipsForUserRow, error) {
	rows, err := q.db.Query(ctx, deletePartnershipsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DeletePartnershipsForUserRow
	for rows.Next() {
		var i DeletePartnershipsForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserA,
			&i.UserB,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deletePendingPartnershipForUser = `-- name: DeletePendingPartnershipForUser :exec
DELETE FROM partnerships WHERE user_a = $1 AND status = 'pending'
`

func (q *Queries) DeletePendingPartnershipForUser(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePendingPartnershipForUser, userID)
	return err
}

const getActivePartnerID = `-- name: GetActivePartnerID :one
SELECT (CASE WHEN user_a = $1 THEN user_b ELSE user_a END)::uuid AS partner_id
FROM partnerships
WHERE status = 'active' AND (user_a = $1 OR user_b = $1)
`

// The other side of the user's active partnership. store.IsNotFound on the
// error means the user has no active partner.
func (q *Queries) GetActivePartnerID(ctx context.Context, userID uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getActivePartnerID, userID)
	var partner_id uuid.UUID
	err := row.Scan(&partner_id)
	return partner_id, err
}

const getActivePartnerIDForShare = `-- name: GetActivePartnerIDForShare :one
SELECT (CASE WHEN user_a = $1 THEN user_b ELSE user_a END)::uuid AS partner_id
FROM partnerships
WHERE status = 'active' AND (user_a = $1 OR user_b = $1)
FOR SHARE
`

// GetActivePartnerID plus a shared lock on the partnership row. Shopping-item
// writes use it: Partners.Unlink's DELETE waits for the edits in flight, and an
// edit that starts afterwards finds no partner (spec §6, unlink ordering).
func (q *Queries) GetActivePartnerIDForShare(ctx context.Context, userID uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getActivePartnerIDForShare, userID)
	var partner_id uuid.UUID
	err := row.Scan(&partner_id)
	return partner_id, err
}

const getPartnershipForUser = `-- name: GetPartnershipForUser :one
SELECT partnerships.id, partnerships.status, partnerships.invite_expires_at, partnerships.updated_at,
       other.display_name AS partner_display_name
FROM partnerships
LEFT JOIN users AS other
       ON other.id = CASE WHEN partnerships.user_a = $1 THEN partnerships.user_b ELSE partnerships.user_a END
WHERE partnerships.user_a = $1 OR partnerships.user_b = $1
`

type GetPartnershipForUserRow struct {
	ID                 uuid.UUID
	Status             string
	InviteExpiresAt    *time.Time
	UpdatedAt          time.Time
	PartnerDisplayName *string
}

// The user's partnership row (pending or active) with the other side's display
// name, which is NULL while the invite is still pending.
func (q *Queries) GetPartnershipForUser(ctx context.Context, userID uuid.UUID) (GetPartnershipForUserRow, error) {
	row := q.db.QueryRow(ctx, getPartnershipForUser, userID)
	var i GetPartnershipForUserRow
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.InviteExpiresAt,
		&i.UpdatedAt,
		&i.PartnerDisplayName,
	)
	return i, err
}

const getPendingPartnershipByCodeHash = `-- name: GetPendingPartnershipByCodeHash :one
SELECT id, user_a, user_b, status, invite_code_hash, invite_expires_at, created_by, created_at, updated_at FROM partnerships
WHERE status = 'pending' AND invite_code_hash = $1
`

func (q *Queries) GetPendingPartnershipByCodeHash(ctx context.Context, inviteCodeHash []byte) (Partnership, error) {
	row := q.db.QueryRow(ctx, getPendingPartnershipByCodeHash, inviteCodeHash)
	var i Partnership
	err := row.Scan(
		&i.ID,
		&i.UserA,
		&i.UserB,
		&i.Status,
		&i.InviteCodeHash,
		&i.InviteExpiresAt,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lockUsersForUpdate = `-- name: LockUsersForUpdate :many
SELECT id FROM users
WHERE id = ANY($1::uuid[])
ORDER BY id
FOR NO KEY UPDATE
`

// Locks the given users rows in id order, so two transactions that lock the
// same pair cannot deadlock. FOR NO KEY UPDATE conflicts with itself but not
// with the FOR KEY SHARE that inserts of dependent rows take, so it does not
// block a user's other writes. Partners.Invite and Partners.Accept use it to
// serialize their check-then-write over one user.
func (q *Queries) LockUsersForUpdate(ctx context.Context, ids []uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, lockUsersForUpdate, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
