// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: plan_entries.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteAllSnackEntriesForUserOnDate = `-- name: DeleteAllSnackEntriesForUserOnDate :execrows
DELETE FROM plan_entries
WHERE owner_id = $1 AND date = $2 AND slot = 'snack'
`

type DeleteAllSnackEntriesForUserOnDateParams struct {
	UserID uuid.UUID
	Date   pgtype.Date
}

func (q *Queries) DeleteAllSnackEntriesForUserOnDate(ctx context.Context, arg DeleteAllSnackEntriesForUserOnDateParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAllSnackEntriesForUserOnDate, arg.UserID, arg.Date)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deletePlanEntriesForUser = `-- name: DeletePlanEntriesForUser :exec
DELETE FROM plan_entries WHERE owner_id = $1
`

// Used by Auth.DeleteUser (Task 4), ahead of deleting diet_templates and
// meals and the user row.
func (q *Queries) DeletePlanEntriesForUser(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePlanEntriesForUser, userID)
	return err
}

const deletePlanEntryForUserOnDateSlot = `-- name: DeletePlanEntryForUserOnDateSlot :execrows
DELETE FROM plan_entries
WHERE owner_id = $1 AND date = $2 AND slot = $3 AND slot != 'snack'
`

type DeletePlanEntryForUserOnDateSlotParams struct {
	UserID uuid.UUID
	Date   pgtype.Date
	Slot   string
}

// The "AND slot != 'snack'" is a defensive belt: this query must never
// delete a snack row even if called with slot = 'snack' by mistake — the
// service layer routes snack deletes to DeleteAllSnackEntriesForUserOnDate
// instead, but a wrong call here should do nothing rather than something
// wrong. Also used by DietTemplates.Apply's overwrite path to clear the one
// existing non-snack entry at a target date+slot before re-inserting.
func (q *Queries) DeletePlanEntryForUserOnDateSlot(ctx context.Context, arg DeletePlanEntryForUserOnDateSlotParams) (int64, error) {
	result, err := q.db.Exec(ctx, deletePlanEntryForUserOnDateSlot, arg.UserID, arg.Date, arg.Slot)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getPlanEntriesForUserInRange = `-- name: GetPlanEntriesForUserInRange :many
SELECT id, owner_id, date, slot, meal_id, portion, from_template_id, created_at, updated_at FROM plan_entries
WHERE owner_id = $1
  AND date >= $2::date AND date <= $3::date
ORDER BY date, array_position(ARRAY['breakfast', 'lunch', 'dinner', 'snack'], slot), created_at, id
`

type GetPlanEntriesForUserInRangeParams struct {
	UserID   uuid.UUID
	FromDate pgtype.Date
	ToDate   pgtype.Date
}

// Ordered by meal-time position (breakfast, lunch, dinner, snack), not
// plain text ("slot" would sort dinner before lunch). created_at, then id,
// is the tiebreak for same-date, same-slot rows (only possible for snack,
// which allows several per day).
func (q *Queries) GetPlanEntriesForUserInRange(ctx context.Context, arg GetPlanEntriesForUserInRangeParams) ([]PlanEntry, error) {
	rows, err := q.db.Query(ctx, getPlanEntriesForUserInRange, arg.UserID, arg.FromDate, arg.ToDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PlanEntry
	for rows.Next() {
		var i PlanEntry
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Date,
			&i.Slot,
			&i.MealID,
			&i.Portion,
			&i.FromTemplateID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPlanEntriesForUserOnDates = `-- name: GetPlanEntriesForUserOnDates :many
SELECT id, owner_id, date, slot, meal_id, portion, from_template_id, created_at, updated_at FROM plan_entries
WHERE owner_id = $1 AND date = ANY($2::date[])
`

type GetPlanEntriesForUserOnDatesParams struct {
	UserID uuid.UUID
	Dates  []pgtype.Date
}

// Used by DietTemplates.Apply's pre-write conflict check: given the exact
// target dates a template's slots would land on, return every existing
// entry on any of those dates in one query.
func (q *Queries) GetPlanEntriesForUserOnDates(ctx context.Context, arg GetPlanEntriesForUserOnDatesParams) ([]PlanEntry, error) {
	rows, err := q.db.Query(ctx, getPlanEntriesForUserOnDates, arg.UserID, arg.Dates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PlanEntry
	for rows.Next() {
		var i PlanEntry
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Date,
			&i.Slot,
			&i.MealID,
			&i.Portion,
			&i.FromTemplateID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertPlanEntry = `-- name: InsertPlanEntry :one
INSERT INTO plan_entries (owner_id, date, slot, meal_id, portion, from_template_id)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, owner_id, date, slot, meal_id, portion, from_template_id, created_at, updated_at
`

type InsertPlanEntryParams struct {
	OwnerID        uuid.UUID
	Date           pgtype.Date
	Slot           string
	MealID         uuid.UUID
	Portion        float64
	FromTemplateID *uuid.UUID
}

// Always adds a new row. Used for snack (which never upserts) and by
// DietTemplates.Apply (Task 5), which sets from_template_id explicitly.
func (q *Queries) InsertPlanEntry(ctx context.Context, arg InsertPlanEntryParams) (PlanEntry, error) {
	row := q.db.QueryRow(ctx, insertPlanEntry,
		arg.OwnerID,
		arg.Date,
		arg.Slot,
		arg.MealID,
		arg.Portion,
		arg.FromTemplateID,
	)
	var i PlanEntry
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Date,
		&i.Slot,
		&i.MealID,
		&i.Portion,
		&i.FromTemplateID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertPlanEntry = `-- name: UpsertPlanEntry :one
INSERT INTO plan_entries (owner_id, date, slot, meal_id, portion, from_template_id)
VALUES ($1, $2, $3, $4, $5, NULL)
ON CONFLICT (owner_id, date, slot) WHERE slot != 'snack'
DO UPDATE SET meal_id = EXCLUDED.meal_id, portion = EXCLUDED.portion, from_template_id = NULL
RETURNING id, owner_id, date, slot, meal_id, portion, from_template_id, created_at, updated_at
`

type UpsertPlanEntryParams struct {
	OwnerID uuid.UUID
	Date    pgtype.Date
	Slot    string
	MealID  uuid.UUID
	Portion float64
}

// Only for slot != 'snack': the partial unique index (owner_id, date, slot)
// WHERE slot != 'snack' from 00006_diets_and_plan.sql is the ON CONFLICT
// target, so this natively updates the single existing entry for that
// date+slot, or inserts a new one. Always writes from_template_id = NULL: a
// manual upsert is no longer "from" a template, even when it overwrites an
// entry that was (see Global Constraints). Never call this for slot =
// 'snack' — the service layer routes to InsertPlanEntry instead.
func (q *Queries) UpsertPlanEntry(ctx context.Context, arg UpsertPlanEntryParams) (PlanEntry, error) {
	row := q.db.QueryRow(ctx, upsertPlanEntry,
		arg.OwnerID,
		arg.Date,
		arg.Slot,
		arg.MealID,
		arg.Portion,
	)
	var i PlanEntry
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Date,
		&i.Slot,
		&i.MealID,
		&i.Portion,
		&i.FromTemplateID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
