// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: shopping_lists.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createShoppingList = `-- name: CreateShoppingList :one
INSERT INTO shopping_lists (owner_id, name, shared_with_partner, source_from, source_to)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, owner_id, name, shared_with_partner, source_from, source_to, created_at, updated_at
`

type CreateShoppingListParams struct {
	OwnerID           uuid.UUID
	Name              string
	SharedWithPartner bool
	SourceFrom        pgtype.Date
	SourceTo          pgtype.Date
}

func (q *Queries) CreateShoppingList(ctx context.Context, arg CreateShoppingListParams) (ShoppingList, error) {
	row := q.db.QueryRow(ctx, createShoppingList,
		arg.OwnerID,
		arg.Name,
		arg.SharedWithPartner,
		arg.SourceFrom,
		arg.SourceTo,
	)
	var i ShoppingList
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.SharedWithPartner,
		&i.SourceFrom,
		&i.SourceTo,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteGeneratedShoppingItems = `-- name: DeleteGeneratedShoppingItems :exec
DELETE FROM shopping_items WHERE list_id = $1 AND origin = 'generated'
`

func (q *Queries) DeleteGeneratedShoppingItems(ctx context.Context, listID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteGeneratedShoppingItems, listID)
	return err
}

const deleteShoppingItemForUser = `-- name: DeleteShoppingItemForUser :one
DELETE FROM shopping_items
USING shopping_lists
WHERE shopping_items.id = $1
  AND shopping_items.list_id = $2
  AND shopping_lists.id = shopping_items.list_id
  AND shopping_lists.owner_id = $3
RETURNING shopping_items.id, shopping_items.version
`

type DeleteShoppingItemForUserParams struct {
	ID     uuid.UUID
	ListID uuid.UUID
	UserID uuid.UUID
}

type DeleteShoppingItemForUserRow struct {
	ID      uuid.UUID
	Version int32
}

// :one, not :execrows: the deleted item's last version goes into the
// item_deleted event.
func (q *Queries) DeleteShoppingItemForUser(ctx context.Context, arg DeleteShoppingItemForUserParams) (DeleteShoppingItemForUserRow, error) {
	row := q.db.QueryRow(ctx, deleteShoppingItemForUser, arg.ID, arg.ListID, arg.UserID)
	var i DeleteShoppingItemForUserRow
	err := row.Scan(&i.ID, &i.Version)
	return i, err
}

const deleteShoppingList = `-- name: DeleteShoppingList :execrows
DELETE FROM shopping_lists WHERE id = $1 AND owner_id = $2
`

type DeleteShoppingListParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteShoppingList(ctx context.Context, arg DeleteShoppingListParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteShoppingList, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteShoppingListsForUser = `-- name: DeleteShoppingListsForUser :exec
DELETE FROM shopping_lists WHERE owner_id = $1
`

// Used by Auth.DeleteUser, first in its chain of explicit pre-deletes. Not
// load-bearing today (shopping_items' references to other user-owned rows are
// ON DELETE SET NULL, not NO ACTION); see DeleteUser's doc comment.
func (q *Queries) DeleteShoppingListsForUser(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteShoppingListsForUser, userID)
	return err
}

const getShoppingItemForUserForUpdate = `-- name: GetShoppingItemForUserForUpdate :one
SELECT shopping_items.id, shopping_items.list_id, shopping_items.ingredient_id, shopping_items.name, shopping_items.quantity, shopping_items.unit, shopping_items.category, shopping_items.checked, shopping_items.checked_by, shopping_items.position, shopping_items.version, shopping_items.origin, shopping_items.created_at, shopping_items.updated_at FROM shopping_items
JOIN shopping_lists ON shopping_lists.id = shopping_items.list_id
WHERE shopping_items.id = $1
  AND shopping_items.list_id = $2
  AND shopping_lists.owner_id = $3
FOR UPDATE OF shopping_items
`

type GetShoppingItemForUserForUpdateParams struct {
	ID     uuid.UUID
	ListID uuid.UUID
	UserID uuid.UUID
}

// Locks the one item row for UpdateItem's version check and the UPDATE after
// it. The join is the ownership check; only the item row is locked.
func (q *Queries) GetShoppingItemForUserForUpdate(ctx context.Context, arg GetShoppingItemForUserForUpdateParams) (ShoppingItem, error) {
	row := q.db.QueryRow(ctx, getShoppingItemForUserForUpdate, arg.ID, arg.ListID, arg.UserID)
	var i ShoppingItem
	err := row.Scan(
		&i.ID,
		&i.ListID,
		&i.IngredientID,
		&i.Name,
		&i.Quantity,
		&i.Unit,
		&i.Category,
		&i.Checked,
		&i.CheckedBy,
		&i.Position,
		&i.Version,
		&i.Origin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getShoppingItems = `-- name: GetShoppingItems :many
SELECT id, list_id, ingredient_id, name, quantity, unit, category, checked, checked_by, position, version, origin, created_at, updated_at FROM shopping_items WHERE list_id = $1 ORDER BY position, id
`

func (q *Queries) GetShoppingItems(ctx context.Context, listID uuid.UUID) ([]ShoppingItem, error) {
	rows, err := q.db.Query(ctx, getShoppingItems, listID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ShoppingItem
	for rows.Next() {
		var i ShoppingItem
		if err := rows.Scan(
			&i.ID,
			&i.ListID,
			&i.IngredientID,
			&i.Name,
			&i.Quantity,
			&i.Unit,
			&i.Category,
			&i.Checked,
			&i.CheckedBy,
			&i.Position,
			&i.Version,
			&i.Origin,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getShoppingListForUser = `-- name: GetShoppingListForUser :one
SELECT id, owner_id, name, shared_with_partner, source_from, source_to, created_at, updated_at FROM shopping_lists
WHERE id = $1 AND owner_id = $2
`

type GetShoppingListForUserParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

// Owner-only visibility for now: shared_with_partner has no effect until the
// partner plan adds the partnerships table and an active-partner lookup. See
// "Not built yet" in backend/CLAUDE.md.
func (q *Queries) GetShoppingListForUser(ctx context.Context, arg GetShoppingListForUserParams) (ShoppingList, error) {
	row := q.db.QueryRow(ctx, getShoppingListForUser, arg.ID, arg.UserID)
	var i ShoppingList
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.SharedWithPartner,
		&i.SourceFrom,
		&i.SourceTo,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertShoppingItem = `-- name: InsertShoppingItem :one
INSERT INTO shopping_items (list_id, ingredient_id, name, quantity, unit, category, position, origin)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, list_id, ingredient_id, name, quantity, unit, category, checked, checked_by, position, version, origin, created_at, updated_at
`

type InsertShoppingItemParams struct {
	ListID       uuid.UUID
	IngredientID *uuid.UUID
	Name         string
	Quantity     *float64
	Unit         *string
	Category     string
	Position     int32
	Origin       string
}

func (q *Queries) InsertShoppingItem(ctx context.Context, arg InsertShoppingItemParams) (ShoppingItem, error) {
	row := q.db.QueryRow(ctx, insertShoppingItem,
		arg.ListID,
		arg.IngredientID,
		arg.Name,
		arg.Quantity,
		arg.Unit,
		arg.Category,
		arg.Position,
		arg.Origin,
	)
	var i ShoppingItem
	err := row.Scan(
		&i.ID,
		&i.ListID,
		&i.IngredientID,
		&i.Name,
		&i.Quantity,
		&i.Unit,
		&i.Category,
		&i.Checked,
		&i.CheckedBy,
		&i.Position,
		&i.Version,
		&i.Origin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listShoppingListsForUser = `-- name: ListShoppingListsForUser :many
SELECT id, owner_id, name, shared_with_partner, source_from, source_to, created_at, updated_at FROM shopping_lists
WHERE owner_id = $1
  AND (
    NOT $2::boolean
    OR (created_at, id) < ($3::timestamptz, $4::uuid)
  )
ORDER BY created_at DESC, id DESC
LIMIT $5
`

type ListShoppingListsForUserParams struct {
	UserID          uuid.UUID
	HasCursor       bool
	CursorCreatedAt time.Time
	CursorID        uuid.UUID
	RowLimit        int32
}

// Newest first. The row comparison is the keyset cursor over
// (created_at DESC, id DESC).
func (q *Queries) ListShoppingListsForUser(ctx context.Context, arg ListShoppingListsForUserParams) ([]ShoppingList, error) {
	rows, err := q.db.Query(ctx, listShoppingListsForUser,
		arg.UserID,
		arg.HasCursor,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.RowLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ShoppingList
	for rows.Next() {
		var i ShoppingList
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.SharedWithPartner,
			&i.SourceFrom,
			&i.SourceTo,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextShoppingItemPosition = `-- name: NextShoppingItemPosition :one
SELECT COALESCE(MAX(position) + 1, 0)::integer AS next_position
FROM shopping_items WHERE list_id = $1
`

func (q *Queries) NextShoppingItemPosition(ctx context.Context, listID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, nextShoppingItemPosition, listID)
	var next_position int32
	err := row.Scan(&next_position)
	return next_position, err
}

const setShoppingListSourceForUser = `-- name: SetShoppingListSourceForUser :one
UPDATE shopping_lists SET source_from = $1, source_to = $2
WHERE id = $3 AND owner_id = $4
RETURNING id, owner_id, name, shared_with_partner, source_from, source_to, created_at, updated_at
`

type SetShoppingListSourceForUserParams struct {
	SourceFrom pgtype.Date
	SourceTo   pgtype.Date
	ID         uuid.UUID
	UserID     uuid.UUID
}

// Used by ShoppingLists.Generate when regenerating an existing list. Being an
// UPDATE, it also takes the list row's write lock before the DELETE+INSERT
// of generated items that follows it, so two concurrent regenerations of one
// list serialize (see Generate in internal/service/shopping_lists.go).
func (q *Queries) SetShoppingListSourceForUser(ctx context.Context, arg SetShoppingListSourceForUserParams) (ShoppingList, error) {
	row := q.db.QueryRow(ctx, setShoppingListSourceForUser,
		arg.SourceFrom,
		arg.SourceTo,
		arg.ID,
		arg.UserID,
	)
	var i ShoppingList
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.SharedWithPartner,
		&i.SourceFrom,
		&i.SourceTo,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const touchShoppingListForUser = `-- name: TouchShoppingListForUser :one
UPDATE shopping_lists SET updated_at = now()
WHERE id = $1 AND owner_id = $2
RETURNING id, owner_id, name, shared_with_partner, source_from, source_to, created_at, updated_at
`

type TouchShoppingListForUserParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

// Bumps updated_at (via the shopping_lists_set_updated_at trigger) and, just
// as importantly, takes the list row's write lock: AddItem uses this instead
// of a plain SELECT so two concurrent adds cannot read the same
// NextShoppingItemPosition. See TouchMealForUser in meals.sql for the same
// pattern in the meals domain.
func (q *Queries) TouchShoppingListForUser(ctx context.Context, arg TouchShoppingListForUserParams) (ShoppingList, error) {
	row := q.db.QueryRow(ctx, touchShoppingListForUser, arg.ID, arg.UserID)
	var i ShoppingList
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.SharedWithPartner,
		&i.SourceFrom,
		&i.SourceTo,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateShoppingItem = `-- name: UpdateShoppingItem :one
UPDATE shopping_items SET
    name       = COALESCE($1, name),
    quantity   = CASE WHEN $2::boolean THEN $3 ELSE quantity END,
    unit       = CASE WHEN $4::boolean THEN $5 ELSE unit END,
    category   = COALESCE($6, category),
    checked_by = CASE
        WHEN $7::boolean IS NULL OR $7::boolean = checked THEN checked_by
        WHEN $7::boolean THEN $8::uuid
        ELSE NULL
    END,
    checked    = COALESCE($7::boolean, checked),
    version    = version + 1
WHERE id = $9
RETURNING id, list_id, ingredient_id, name, quantity, unit, category, checked, checked_by, position, version, origin, created_at, updated_at
`

type UpdateShoppingItemParams struct {
	Name        *string
	SetQuantity bool
	Quantity    *float64
	SetUnit     bool
	Unit        *string
	Category    *string
	Checked     *bool
	CheckedBy   *uuid.UUID
	ID          uuid.UUID
}

// Unconditional on version: ShoppingLists.UpdateItem has already locked the
// row (GetShoppingItemForUserForUpdate) and checked the version in the same
// transaction. checked_by follows checked, and is left alone when checked is
// absent or unchanged (the right-hand "checked" is the row's old value).
func (q *Queries) UpdateShoppingItem(ctx context.Context, arg UpdateShoppingItemParams) (ShoppingItem, error) {
	row := q.db.QueryRow(ctx, updateShoppingItem,
		arg.Name,
		arg.SetQuantity,
		arg.Quantity,
		arg.SetUnit,
		arg.Unit,
		arg.Category,
		arg.Checked,
		arg.CheckedBy,
		arg.ID,
	)
	var i ShoppingItem
	err := row.Scan(
		&i.ID,
		&i.ListID,
		&i.IngredientID,
		&i.Name,
		&i.Quantity,
		&i.Unit,
		&i.Category,
		&i.Checked,
		&i.CheckedBy,
		&i.Position,
		&i.Version,
		&i.Origin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateShoppingList = `-- name: UpdateShoppingList :one
UPDATE shopping_lists SET
    name                = COALESCE($1, name),
    shared_with_partner = COALESCE($2, shared_with_partner)
WHERE id = $3 AND owner_id = $4
RETURNING id, owner_id, name, shared_with_partner, source_from, source_to, created_at, updated_at
`

type UpdateShoppingListParams struct {
	Name              *string
	SharedWithPartner *bool
	ID                uuid.UUID
	UserID            uuid.UUID
}

func (q *Queries) UpdateShoppingList(ctx context.Context, arg UpdateShoppingListParams) (ShoppingList, error) {
	row := q.db.QueryRow(ctx, updateShoppingList,
		arg.Name,
		arg.SharedWithPartner,
		arg.ID,
		arg.UserID,
	)
	var i ShoppingList
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.SharedWithPartner,
		&i.SourceFrom,
		&i.SourceTo,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
