// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, password_hash, display_name)
VALUES ($1, $2, $3)
RETURNING id, email, password_hash, apple_sub, display_name, target_kcal, target_protein_g, target_carbs_g, target_fat_g, created_at, updated_at
`

type CreateUserParams struct {
	Email        string
	PasswordHash *string
	DisplayName  string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.PasswordHash, arg.DisplayName)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.AppleSub,
		&i.DisplayName,
		&i.TargetKcal,
		&i.TargetProteinG,
		&i.TargetCarbsG,
		&i.TargetFatG,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :execrows
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUser, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, apple_sub, display_name, target_kcal, target_protein_g, target_carbs_g, target_fat_g, created_at, updated_at FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.AppleSub,
		&i.DisplayName,
		&i.TargetKcal,
		&i.TargetProteinG,
		&i.TargetCarbsG,
		&i.TargetFatG,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, apple_sub, display_name, target_kcal, target_protein_g, target_carbs_g, target_fat_g, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.AppleSub,
		&i.DisplayName,
		&i.TargetKcal,
		&i.TargetProteinG,
		&i.TargetCarbsG,
		&i.TargetFatG,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE users SET
    display_name     = COALESCE($1, display_name),
    target_kcal      = CASE WHEN $2::boolean THEN $3 ELSE target_kcal END,
    target_protein_g = CASE WHEN $4::boolean THEN $5 ELSE target_protein_g END,
    target_carbs_g   = CASE WHEN $6::boolean THEN $7 ELSE target_carbs_g END,
    target_fat_g     = CASE WHEN $8::boolean THEN $9 ELSE target_fat_g END
WHERE id = $10
RETURNING id, email, password_hash, apple_sub, display_name, target_kcal, target_protein_g, target_carbs_g, target_fat_g, created_at, updated_at
`

type UpdateUserProfileParams struct {
	DisplayName       *string
	SetTargetKcal     bool
	TargetKcal        *float64
	SetTargetProteinG bool
	TargetProteinG    *float64
	SetTargetCarbsG   bool
	TargetCarbsG      *float64
	SetTargetFatG     bool
	TargetFatG        *float64
	ID                uuid.UUID
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserProfile,
		arg.DisplayName,
		arg.SetTargetKcal,
		arg.TargetKcal,
		arg.SetTargetProteinG,
		arg.TargetProteinG,
		arg.SetTargetCarbsG,
		arg.TargetCarbsG,
		arg.SetTargetFatG,
		arg.TargetFatG,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.AppleSub,
		&i.DisplayName,
		&i.TargetKcal,
		&i.TargetProteinG,
		&i.TargetCarbsG,
		&i.TargetFatG,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
